import { AI_DIFFICULTY_OPTIONS } from '../../games/schafkopf/schafkopf';
import { DEFAULT_BOT_CONFIG, type BotConfig, type TipCode } from '../../games/schafkopf/botConfig';
export default function SchafkopfBotSettings({value,onChange,disabled}: {value:BotConfig;onChange:(value:BotConfig)=>void;disabled:boolean}) {
  return <div className="sk-bot-settings"><h3>Bot-Verhalten nach deinem Regelwerk</h3><p>R-Regeln und A1–A3 gelten unabhängig von Tipp-Fehlern. Anfänger verwenden nur Hand und aktuellen Stich; Amateur nutzt Tipps mit den angegebenen Trefferquoten. Ab Fortgeschritten zählen die Bots Trümpfe und merken sich Farbfreiheit. Profi wägt Tipps mit Punkten ab. Legende simuliert mögliche Kartenverteilungen.</p>
    <p>Anfänger zeigt zufällig eine Regel, Amateur eine Regel oder einen Tipp, Fortgeschritten einen Tipp. Die Stich-Review prüft beide.</p>
    <div className="sk-source-table"><table><caption>Trefferquoten je Tipp in Prozent</caption><thead><tr><th>Tipp</th>{AI_DIFFICULTY_OPTIONS.map(level => <th key={level.id}>{level.label}</th>)}</tr></thead><tbody>{(Object.keys(value.reliability.beginner) as TipCode[]).map(tip => <tr key={tip}><th scope="row">{tip}</th>{AI_DIFFICULTY_OPTIONS.map(level => <td key={level.id}>{level.id === 'beginner' ? 'aus' : level.id === 'legend' ? 'Simulation' : <input aria-label={`${tip} ${level.label} Trefferquote`} type="number" min="0" max="100" value={Math.round(value.reliability[level.id][tip]*100)} disabled={disabled || tip === 'T9' || tip === 'T7' && level.id !== 'amateur'} onChange={event => onChange({...value,reliability:{...value.reliability,[level.id]:{...value.reliability[level.id],[tip]:Math.max(0,Math.min(100,Number(event.target.value)))/100}}})}/>}</td>)}</tr>)}</tbody></table></div>
    <p>T9: Bei bewiesener Trumpflosigkeit beider Gegenspieler suchen Anfänger weiterhin immer, Amateur zu 75 %, Fortgeschritten zu 50 %, Profi zu 25 % und Legende nie. Die Matrix zeigt die Gegenwahrscheinlichkeit für das Befolgen von T9 (nicht suchen).</p>
    <fieldset><legend>Ansage-Abweichungen</legend>{(['beginner','amateur'] as const).map(level => <label key={level}>{level === 'beginner' ? 'Anfänger' : 'Amateur'} · Ansageabweichung (%)<input type="number" min="0" max="100" disabled={disabled} value={Math.round(value.announcementError[level]*100)} onChange={event => onChange({...value,announcementError:{...value.announcementError,[level]:Math.max(0,Math.min(100,Number(event.target.value)))/100}})}/></label>)}<label>Amateur · Spritzchance bei außergewöhnlicher Hand (%)<input type="number" min="0" max="100" disabled={disabled} value={Math.round(value.amateurSpritzChance*100)} onChange={event => onChange({...value,amateurSpritzChance:Math.max(0,Math.min(100,Number(event.target.value)))/100})}/></label></fieldset>
    <fieldset><legend>Ansage-Schwellen</legend>{([['sauspielWithBremserMin','Sauspiel · Trümpfe mit Bremser'],['sauspielWithoutBremserMin','Sauspiel · Trümpfe ohne Bremser'],['soloMinTrumps','Solo · Trümpfe mindestens'],['soloMinOber','Solo · Ober mindestens'],['farbwenzMinTrumps','Farbwenz · Trümpfe mindestens'],['farbwenzMinUnter','Farbwenz · Unter mindestens']] as const).map(([key,label]) => <label key={key}>{label}<input type="number" min="1" max="8" value={value[key]} disabled={disabled} onChange={event => onChange({...value,[key]:Math.max(1,Math.min(8,Number(event.target.value)))})}/></label>)}</fieldset>
    <fieldset><legend>Profi und Legende</legend><label>Profi · Gesamtfehlerquote (%)<input type="number" min="0" max="100" disabled={disabled} value={Math.round(value.proError*100)} onChange={event => onChange({...value,proError:Math.max(0,Math.min(100,Number(event.target.value)))/100})}/></label>{([['legendIterations','Simulationen je Zug',1,1000],['legendTimeMs','Zeitbudget je Zug (ms)',1,2000],['announcementSamples','Verteilungen für Ansagen',1,200]] as const).map(([key,label,min,max]) => <label key={key}>{label}<input type="number" min={min} max={max} value={value[key]} disabled={disabled} onChange={event => onChange({...value,[key]:Math.max(min,Math.min(max,Number(event.target.value)))})}/></label>)}</fieldset>
    <details><summary>Technische Startwerte für offene Präzisierungen</summary><p>R4a verwendet die konservative Sicherheitsbedingung aus Teil 1. Die Grenzwerte sind anpassbar.</p>{([['r4aMinTrumps','R4a · eigene Trümpfe mindestens'],['r4aRemainingTrumps','R4a · verbleibende Trümpfe mindestens'],['r4aRemainingHigh','R4a · verbleibende der höchsten sechs'],['manyTrumps','T12 · viele Trümpfe'],['manyHigh','T12 · viele Ober'],['manyCourt','T12 · Ober/Unter insgesamt']] as const).map(([key,label]) => <label key={key}>{label}<input type="number" min="1" max="8" value={value[key]} disabled={disabled} onChange={event => onChange({...value,[key]:Math.max(1,Math.min(8,Number(event.target.value)))})}/></label>)}</details>
    <button type="button" className="sk-button sk-secondary" disabled={disabled} onClick={() => onChange(structuredClone(DEFAULT_BOT_CONFIG))}>Dokument-Startwerte wiederherstellen</button>
  </div>;
}
