import { lazy, Suspense, useEffect, useState } from 'react';
import type { BotDifficulty, GameResult, ScenarioId } from '../../games/natura/naturaData';
import { SCENARIOS } from '../../games/natura/naturaData';
import { dailyExpedition, expeditionPoints, loadJournal, recordExpedition } from '../../games/natura/journal';
import NaturaGame from './NaturaGame';
import SpecimenPlate from './SpecimenPlate';
const DidYouKnow=lazy(()=>import('./DidYouKnow'));
const routes: {id:string;name:string;habitats:ScenarioId[];description:string}[] = [
  {id:'adaptation',name:'The art of adaptation',habitats:['cuttlefish','archerfish','flyingfish'],description:'Disguise yourself, predict a catch, and escape between sea and sky.'},
  {id:'canopy',name:'From roots to canopy',habitats:['trapjaw','bolas','jumpingspider'],description:'Launch from the forest floor, hunt with silk, and climb to the summit.'},
  {id:'survival',name:'Shelter, hunt, survive',habitats:['coconut','meadow','spermwhale'],description:'Carry your cover, watch the meadow, and make a deep dive.'},
];
export default function NaturaExpedition({onExit}:{onExit:()=>void}) {
  const [daily,setDaily]=useState(()=>dailyExpedition()),[route,setRoute]=useState('adaptation'),[difficulty,setDifficulty]=useState<BotDifficulty>('normal'),[challenge,setChallenge]=useState<'classic'|'wild'>('classic');
  const [stage,setStage]=useState<'setup'|'game'|'between'|'done'>('setup'),[index,setIndex]=useState(0),[results,setResults]=useState<GameResult[]>([]),[seed,setSeed]=useState(1);
  useEffect(()=>{if(stage!=='setup')return;const timer=window.setInterval(()=>{const next=dailyExpedition();setDaily(previous=>previous.id===next.id?previous:next);},1000);return()=>window.clearInterval(timer);},[stage]);
  const habitats=route==='daily'?daily.habitats:routes.find(r=>r.id===route)!.habitats;
  const id=route==='daily'?daily.id:`${route}:${difficulty}:${challenge}`,effectiveDifficulty=route==='daily'?'normal':difficulty,effectiveChallenge=route==='daily'?'classic':challenge;
  const score=results.reduce((sum,r,i)=>sum+expeditionPoints(habitats[i],r),0),scenario=habitats[index],descriptor=SCENARIOS.find(s=>s.id===scenario)!;
  const finish=(r:GameResult)=>{const next=[...results,r];setResults(next);if(index===2){recordExpedition(id,next.reduce((sum,result,i)=>sum+expeditionPoints(habitats[i],result),0));setStage('done');}else setStage('between');};
  if(stage==='game')return <NaturaGame key={`${seed}-${index}`} scenario={scenario} mode="ai" botDifficulty={effectiveDifficulty} round={1} initialLevel={0} lockedCourse options={{seed:seed+index*7919,challenge:effectiveChallenge,role:scenario==='meadow'?'falcon':undefined}} turnLabel={`EXPEDITION / STUDY ${index+1} OF 3 / ${score} POINTS`} onComplete={finish} onExit={onExit}/>;
  return <main className="nm-page"><section className="nf-session ne-session"><button className="nf-button" onClick={onExit}>← Habitats</button><p className="nm-eyebrow">NATURA / CONNECTED EXPEDITIONS</p><h1>{stage==='setup'?'Follow a trail.':stage==='done'?'Expedition complete.':'One discovery leads to another.'}</h1>
    {stage==='setup'?<><p>Three habitats, one expedition score. Each study awards up to 100 points for progress, victory and remaining hearts. Daily expeditions use the same seed and Medium difficulty for everyone, with a new trail at midnight in Berlin.</p><div className="ne-routes">{[...routes,{id:'daily',name:`Daily expedition · ${daily.day}`,habitats:daily.habitats,description:'Today’s repeatable trail. Improve your personal expedition best.'}].map(r=><button key={r.id} aria-pressed={route===r.id} onClick={()=>setRoute(r.id)}><strong>{r.name}</strong><span>{r.description}</span></button>)}</div>{route!=='daily'&&<div className="nf-form-grid"><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value as BotDifficulty)}><option value="easy">Easy</option><option value="normal">Medium</option><option value="hard">Hard</option></select></label><label>Habitat rules<select value={challenge} onChange={e=>setChallenge(e.target.value as 'classic'|'wild')}><option value="classic">Classic</option><option value="wild">Wild challenge</option></select></label></div>}<ol className="ne-trail">{habitats.map(s=><li key={s}>{SCENARIOS.find(d=>d.id===s)!.title}</li>)}</ol><p>Personal expedition best: {loadJournal().expeditions[id]??0}/300</p><button className="nf-primary" onClick={()=>{setSeed(route==='daily'?daily.seed:crypto.getRandomValues(new Uint32Array(1))[0]);setStage('game');}}>Start expedition</button></>:<><div className="nm-assessment"><b>{score}/300</b><span>Expedition points<br/>Personal best {loadJournal().expeditions[id]??0}/300</span></div><div className="ne-recap">{results.map((r,i)=><article key={i}><SpecimenPlate id={habitats[i]}/><h3>{SCENARIOS.find(s=>s.id===habitats[i])!.title}</h3><b>{expeditionPoints(habitats[i],r)}/100 points</b><p>{r.review?.tip??r.detail}</p></article>)}</div>{stage==='between'?<><h2>Next: {SCENARIOS.find(s=>s.id===habitats[index+1])!.title}</h2><Suspense fallback={null}><DidYouKnow scenario={scenario}/></Suspense><button className="nf-primary" onClick={()=>{setIndex(i=>i+1);setStage('game');}}>Continue expedition →</button></>:<><p>You observed three different ways animals adapt. Your habitat records and expedition best are saved in your journal.</p><button className="nf-primary" onClick={()=>{setResults([]);setIndex(0);setStage('setup');}}>Choose another trail</button></>}</>}
    <p className="ne-current">{stage==='setup'?'':descriptor.setting}</p>
  </section></main>;
}
