import { SCENARIOS } from '../../games/natura/naturaData';
import { STUDIES, difficultyLabel } from '../../games/natura/studies';
import { habitatRecord, type Journal } from '../../games/natura/journal';
import FieldDialog from './FieldDialog';
import SpecimenPlate from './SpecimenPlate';
export default function NaturaJournal({journal,close}:{journal:Journal;close:()=>void}) {
  return <FieldDialog title="Your field journal" close={close} className="nj-dialog"><div className="nj-heading"><div><p className="nm-eyebrow">NATURA / YOUR DISCOVERIES</p><h2>Field journal.</h2></div><button className="nf-button" onClick={close}>Close</button></div><p>Complete a habitat to collect its specimen illustration and observation. Personal bests are separated by course, difficulty, animal role and habitat rules. Progress is saved in this browser.</p><div className="nj-grid">{SCENARIOS.map(s=>{
    const record=habitatRecord(journal,s.id),unlocked=record.wins>0;
    return <article key={s.id} style={{color:STUDIES[s.id].accent}}><div className={unlocked?'nj-plate':'nj-plate is-locked'}>{unlocked?<SpecimenPlate id={s.id}/>:<span>Complete this habitat<br/>to collect its illustration</span>}</div><h3>{s.title}</h3><p>{record.attempts} runs · {record.wins} wins · {record.medals} course medals</p><p>{journal.practice[s.id]?'✓ Field skill practised':'Field skill awaits'} · Quiz {journal.quizzes[s.id]??0}/6</p>{unlocked&&<p>{s.behaviour} <a href={s.source.url} target="_blank" rel="noreferrer">Field source ↗</a></p>}<details><summary>Course records</summary>{Object.entries(journal.runs).filter(([key])=>key.startsWith(s.id+':')).map(([key,r])=>{const [,level,difficulty,challenge,variant,role]=key.split(':');return <p key={key}>Course {Number(level)+1} · {difficultyLabel(difficulty as 'easy'|'normal'|'hard')} · {challenge} · {variant} · {role}<br/>{r.medal?`${r.medal} medal`:'Working toward a medal'} · Best progress {r.bestProgress.toFixed(1)}{r.bestTime!==null?` · Best win ${r.bestTime.toFixed(1)}s`:''}</p>;})}{record.attempts===0&&<p>Play a scored single-player run to begin.</p>}</details></article>;
  })}</div><p className="nj-medal-note">Win for bronze. In games with hearts, finish with two for silver or three for gold. Completing the kestrel hunt earns gold. Spider runs use falls: a clean run earns silver, or gold in under 100 seconds.</p></FieldDialog>;
}
