import { gameUi, useGameLanguage } from "../../i18n/gameUi.ts";
import GameXpReward from "@/components/games/GameXpReward";
import { useEffect, useRef, useState } from 'react';
import InviteFriendButton from '../chess/InviteFriendButton';
import { usePublishRoom } from '../social/currentRoom';
import { Link } from 'react-router-dom';
import { ArrowLeft, Check, Copy, Globe, Link as LinkIcon, Users } from 'lucide-react';
import { NaturaConnection } from '../../games/natura/network';
import { useAuth } from '../../context/AuthContext';
import { SCENARIOS, type ScenarioId } from '../../games/natura/naturaData';
import { SNAP_LEVELS } from '../../games/natura/wildModes';
import { SPIDER_COURSES } from '../../games/natura/expeditions';
import type { NaturaConfig, PrivateState } from '../../games/natura/protocol';
import NaturaGame from './NaturaGame';
const inviteCode=()=>new URLSearchParams(location.search).get('naturaRoom')?.toUpperCase().slice(0,6)??'';
/** Online rooms use a private relay channel that only signed-in players may join. */
export default function NaturaOnline(props:{scenario:ScenarioId;onExit:()=>void}) {
  useGameLanguage();
  const {user,loading}=useAuth();
  if(user)return <NaturaOnlineRoom {...props}/>;
  return <main className="nm-page"><section className="nf-session nf-session-online"><button className="nf-button" onClick={props.onExit}><ArrowLeft size={17}/>{gameUi(" Habitats")}</button><p className="nm-eyebrow">{gameUi("NATURA / ONLINE MULTIPLAYER")}</p><Globe size={36}/>
    {loading?<p className="nf-connection-status" role="status">{gameUi("Checking your account…")}</p>:<><h1>{gameUi("You’re not logged in.")}</h1><p role="status">{gameUi("You need an account to play Natura online. Create one for free, or log in if you already have one. Single-player, hotseat and local two-player studies work without an account.")}</p><div className="nm-result-actions"><Link className="nf-primary" to="/login?register">{gameUi("Create account")}</Link><Link className="nf-button" to="/login">{gameUi("Log in")}</Link></div></>}
  </section></main>;
}
function NaturaOnlineRoom({scenario,onExit}:{scenario:ScenarioId;onExit:()=>void}) {
  useGameLanguage();
  const [connection,setConnection]=useState<NaturaConnection|null>(null),[state,setState]=useState<PrivateState|null>(null),[status,setStatus]=useState('Ready to connect'),[error,setError]=useState('');
  const {profile}=useAuth(),[name,setName]=useState(()=>profile?.username||profile?.display_name||'Player'),[code,setCode]=useState(inviteCode),[copied,setCopied]=useState('');const joinOnArrival=useRef(new URLSearchParams(location.search).get('join')==='1');
  const [config,setConfig]=useState<NaturaConfig>({scenario,level:0,seed:crypto.getRandomValues(new Uint32Array(1))[0],variant:'race',difficulty:'normal'});
  useEffect(()=>{const c=new NaturaConnection(next=>{setState(next);if(next){const url=new URL(location.href);url.searchParams.set('naturaRoom',next.room.code);history.replaceState(history.state,'',url);}},(message,problem)=>{setStatus(message);if(problem)setError(problem);else if(message==='Connected'||message==='Ready to connect')setError('');});setConnection(c);c.resume(inviteCode());return()=>c.close();},[]);
  const room=state?.room,host=room?.host===connection?.id,online=!!connection?.connected;
  const current=room?.config??config,descriptor=SCENARIOS.find(s=>s.id===current.scenario)!;
  const courses=current.scenario==='trapjaw'?SNAP_LEVELS.map(c=>c.name):current.scenario==='jumpingspider'?SPIDER_COURSES:[];
  const send=(msg:Parameters<NaturaConnection['send']>[0])=>{setError('');connection?.send(msg);};
  usePublishRoom(room?{lobbyRoute:'/games/natura',code:room.code}:null);
  // An accepted invite (`?join=1`) takes the seat as soon as the connection is up.
  useEffect(()=>{if(!joinOnArrival.current||room||!online||code.length!==6||!name.trim())return;joinOnArrival.current=false;const url=new URL(location.href);url.searchParams.delete('join');history.replaceState(history.state,'',url);connection?.send({type:'JOIN',name,code});},[room,online,code,name,connection]);
  const exit=()=>{if(room)send({type:'LEAVE'});const url=new URL(location.href);url.searchParams.delete('naturaRoom');history.replaceState(history.state,'',url);onExit();};
  const change=(next:NaturaConfig)=>{if(room)send({type:'CONFIG',config:next});else setConfig(next);};
  const copy=async(link=false)=>{if(!room)return;try{const url=new URL(location.href);url.searchParams.set('naturaRoom',room.code);await navigator.clipboard.writeText(link?url.toString():room.code);setCopied(link?'Invite link copied':'Room code copied');}catch{setError(`Copy this room code: ${room.code}`);}};
  if(room&&state?.world&&(room.status==='playing'||room.status==='paused'))return <><NaturaGame key={`${room.code}-${room.round}`} scenario={current.scenario} mode="hotseat" round={1} remote={connection!} initialLevel={current.level} lockedCourse turnLabel={`ONLINE / ${room.code} / ${room.members[state.seat]?.name??'You'}`} onComplete={()=>{}} onExit={exit}/>{error&&<div className="nf-network-error" role="alert">{gameUi(error)}<button onClick={()=>setError('')}>{gameUi("Dismiss")}</button></div>}</>;
  return <main className="nm-page"><section className="nf-session nf-session-online"><button className="nf-button" onClick={exit}><ArrowLeft size={17}/>{gameUi(" Habitats")}</button><p className="nm-eyebrow">{gameUi("NATURA / ONLINE MULTIPLAYER")}</p><Globe size={36}/><h1>{gameUi(room?descriptor.title:'Explore together.')}</h1><p className="nf-connection-status" role="status">{gameUi(status)}</p>{error&&<p className="nf-session-error" role="alert">{gameUi(error)}</p>}
    {!room?<><p>{gameUi("Create an invite-code room, or join a friend. Each device controls one animal; the room creator’s browser runs the match and Supabase connects the players.")}</p><div className="nf-form-grid"><label>{gameUi("Your name")}<input maxLength={24} value={name} onChange={e=>setName(e.target.value)}/></label><label>{gameUi("Habitat")}<select value={config.scenario} onChange={e=>setConfig(c=>({...c,scenario:e.target.value as ScenarioId,level:0,variant:'race'}))}>{SCENARIOS.map(s=><option key={s.id} value={s.id}>{gameUi(s.title)}</option>)}</select></label></div></>:<><p className="nm-eyebrow">{gameUi("INVITE CODE")}</p><div className="nf-room-code"><strong>{room.code}</strong><button className="nf-button" onClick={()=>void copy()} aria-label={gameUi("Copy room code")}><Copy size={18}/></button><button className="nf-button" onClick={()=>void copy(true)}><LinkIcon size={17}/>{gameUi(" Invite link")}</button></div>{copied&&<p role="status">{gameUi(copied)}</p>}<div className="nf-members">{room.members.map((member,i)=><article key={i}><Users size={20}/><strong>{gameUi(member?.name??'Waiting for a friend')}</strong><span>{gameUi(member?member.connected?member.ready?'Ready':'Not ready':'Disconnected':'Share the invite code')}</span>{member?.ready&&<Check size={19}/>}{!member&&<InviteFriendButton room={{lobbyRoute:'/games/natura',code:room.code}}/>}</article>)}</div></>}
    {(!room||room.status==='lobby')&&<><div className="nf-form-grid">{room&&<label>{gameUi("Habitat")}<select disabled={!host} value={current.scenario} onChange={e=>change({...current,scenario:e.target.value as ScenarioId,level:0,variant:'race'})}>{SCENARIOS.map(s=><option key={s.id} value={s.id}>{gameUi(s.title)}</option>)}</select></label>}{courses.length>0&&<label>{gameUi("Course")}<select disabled={!!room&&!host} value={current.level} onChange={e=>change({...current,level:Number(e.target.value)})}>{courses.map((c,i)=><option value={i} key={gameUi(c)}>{gameUi(i+1)}. {gameUi(c)}</option>)}</select></label>}{current.scenario==='spermwhale'&&<label>{gameUi("Challenge")}<select disabled={!!room&&!host} value={current.variant} onChange={e=>change({...current,variant:e.target.value as NaturaConfig['variant']})}><option value="race">{gameUi("Two whales racing")}</option><option value="pursuit">{gameUi("Whale vs squid")}</option></select></label>}</div>
      <p className="nf-session-note">{gameUi(current.scenario==='meadow'?'Player 1 is the kestrel; Player 2 is the vole. Each animal receives its own view; the room host holds the full match.':current.scenario==='spermwhale'&&current.variant==='pursuit'?'Player 1 is the whale; Player 2 is the squid. The squid has burst and ink. Each creature gets its own view; the room host holds the full match.':'Both players use WASD / Space and their own touch controls. No shared keyboard is required.')}{gameUi(" Keep the host’s tab open. Guest disconnects pause the round and hold their seat for 20 seconds; closing or reloading the host ends the room.")}</p>
      {room?<div className="nm-result-actions"><button className="nf-primary" disabled={!online} onClick={()=>send({type:'READY',ready:!room.members[state!.seat]?.ready})}>{gameUi(room.members[state!.seat]?.ready?'Not ready':'I’m ready')}</button>{host&&<button className="nf-button" disabled={!online||!room.members.every(m=>m?.connected&&m.ready)} onClick={()=>send({type:'START'})}>{gameUi("Start round")}</button>}</div>:<><button className="nf-primary" disabled={!online||!name.trim()} onClick={()=>send({type:'CREATE',name,config})}>{gameUi("Create room")}</button><div className="nf-join"><label>{gameUi("Friend’s room code")}<input maxLength={6} value={code} autoCapitalize="characters" onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))} placeholder={gameUi("ABC234")}/></label><button className="nf-button" disabled={!online||!name.trim()||code.length!==6} onClick={()=>send({type:'JOIN',name,code})}>{gameUi("Join room")}</button></div></>}
    </>}
    {room?.status==='finished'&&<><GameXpReward /><h2>{gameUi(state?.result?.winner===null?'An even match.':`${room.members[state?.result?.winner??0]?.name??'The other player'} wins.`)}</h2><p>{gameUi(state?.result?.detail)}</p><p className="nf-room-score">{gameUi(room.scores[0])} : {gameUi(room.scores[1])} <span>{gameUi("match points")}</span></p>{host?<button className="nf-primary" onClick={()=>send({type:'REMATCH'})}>{gameUi("Return to lobby for another round")}</button>:<p>{gameUi("Waiting for the host to reopen the lobby.")}</p>}</>}
  </section></main>;
}
