import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {EAT,FOOD,playerRadius} from '../src/games/eat-it/config.ts';
import {createGame,stepGame,collectPower,eliminate} from '../src/games/eat-it/engine.ts';
import {activateAbility,abilityAvailable,jumpHeight,ABILITY_KEYS} from '../src/games/eat-it/abilities.ts';
import {startHell,blackHoles,cellCenter,cellIndex,spawnHellSpeed,spawnHellStrikes,hellBotInput} from '../src/games/eat-it/hell.ts';
import {foodFits,canopyFits,isChoking,mouthPosition,MOUTH} from '../src/games/eat-it/rules.ts';
import {canUnderpass} from '../src/games/eat-it/progression.ts';
import {fallPose,objectHeight} from '../src/games/eat-it/falling.ts';
import {SPIT_DURATION,spitPose} from '../src/games/eat-it/choking.ts';
import {botInput} from '../src/games/eat-it/bots.ts';
import {updateSpawns} from '../src/games/eat-it/spawn.ts';
import {stepEncounter,QUEST} from '../src/games/eat-it/quests.ts';
import {escapeAvailable,activateEscape} from '../src/games/eat-it/escape.ts';
import {applyRoomAction} from '../src/games/eat-it/authority.ts';
import {SnapshotBuffer} from '../src/games/eat-it/presentation.ts';
function scene(options={}){const s=createGame('city',[{id:'a',name:'A'},{id:'b',name:'B'}],84,'abilities',{mode:'solo',...options});s.food=[];s.powerups=[];delete s.encounter;s.nextFood=s.nextPower=s.nextPluto=s.nextBig=1e9;s.players.forEach((p,i)=>Object.assign(p,{x:1500+i*1000,y:1500,facing:0}));return s;}
function hell(options={}){const s=scene(options);startHell(s);s.time=s.hell.readyAt;s.phase='hell';for(const b of blackHoles(s))b.warnUntil=1e9;s.nextPower=s.hell.nextEruption=1e9;Object.assign(s.players[0],cellCenter(8*EAT.hell.columns+8));Object.assign(s.players[1],cellCenter(2*EAT.hell.columns+25));return s;}
const ticks=(s,n)=>{for(let i=0;i<n;i++)stepGame(s)};
function pickup(s,kind,p=s.players[0]){const item={id:s.nextId++,kind,x:p.x,y:p.y};s.powerups.push(item);collectPower(s,p,item);return item;}
function gap(s){const p=s.players[0],idx=cellIndex(p);for(let col=1;col<=3;col++)s.hell.cells[idx+col]=-1;return idx;}
function prop(s,kind){const p=s.players[0],f={...mouthPosition(p,playerRadius(p,s.time)),id:s.nextId++,kind,z:0,vx:0,vy:0,vz:0,rotation:0,target:null,capturedAt:0};s.food.push(f);return f;}

test('Jump pickup is Hell-only, holds exactly one charge, never auto-activates or overwrites',()=>{const normal=scene();pickup(normal,'jump');assert.equal(normal.players[0].storedJump,undefined);const s=hell(),p=s.players[0];pickup(s,'jump');assert.ok(p.storedJump);assert.equal(p.ability,undefined);const duplicate=pickup(s,'jump');assert.ok(s.powerups.includes(duplicate));assert.equal(p.stats.collected.jump,1);assert.ok(activateAbility(s,p,'jump'));assert.equal(p.storedJump,false);assert.equal(activateAbility(s,p,'jump'),false);assert.equal(p.stats.jumpUses,1);});

test('Jump visibly rises across three destroyed tiles and lands at its bounded endpoint',()=>{const s=hell(),p=s.players[0],x=p.x;gap(s);pickup(s,'jump');activateAbility(s,p,'jump');ticks(s,14);assert.ok(jumpHeight(p,s.time)>100);assert.equal(p.fallingAt,undefined);assert.ok(p.alive);ticks(s,15);assert.equal(p.ability,undefined);assert.equal(p.fallingAt,undefined);assert.equal(p.x,x+EAT.powerups.jump.distance);assert.equal(p.stats.gapJumps,1);});

test('invalid Jump landing immediately resumes falling with no rescue teleport',()=>{const s=hell(),p=s.players[0],idx=gap(s),x=p.x;s.hell.cells[idx+4]=-1;pickup(s,'jump');activateAbility(s,p,'jump');ticks(s,28);assert.equal(p.fallingAt,undefined);ticks(s,1);assert.ok(p.fallingAt);assert.equal(p.x,x+320);assert.equal(p.stats.gapJumps??0,0);ticks(s,25);assert.equal(p.alive,false);});

for(const kind of ['jump','strike'])test(`${kind} rejects dead, respawning, choking, stunned, falling, escaping, airborne and transition states`,()=>{for(const block of [p=>p.alive=false,p=>p.respawnAt=5,p=>p.chokingUntil=100,p=>p.stunnedUntil=100,p=>p.fallingAt=0,p=>p.escape={},p=>p.ability={kind:'jump'}]){const s=hell(),p=s.players[0];p.storedJump=p.storedStrike=true;block(p);assert.equal(activateAbility(s,p,kind),false);assert.ok(p.storedJump&&p.storedStrike);}const s=hell(),p=s.players[0];p.storedJump=p.storedStrike=true;s.phase='transition';assert.equal(activateAbility(s,p,kind),false);s.phase='hell';s.hell.cells[cellIndex(p)]=-1;assert.equal(activateAbility(s,p,kind),false);});

test('Strike holds one use, winds up, lunges forward, decelerates and keeps its feet down',()=>{const s=scene(),p=s.players[0],x=p.x;pickup(s,'strike');assert.equal(p.ability,undefined);const duplicate=pickup(s,'strike');assert.ok(s.powerups.includes(duplicate));s.powerups=[];assert.ok(activateAbility(s,p,'strike'));assert.equal(activateAbility(s,p,'strike'),false);assert.equal(p.storedStrike,false);ticks(s,1);assert.equal(p.x,x);ticks(s,2);const fast=p.vx;ticks(s,8);assert.ok(p.vx<fast);assert.equal(jumpHeight(p,s.time),0);ticks(s,5);assert.equal(p.ability,undefined);const lunge=EAT.powerups.strike.distance;assert.ok(p.x-x>lunge*.88&&p.x-x<lunge*1.09);assert.equal(p.stats.strikeUses,1);assert.equal(ABILITY_KEYS.strike,'Space');assert.equal(ABILITY_KEYS.jump,'KeyJ');});

for(const scenario of ['valid','too big','shield'])test(`Strike PvP preserves mouth and 130% rules: ${scenario}`,()=>{const s=scene(),[p,v]=s.players;p.mass=144;v.mass=scenario==='too big'?144:36;Object.assign(v,{x:p.x+130,y:p.y});if(scenario==='shield')v.effects.shield=100;pickup(s,'strike');activateAbility(s,p,'strike');ticks(s,15);assert.equal(v.alive,scenario!=='valid');assert.equal(p.stats.strikeDevours??0,scenario==='valid'?1:0);});

test('grounded Strike falls into the first missing Hell tile',()=>{const s=hell(),p=s.players[0],x=p.x;gap(s);pickup(s,'strike');activateAbility(s,p,'strike');ticks(s,6);assert.ok(p.fallingAt);assert.ok(p.x<x+180);assert.equal(p.ability,undefined);});

test('rare Hell items spawn only on safe reachable floor, outside players and obey active caps',()=>{const s=hell();let jump=0,strike=0;for(let i=0;i<160;i++){s.time+=12;s.nextPower=0;spawnHellSpeed(s);s.hell.nextStrike=0;spawnHellStrikes(s);assert.ok(s.powerups.length<=4);assert.ok(s.powerups.filter(p=>p.kind==='jump').length<=1);assert.ok(s.powerups.filter(p=>p.kind==='strike').length<=1);for(const item of s.powerups){assert.equal(s.hell.cells[cellIndex(item)],0);assert.ok(s.players.every(p=>Math.hypot(p.x-item.x,p.y-item.y)>playerRadius(p,s.time)+EAT.powerups.radius));if(item.kind==='jump')jump++;if(item.kind==='strike')strike++;}s.powerups=[];}assert.ok(jump>4&&strike>2);const n=scene();let found=false;for(let i=0;i<300;i++){n.time=i*5;n.nextPower=0;updateSpawns(n);assert.ok(n.powerups.every(p=>p.kind!=='jump'));found ||= n.powerups.some(p=>p.kind==='strike');n.powerups=[];}assert.ok(found);});

for(const botDifficulty of ['easy','medium','hard'])test(`${botDifficulty} bot uses a held Jump from a threatened isolated tile`,()=>{const s=hell({botDifficulty}),p=s.players[0];const idx=cellIndex(p);s.hell.cells.fill(-1);s.hell.cells[idx]=s.time-.1;for(let row=-1;row<=1;row++)for(let col=3;col<=5;col++)s.hell.cells[idx+row*EAT.hell.columns+col]=0;p.storedJump=true;hellBotInput(s,p);assert.equal(p.ability?.kind,'jump');assert.equal(p.storedJump,false);});

for(const botDifficulty of ['easy','medium','hard'])test(`${botDifficulty} bot uses Strike in a valid prey line`,()=>{const s=scene({botDifficulty}),[p,v]=s.players;p.mass=144;p.storedStrike=true;Object.assign(v,{x:p.x+160,y:p.y});botInput(s,p);assert.equal(p.ability?.kind,'strike');assert.equal(p.storedStrike,false);});

for(const kind of ['house','car'])test(`${kind} permits continuous underpassing up to actual mouth fit, then physical capture`,()=>{const s=scene(),p=s.players[0],f=prop(s,kind),threshold=FOOD[kind].devourArea/Math.PI/(4*MOUTH.radius)**2;for(const mass of [36,100,threshold*.8,threshold*.999]){p.mass=mass;assert.equal(foodFits(p,f),false);assert.ok(canUnderpass(p,f,s.time));p.x=f.x-FOOD[kind].width;p.y=f.y;p.input={x:1,y:0};p.vx=p.vy=0;ticks(s,100);assert.ok(p.x>f.x+FOOD[kind].width/2);assert.equal(f.target,null);}p.mass=threshold*1.01;Object.assign(p,{x:f.x,y:f.y,vx:0,vy:0,input:{x:0,y:0}});ticks(s,1);assert.equal(f.target,p.id);assert.ok(f.z>-2);ticks(s,60);assert.equal(s.food.includes(f),false);assert.equal(p.foodEaten,1);});

test('tree trunk descends upright before canopy contact, chokes for the choke duration, reverses out then settles without growth',()=>{const s=scene(),p=s.players[0],f=prop(s,'tree'),mass=p.mass;ticks(s,1);assert.equal(f.target,p.id);ticks(s,8);assert.equal(isChoking(p,s.time),false);assert.ok(f.z<0);assert.equal(fallPose(f,.3).angle,0);assert.ok(f.z> -f.treeEntryDepth);ticks(s,12);assert.ok(f.stuck);assert.ok(isChoking(p,s.time));assert.ok(f.z+objectHeight(f.kind)>50);const x=p.x;p.input={x:1,y:0};ticks(s,Math.round(EAT.eating.chokeDuration*30)-10);assert.equal(p.x,x);ticks(s,11);assert.ok(f.spit);assert.ok(f.spit.fromZ<0);const a=spitPose(f,f.spit.since+.05),b=spitPose(f,f.spit.since+.15);assert.ok(b.z>a.z);assert.equal(a.x,f.spit.origin.x);ticks(s,Math.ceil(SPIT_DURATION*30)+1);assert.equal(f.spit,undefined);assert.equal(f.stuck,undefined);assert.equal(f.z,0);assert.equal(p.mass,mass);assert.equal(p.stats.trees,0);assert.equal(p.stats.chokes,1);assert.equal(s.food.filter(o=>o.id===f.id).length,1);});

test('full tree canopy fit consumes successfully without choking',()=>{const s=scene(),p=s.players[0];p.mass=500;const f=prop(s,'tree');assert.ok(canopyFits(p,f));ticks(s,70);assert.equal(s.food.includes(f),false);assert.equal(p.stats.trees,1);assert.equal(p.stats.chokes,0);});

for(const map of ['city','nature'])test(`${map} friendly animal follows for 60 seconds, feeds visibly and fully expires`,()=>{const s=scene();s.map=map;const p=s.players[0],kind=map==='city'?'pigeon':'cat';s.encounter={shrine:null,completedBy:p.id,item:{kind:kind==='cat'?'catTree':'scroll',home:{x:0,y:0},x:0,y:0,status:'delivered',ownerId:null},npc:{kind,phase:'friendly',since:0,until:60,targetId:p.id,x:p.x+60,y:p.y,facing:0,origin:{x:0,y:0},destination:{x:0,y:0},nextAction:4,actionAt:0,attacks:0,feeds:0}};p.helper={kind,until:60,used:false,hell:false};assert.equal(QUEST.duration,60);assert.ok(escapeAvailable(s,p));const n=s.encounter.npc;for(let i=0;i<1799;i++){const before={x:p.x,y:p.y};p.x=1500+150*Math.sin(s.time*.3);p.y=1500+150*Math.cos(s.time*.3);p.vx=(p.x-before.x)*30;p.vy=(p.y-before.y)*30;stepGame(s);assert.ok(Math.hypot(n.x-p.x,n.y-p.y)<playerRadius(p,s.time)+230);assert.equal(n.phase,'friendly');}assert.equal(n.feeds,14);assert.equal(p.stats.companionFeeds,14);assert.ok(p.stats.companionSeconds>59);assert.ok(p.foodEaten>=13);ticks(s,2);assert.equal(n.phase,'leaving');assert.equal(p.helper,undefined);assert.equal(escapeAvailable(s,p),false);ticks(s,25);assert.equal(n.phase,'gone');assert.equal(n.until,0);assert.equal(n.targetId,null);assert.equal(n.nextAction,0);});

test('authority owns ability consumption and replayed intents cannot create extra charges',()=>{const s=hell(),p=s.players[0];p.storedJump=p.storedStrike=true;const now=1000000,room={room_code:'TEST',host_id:'a',status:'playing',settings:{map:'city',count:2},players:s.players.map(p=>({id:p.id,name:p.name,lastSeen:now,ready:true})),game_state:s,last_tick:now};applyRoomAction(room,'a','A',{op:'jump',playerId:'b',distance:9999},now,1,'match');assert.equal(p.ability.kind,'jump');assert.equal(s.players[1].ability,undefined);applyRoomAction(room,'a','A',{op:'strike'},now,1,'match');assert.ok(p.storedStrike);applyRoomAction(room,'a','A',{op:'jump'},now,1,'match');assert.equal(p.stats.jumpUses,1);const buffer=new SnapshotBuffer();buffer.push(s,0);const before=JSON.stringify(s);buffer.sample(150,'a',{x:-1,y:0});assert.equal(JSON.stringify(s),before);eliminate(s,p);assert.equal(p.ability,undefined);assert.equal(p.storedStrike,false);});

test('burp particles remain with no text and new controls are translated in every language',()=>{const renderer=readFileSync(new URL('../src/games/eat-it/renderer.ts',import.meta.url),'utf8'),strings=JSON.parse(readFileSync(new URL('../src/i18n/eatItTranslations.json',import.meta.url),'utf8'));assert.match(renderer,/burpAmount/);assert.match(renderer,/c\.arc\(at\.x/);assert.doesNotMatch(renderer,/ui\(['"]burp/i);for(const dict of Object.values(strings)){assert.ok(!Object.keys(dict).some(k=>/^burp/i.test(k)));for(const key of ['Jump','Strike','Jump Ready','Strike Ready','{animal} ♥ {seconds}s','SPACE: Strike · J: Jump in Hell'])assert.ok(dict[key]);}});
test('Hell spawns Strike items frequently on their own timer, capped by hellMaxActive',()=>{const s=hell(),c=EAT.powerups.strike;s.powerups=[];s.hell.nextStrike=s.time;for(let i=0;i<10;i++){s.time+=c.hellInterval;spawnHellStrikes(s);}assert.equal(s.powerups.filter(p=>p.kind==='strike').length,c.hellMaxActive);assert.ok(c.hellInterval<EAT.hell.speedInterval);});
