import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const user='00000000-0000-4000-8000-000000000001';
let handler, calls=[], network=[], jobs=[];
const subscription={endpoint:'https://fcm.googleapis.com/device',keys:{p256dh:'A'.repeat(87),auth:'B'.repeat(22)}};
const query=table=>{const q={then:resolve=>resolve({data:table==='tool_push_deliveries'?[{id:'delivery'}]:[],error:null}),select:()=>q,eq:()=>q,in:()=>q,order:()=>q,limit:()=>q,maybeSingle:async()=>({data:{id:'delivery'},error:null}),update:value=>{calls.push({table,value});return q;},delete:()=>q};return q;};
globalThis.__toolPushMock={db:{auth:{getUser:async token=>({data:{user:token==='valid'?{id:user}:null},error:null})},rpc:async(name,args)=>{calls.push({name,args});return {data:name==='tool_push_claim'?jobs:name==='tool_push_register'?'00000000-0000-4000-8000-000000000003':true,error:null};},from:query},webpush:{generateRequestDetails:(sub,payload,options)=>{calls.push({payload:JSON.parse(payload),options});return {endpoint:sub.endpoint,headers:{},body:new TextEncoder().encode(payload)};}}};
globalThis.Deno={env:{get:name=>({SUPABASE_URL:'https://project.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'service-test',TOOL_PUSH_VAPID_PUBLIC:'public-test',TOOL_PUSH_VAPID_PRIVATE:'private-test',TOOL_PUSH_VAPID_SUBJECT:'mailto:test@pluto.test',TOOL_PUSH_CRON_SECRET:'cron-test',TOOL_PUSH_ALLOWED_ORIGINS:'https://pluto.test'})[name]},serve:h=>{handler=h;}};
let source=readFileSync(new URL('../supabase/functions/tool-push/index.ts',import.meta.url),'utf8');source=source.replace("import { createClient } from 'jsr:@supabase/supabase-js@2';","const createClient=()=>globalThis.__toolPushMock.db;").replace("import webpush from 'npm:web-push@3.6.7';","const webpush=globalThis.__toolPushMock.webpush;").replace("'./model.ts'",JSON.stringify(new URL('../supabase/functions/tool-push/model.ts',import.meta.url).href));
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2023,module:ts.ModuleKind.ESNext}}).outputText;await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const request=(body,token='valid',origin='https://pluto.test')=>handler(new Request('https://project.supabase.co/functions/v1/tool-push',{method:'POST',headers:{Authorization:`Bearer ${token}`,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)}));
test('HTTP actions authenticate identity, restrict origins, validate input and keep service credentials private',async()=>{calls=[];assert.equal((await request({action:'status'},'invalid')).status,401);assert.equal((await request({action:'config'},'valid','https://evil.test')).status,403);assert.equal((await request({action:'dispatch'},'valid')).status,401);assert.equal((await request({action:'subscribe',subscription:{endpoint:'https://127.0.0.1'}})).status,400);assert.equal((await request({action:'reminders',changes:[{id:'bad',at:NaN}]})).status,400);assert.equal((await request({action:'ack',token:'not-uuid',clicked:true})).status,400);
 const response=await request({action:'config'});assert.equal(response.headers.get('Access-Control-Allow-Origin'),'https://pluto.test');assert.deepEqual(await response.json(),{configured:true,publicKey:'public-test'});assert.equal(calls.length,0);
 await request({action:'subscribe',user:'someone-else',subscription,labels:{task:'Task reminder'}});assert.equal(calls[0].args.p_user,user);
});
test('dispatcher handles provider acceptance, transient retry and dead subscription cleanup without downgrading acknowledgement states',async()=>{const oldFetch=globalThis.fetch;try{jobs=[{delivery_id:'delivery',device_id:'device',subscription,labels:{task:'Reminder'},title:'Appointment',ack_token:'00000000-0000-4000-8000-000000000003',test:false,attempts:1}];calls=[];globalThis.fetch=async(url,options)=>{network.push({url,options});return new Response(null,{status:201});};assert.equal((await request({action:'dispatch'},'cron-test')).status,200);assert.equal(calls.find(c=>c.payload).payload.body,'Appointment');assert.equal(calls.find(c=>c.value).value.status,'accepted');assert.equal(network[0].options.redirect,'error');
 calls=[];globalThis.fetch=async()=>new Response(null,{status:503});await request({action:'dispatch'},'cron-test');assert.equal(calls.find(c=>c.value).value.status,'pending');jobs[0].attempts=3;calls=[];await request({action:'dispatch'},'cron-test');assert.equal(calls.find(c=>c.value).value.status,'failed');
 calls=[];globalThis.fetch=async()=>new Response(null,{status:410});await request({action:'dispatch'},'cron-test');assert.equal(calls.some(c=>c.value),false);
}finally{globalThis.fetch=oldFetch;jobs=[];}});

test('birthday changes use the annual scheduler and route notifications to the birthday app',async()=>{
 calls=[];await request({action:'reminders',changes:[{id:'birthday-alex',title:'Alex',at:Date.now(),enabled:true,issuedAt:100,annual:{month:2,day:29,zone:'Europe/Berlin'}}]});
 const call=calls.find(c=>c.name==='tool_push_set_birthday');assert.equal(call.args.p_user,user);assert.equal(call.args.p_day,29);assert.equal('p_at' in call.args,false);
 assert.equal((await request({action:'reminders',changes:[{id:'birthday-bad',title:'Bad',at:Date.now(),enabled:true,annual:{month:2,day:30,zone:'UTC'}}]})).status,400);
 const oldFetch=globalThis.fetch;try{calls=[];jobs=[{delivery_id:'birthday-delivery',device_id:'device',subscription,labels:{birthday:'Birthday reminder'},title:'Alex',ack_token:'00000000-0000-4000-8000-000000000003',test:false,birthday:true,attempts:1}];globalThis.fetch=async()=>new Response(null,{status:201});await request({action:'dispatch'},'cron-test');const payload=calls.find(c=>c.payload).payload;assert.equal(payload.title,'Pluto · Birthday reminder');assert.equal(payload.url,'/tools/birthday-reminders');}finally{globalThis.fetch=oldFetch;jobs=[];}
});
