/**
 * A short everyday greeting per official language (GeoNames language names), shown as the
 * "overheard on the street" clue in Guess the Country. The language itself is never named in that clue.
 */
export const LANGUAGE_PHRASES: Record<string, string> = {
  English: "Good morning! Lovely weather today, isn't it?",
  French: "Bonjour ! Un café, s'il vous plaît.",
  Spanish: "¡Hola! ¿Qué tal? Muchas gracias.",
  Arabic: "مرحبا! كيف حالك؟ شكراً جزيلاً.",
  Russian: "Привет! Как дела? Большое спасибо.",
  Portuguese: "Olá! Tudo bem? Muito obrigado.",
  German: "Guten Morgen! Wie geht es dir? Vielen Dank.",
  Italian: "Buongiorno! Come stai? Grazie mille.",
  Dutch: "Goedemorgen! Hoe gaat het? Dank je wel.",
  Hungarian: "Jó napot! Hogy vagy? Köszönöm szépen.",
  Persian: "سلام! حال شما چطور است؟ خیلی ممنون.",
  Greek: "Καλημέρα! Τι κάνεις; Ευχαριστώ πολύ.",
  Croatian: "Dobro jutro! Kako si? Hvala lijepa.",
  Turkish: "Günaydın! Nasılsın? Çok teşekkür ederim.",
  Serbian: "Добро јутро! Како си? Хвала лепо.",
  "Serbian (Latin)": "Dobro jutro! Kako si? Hvala lepo.",
  Albanian: "Mirëmëngjes! Si je? Faleminderit shumë.",
  Catalan: "Bon dia! Com estàs? Moltes gràcies.",
  Malay: "Selamat pagi! Apa khabar? Terima kasih banyak.",
  Chinese: "早上好！你好吗？非常感谢。",
  Cantonese: "早晨！你好嗎？唔該晒。",
  Slovak: "Dobré ráno! Ako sa máš? Ďakujem pekne.",
  Swedish: "God morgon! Hur mår du? Tack så mycket.",
  Swahili: "Habari za asubuhi! Hujambo? Asante sana.",
  Uzbek: "Xayrli tong! Qalaysiz? Katta rahmat.",
  Romanian: "Bună dimineața! Ce mai faci? Mulțumesc frumos.",
  Korean: "좋은 아침이에요! 잘 지내세요? 정말 감사합니다.",
  Armenian: "Բարի լույս։ Ինչպե՞ս ես։ Շատ շնորհակալություն։",
  Azerbaijani: "Sabahınız xeyir! Necəsiniz? Çox sağ olun.",
  Bangla: "শুভ সকাল! কেমন আছেন? অনেক ধন্যবাদ।",
  Belarusian: "Добрай раніцы! Як справы? Вялікі дзякуй.",
  Bosnian: "Dobro jutro! Kako si? Hvala lijepo.",
  Bulgarian: "Добро утро! Как си? Много благодаря.",
  Khmer: "អរុណសួស្តី! សុខសប្បាយទេ? អរគុណច្រើន។",
  Czech: "Dobré ráno! Jak se máš? Děkuji moc.",
  Danish: "God morgen! Hvordan har du det? Mange tak.",
  Estonian: "Tere hommikust! Kuidas läheb? Suur aitäh.",
  Amharic: "እንደምን አደሩ! ጤና ይስጥልኝ። በጣም አመሰግናለሁ።",
  Finnish: "Hyvää huomenta! Mitä kuuluu? Kiitos paljon.",
  Georgian: "დილა მშვიდობისა! როგორ ხარ? დიდი მადლობა.",
  Icelandic: "Góðan daginn! Hvað segirðu? Takk kærlega.",
  Hindi: "सुप्रभात! आप कैसे हैं? बहुत धन्यवाद।",
  Indonesian: "Selamat pagi! Apa kabar? Terima kasih banyak.",
  Irish: "Dia duit ar maidin! Conas atá tú? Go raibh míle maith agat.",
  Hebrew: "בוקר טוב! מה שלומך? תודה רבה.",
  Japanese: "おはようございます！お元気ですか？どうもありがとう。",
  Kazakh: "Қайырлы таң! Қалыңыз қалай? Көп рахмет.",
  Kyrgyz: "Кутман таң! Кандайсыз? Чоң рахмат.",
  Latvian: "Labrīt! Kā tev iet? Liels paldies.",
  Lithuanian: "Labas rytas! Kaip sekasi? Labai ačiū.",
  Luxembourgish: "Gudde Moien! Wéi geet et? Merci villmools.",
  Maltese: "Bonġu! Kif int? Grazzi ħafna.",
  Mongolian: "Өглөөний мэнд! Сайн байна уу? Их баярлалаа.",
  Afrikaans: "Goeie môre! Hoe gaan dit? Baie dankie.",
  Nepali: "शुभ प्रभात! तपाईंलाई कस्तो छ? धेरै धन्यवाद।",
  "Māori": "Ata mārie! Kei te pēhea koe? Ngā mihi nui.",
  Macedonian: "Добро утро! Како си? Многу благодарам.",
  Norwegian: "God morgen! Hvordan har du det? Tusen takk.",
  "Norwegian Bokmål": "God morgen! Hvordan har du det? Tusen takk.",
  Urdu: "صبح بخیر! آپ کیسے ہیں؟ بہت شکریہ۔",
  Pashto: "سهار مو پخیر! څنګه یاست؟ ډېره مننه.",
  Filipino: "Magandang umaga! Kumusta ka? Maraming salamat.",
  Polish: "Dzień dobry! Jak się masz? Dziękuję bardzo.",
  Kinyarwanda: "Mwaramutse! Amakuru? Murakoze cyane.",
  Rundi: "Mwaramutse! Amakuru? Murakoze cane.",
  Samoan: "Talofa! O a mai oe? Faʻafetai tele lava.",
  Slovenian: "Dobro jutro! Kako si? Najlepša hvala.",
  Somali: "Subax wanaagsan! Iska warran? Aad baad u mahadsan tahay.",
  Zulu: "Sawubona! Unjani? Ngiyabonga kakhulu.",
  Swati: "Sawubona! Unjani? Ngiyabonga kakhulu.",
  Xhosa: "Molo! Unjani? Enkosi kakhulu.",
  Sinhala: "සුභ උදෑසනක්! කොහොමද? බොහොම ස්තූතියි.",
  Tamil: "காலை வணக்கம்! எப்படி இருக்கிறீர்கள்? மிக்க நன்றி.",
  Tajik: "Субҳ ба хайр! Шумо чӣ хел? Раҳмати калон.",
  Thai: "สวัสดีตอนเช้า! สบายดีไหม? ขอบคุณมาก",
  Ukrainian: "Доброго ранку! Як справи? Щиро дякую.",
  Vietnamese: "Chào buổi sáng! Bạn khỏe không? Cảm ơn rất nhiều.",
  "Haitian Creole": "Bonjou! Kijan ou ye? Mèsi anpil.",
  Tongan: "Mālō e lelei! Fēfē hake? Mālō ʻaupito.",
  Fijian: "Bula! Vacava tiko? Vinaka vakalevu.",
  "Tok Pisin": "Moning! Yu stap gut? Tenkyu tru.",
  Bislama: "Gud moning! Olsem wanem? Tangkiu tumas.",
  Tetum: "Bondia! Diʼak ka lae? Obrigadu barak.",
  Latin: "Salve! Quid agis? Gratias tibi ago.",
  Hausa: "Ina kwana! Yaya kake? Na gode sosai.",
  Shona: "Mangwanani! Makadii? Ndatenda zvikuru.",
  Lingala: "Mbote! Sango nini? Matondo mingi.",
  "Southern Sotho": "Dumela! O phela joang? Ke a leboha haholo.",
  Tswana: "Dumela! O tsogile jang? Ke a leboga thata.",
  Akan: "Maakye! Wo ho te sɛn? Meda wo ase paa.",
  Nyanja: "Mwadzuka bwanji! Muli bwanji? Zikomo kwambiri.",
  Malagasy: "Manao ahoana! Salama ve? Misaotra betsaka.",
  Quechua: "Allin pʼunchaw! Imaynalla kashanki? Añaychayki.",
  Welsh: "Bore da! Sut wyt ti? Diolch yn fawr.",
  Turkmen: "Ertiriňiz haýyrly bolsun! Ýagdaýlar nähili? Köp sag boluň.",
};

/** Lingua francas are shared by dozens of countries, so a more local official language makes the better clue. */
const WIDESPREAD = new Set(["English", "French", "Spanish", "Arabic", "Portuguese", "Russian"]);
export function phraseFor(languages: string[]): string | null {
  const local = languages.find((language) => !WIDESPREAD.has(language) && LANGUAGE_PHRASES[language]);
  const fallback = languages.find((language) => LANGUAGE_PHRASES[language]);
  return LANGUAGE_PHRASES[local || fallback || ""] || null;
}
