import { lazy, Suspense, useState } from 'react';
import { Bird, Bug, Fish, Waves, BookOpen, Play, ArrowLeft } from 'lucide-react';
import { SCENARIOS, type ScenarioId, type GameResult, type PlayMode, type BotDifficulty } from '../../../games/natura/naturaData';
import DidYouKnow from '../../../components/natura/DidYouKnow';
import '../../../components/natura/natura3d.css';
const NaturaGame = lazy(() => import('../../../components/natura/NaturaGame'));
const scenarios=[SCENARIOS.find(s=>s.id==='meadow')!,...SCENARIOS.filter(s=>s.id!=='meadow')];
function Icon({id}:{id:ScenarioId}) { return id==='meadow'?<Bird/>:['flyingfish','archerfish'].includes(id)?<Fish/>:['cuttlefish','coconut','spermwhale'].includes(id)?<Waves/>:<Bug/>; }
export default function NaturaMenu() {
  const [mode,setMode]=useState<PlayMode>('ai'),[botDifficulty,setBotDifficulty]=useState<BotDifficulty>('normal'),[selected,setSelected]=useState<ScenarioId>('meadow');
  const [stage,setStage]=useState<'menu'|'game'|'results'>('menu'),[round,setRound]=useState(1),[scores,setScores]=useState<[number,number]>([0,0]);
  const [result,setResult]=useState<GameResult|null>(null),[quiz,setQuiz]=useState<ScenarioId|null>(null);
  const scenario=SCENARIOS.find(s=>s.id===selected)!;
  const finish=(r:GameResult)=>{setResult(r);if(r.winner!==null)setScores(s=>{const next:[number,number]=[...s];next[r.winner!]+=3;return next;});setStage('results');};
  if(stage==='game')return <Suspense fallback={<div className="n3-loading">Opening the habitat…</div>}><NaturaGame key={`${selected}-${round}`} scenario={selected} mode={mode} botDifficulty={botDifficulty} round={round} onComplete={finish} onExit={()=>setStage('menu')}/></Suspense>;
  return <div className="nm-page"><div className="nm-shell"><header className="nm-heading"><div><p className="nm-eyebrow">NATURA / PLAY & DISCOVER</p><h1>The world is your playground.</h1><p>Nine animal adventures. Step into a habitat and learn its ways.</p></div><div className="nm-score"><small>MATCH SCORE</small><b>{scores[0]} <span>:</span> {scores[1]}</b><button onClick={()=>{setScores([0,0]);setRound(1);}}>Reset match</button></div></header>
    {stage==='results'?<section className="nm-results"><p className="nm-eyebrow">{scenario.title} / ROUND {round}</p><h2>{result?.winner===null?'An even match.':`${mode==='ai'?(result?.winner===0?'You win':'Your opponent wins'):`Player ${(result?.winner??0)+1} wins`}.`}</h2><p>{result?.detail}</p><p>{result?.winner===null?'No points for a draw.':'Winner earns 3 Natura points.'}</p><DidYouKnow scenario={selected}/><div className="nm-result-actions"><button className="nm-play" onClick={()=>{setRound(r=>r+1);setStage('game');}}>Play again</button><button onClick={()=>{setRound(r=>r+1);setStage('menu');}}><ArrowLeft size={17}/> Choose habitat</button></div></section>:<>
      <div className="nm-menu-tools"><div><p className="nm-eyebrow">CHOOSE YOUR HABITAT</p><h2>Follow your instincts.</h2></div><div className="nm-mode" aria-label="Players"><button aria-pressed={mode==='ai'} onClick={()=>setMode('ai')}>Solo / vs AI</button><button aria-pressed={mode==='hotseat'} onClick={()=>setMode('hotseat')}>Local two players</button></div></div>
      {mode==='ai'&&<div className="nm-bot-level" role="group" aria-label="Bot difficulty"><span>BOT DIFFICULTY</span>{(['easy','normal','hard'] as const).map(level=><button key={level} type="button" aria-pressed={botDifficulty===level} onClick={()=>setBotDifficulty(level)}>{level}</button>)}<small>For AI rivals; ocean survival stays solo.</small></div>}
      <div className="nm-cards">{scenarios.map((s,i)=><article className={`nm-card nm-${s.id}`} key={s.id}><div className="nm-card-top"><span>{String(i+1).padStart(2,'0')} / 3D HABITAT</span><Icon id={s.id}/></div><small>{s.setting}</small><h2>{s.title}</h2><p>{s.id==='meadow'?'Five dives. One perch. A meadow full of hiding places.':s.id==='flyingfish'?'Three lanes between sea and sky. Read the opening and escape.':s.id==='trapjaw'?'Aim your jaws. Launch across ten forest courses.':s.id==='jumpingspider'?'Leap through three sprawling courses with silk at your side.':s.id==='spermwhale'?'Follow the echoes into the deep. Remember to come up for air.':s.behaviour}</p><div className="nm-card-actions"><button className="nm-play" onClick={()=>{setSelected(s.id);setStage('game');}}><Play size={16}/> Play</button><button onClick={()=>setQuiz(s.id)} aria-label={`Quiz: ${s.title}`}><BookOpen size={16}/> Quiz</button></div></article>)}</div><p className="nm-footnote">Real animal behaviour, playful rules. Find source-linked facts inside every habitat. Quizzes are optional and have their own score.</p>
    </>}
  </div>{quiz&&<Quiz key={quiz} id={quiz} close={()=>setQuiz(null)}/>}</div>;
}
function Quiz({id,close}:{id:ScenarioId;close:()=>void}) {
  const scenario=SCENARIOS.find(s=>s.id===id)!;
  const [index,setIndex]=useState(0),[answer,setAnswer]=useState<number|null>(null),[score,setScore]=useState(0);
  const done=index>=scenario.questions.length,q=scenario.questions[index];
  return <div className="nm-modal"><section className="nm-quiz" role="dialog" aria-modal="true" aria-label={`${scenario.title} quiz`}><button className="nm-close" onClick={close}>Close quiz</button><p className="nm-eyebrow">{scenario.title} / OPTIONAL QUIZ</p>{done?<><h2>{score} / {scenario.questions.length}</h2><p>Field notes complete. Your game score stays separate.</p><DidYouKnow scenario={id}/><button className="nm-play" onClick={close}>Back to habitats</button></>:<><small>Question {index+1} / {scenario.questions.length} · Score {score}</small><h2>{q.text}</h2><div className="nm-answers">{q.answers.map((a,i)=><button key={a} disabled={answer!==null} className={answer!==null&&i===q.correct?'correct':answer===i?'incorrect':''} onClick={()=>{setAnswer(i);if(i===q.correct)setScore(s=>s+1);}}>{a}</button>)}</div>{answer!==null&&<div role="status"><p><b>{answer===q.correct?'Correct.':'Not quite.'}</b> {q.explanation}</p><button className="nm-play" onClick={()=>{setIndex(n=>n+1);setAnswer(null);}}>{index===scenario.questions.length-1?'See quiz score':'Next question'}</button></div>}</>}</section></div>;
}
