import { Bird, Castle, Cat, ChessKing, ChessKnight, ChessQueen, Compass, Crown, Dice5, Dog, Flame, Gem, Globe2, Grid3X3, Hexagon, Map, Mountain, Orbit, Shield, Snowflake, Spade, Swords, Trees, Waves, Zap, type LucideIcon } from "lucide-react";

export const groupAvatars: { id: string; name: string; Icon: LucideIcon; colors: string; image?: string }[] = [
  { id: "chess-king", name: "Chess King", Icon: ChessKing, colors: "from-amber-500 to-orange-900", image: "/group-avatars/chess-king.png" },
  { id: "chess-knight", name: "Chess Knight", Icon: ChessKnight, colors: "from-indigo-500 to-slate-900", image: "/group-avatars/chess-knight.png" },
  { id: "chess-queen", name: "Chess Queen", Icon: ChessQueen, colors: "from-fuchsia-500 to-purple-950" },
  { id: "chess-board", name: "Chess Board", Icon: Grid3X3, colors: "from-slate-500 to-slate-950" },
  { id: "cards", name: "Playing Cards", Icon: Spade, colors: "from-red-500 to-rose-950", image: "/group-avatars/cards.png" },
  { id: "card-king", name: "Card King", Icon: Crown, colors: "from-red-400 to-amber-900" },
  { id: "dice", name: "Dice", Icon: Dice5, colors: "from-cyan-500 to-indigo-950" },
  { id: "castle", name: "Castle", Icon: Castle, colors: "from-stone-400 to-stone-900" },
  { id: "shield", name: "Shield", Icon: Shield, colors: "from-blue-500 to-indigo-950" },
  { id: "dragon", name: "Dragon", Icon: Flame, colors: "from-emerald-400 to-green-950", image: "/group-avatars/dragon.png" },
  { id: "forest", name: "Forest", Icon: Trees, colors: "from-lime-400 to-emerald-950", image: "/group-avatars/forest.png" },
  { id: "wolf", name: "Wolf", Icon: Dog, colors: "from-slate-400 to-indigo-950" },
  { id: "eagle", name: "Eagle", Icon: Bird, colors: "from-sky-400 to-blue-950" },
  { id: "fox", name: "Fox", Icon: Cat, colors: "from-orange-400 to-red-950" },
  { id: "ocean", name: "Ocean", Icon: Waves, colors: "from-cyan-400 to-blue-950" },
  { id: "mountain", name: "Mountain", Icon: Mountain, colors: "from-slate-300 to-blue-950" },
  { id: "globe", name: "Globe", Icon: Globe2, colors: "from-teal-400 to-blue-950" },
  { id: "compass", name: "Compass", Icon: Compass, colors: "from-amber-300 to-sky-950" },
  { id: "arena", name: "Arena", Icon: Swords, colors: "from-rose-500 to-slate-950" },
  { id: "crown", name: "Crown", Icon: Crown, colors: "from-yellow-400 to-amber-950" },
  { id: "galaxy", name: "Galaxy", Icon: Orbit, colors: "from-violet-400 to-indigo-950" },
  { id: "planet", name: "Planet", Icon: Orbit, colors: "from-pink-400 to-violet-950" },
  { id: "fire", name: "Fire", Icon: Flame, colors: "from-yellow-400 to-red-950" },
  { id: "ice", name: "Ice", Icon: Snowflake, colors: "from-cyan-200 to-blue-900" },
  { id: "lightning", name: "Lightning", Icon: Zap, colors: "from-yellow-300 to-violet-950" },
  { id: "treasure", name: "Treasure", Icon: Gem, colors: "from-amber-400 to-yellow-950" },
  { id: "map", name: "Strategy Map", Icon: Map, colors: "from-emerald-300 to-teal-950" },
  { id: "geometry", name: "Geometry", Icon: Hexagon, colors: "from-violet-400 to-rose-950" },
];
