export const pushHosts = ['fcm.googleapis.com', 'updates.push.services.mozilla.com', 'push.services.mozilla.com', 'web.push.apple.com', 'notify.windows.com'];
export function validPushEndpoint(value: unknown): value is string { if (typeof value !== 'string' || value.length > 2048) return false; try { const u = new URL(value); return u.protocol === 'https:' && !u.username && !u.password && !u.hash && (!u.port || u.port === '443') && pushHosts.some(host => u.hostname === host || u.hostname.endsWith('.' + host)); } catch { return false; } }
export function validSubscription(value: unknown): value is { endpoint: string; keys: { p256dh: string; auth: string } } { if (!value || typeof value !== 'object') return false; const v = value as Record<string, unknown>, keys = v.keys as Record<string, unknown> | undefined; return validPushEndpoint(v.endpoint) && !!keys && typeof keys.p256dh === 'string' && /^[A-Za-z0-9_-]{87}$/.test(keys.p256dh) && typeof keys.auth === 'string' && /^[A-Za-z0-9_-]{22}$/.test(keys.auth); }
export function validAnnualReminder(value: unknown): value is { month: number; day: number; zone: string } {
 if (!value || typeof value !== 'object') return false;
 const a=value as Record<string,unknown>;
 if (typeof a.month!=='number' || !Number.isInteger(a.month) || a.month<1 || a.month>12 || typeof a.day!=='number' || !Number.isInteger(a.day) || a.day<1 || a.day>new Date(Date.UTC(2000,a.month,0)).getUTCDate() || typeof a.zone!=='string' || a.zone.length>100) return false;
 try { new Intl.DateTimeFormat('en',{timeZone:a.zone}); return true; } catch { return false; }
}
export const validReminder = (v: unknown): v is { id: string; title: string; at: number; enabled: boolean; issuedAt?: number; annual?: { month: number; day: number; zone: string } } => { if (!v || typeof v !== 'object') return false; const r = v as Record<string, unknown>; return typeof r.id === 'string' && /^[a-zA-Z0-9-]{1,80}$/.test(r.id) && typeof r.title === 'string' && !!r.title.trim() && r.title.length <= 100 && typeof r.at === 'number' && Number.isSafeInteger(r.at) && r.at >= 946684800000 && r.at <= 4102444800000 && typeof r.enabled === 'boolean' && (r.issuedAt === undefined || typeof r.issuedAt === 'number' && Number.isSafeInteger(r.issuedAt) && r.issuedAt >= 0 && r.issuedAt <= 4102444800000) && (r.annual === undefined || r.id.startsWith('birthday-') && validAnnualReminder(r.annual)); };
export const terminalPushFailure = (status: number) => status === 404 || status === 410;
