import SubscriptionTracker from './SubscriptionTracker';
import useMoney from '@/hooks/useToolMoney';
import { localToday, downloadCsv } from '@/data/lifeToolsBrowser';
import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useLifeTools } from '@/hooks/useLifeTools';
import { budgetMonth, subscriptionBudgetEntries, moneyCents, csv, type Currency, type BudgetEntry } from '@/data/lifeTools';
import { Field, CurrencyField, StorageNote, DeleteAction } from './LifeToolParts';
import ToolTabs from './ToolTabs';
import { ui } from '@/i18n/ui';
function Tracker() {
 const { state, save, remove, sessionOnly, loading } = useLifeTools(), money = useMoney();
 const [params, setParams] = useSearchParams(), tab = params.get('section') === 'subscriptions' ? 'Subscriptions' : 'Budget';
 const [month, setMonth] = useState(() => localToday().slice(0, 7)), [currency, setCurrency] = useState<Currency>('EUR'), [title, setTitle] = useState(''), [category, setCategory] = useState(''), [date, setDate] = useState(localToday), [amount, setAmount] = useState(''), [kind, setKind] = useState<BudgetEntry['kind']>('expense'), [recurring, setRecurring] = useState(false), [editing, setEditing] = useState<string | null>(null), [limit, setLimit] = useState(''), [message, setMessage] = useState('');
 const report = budgetMonth([...state.entries, ...subscriptionBudgetEntries(state.subscriptions, month)], month, currency), budget = state.limits.find(l => l.month === month && l.currency === currency), allEntries = state.entries.filter(e => e.currency === currency).sort((a, b) => b.date.localeCompare(a.date));
 const reset = () => { setEditing(null); setTitle(''); setCategory(''); setAmount(''); setRecurring(false); };
 const edit = (entry: BudgetEntry) => { setEditing(entry.id); setTitle(entry.title); setCategory(entry.category); setDate(entry.date); setAmount((entry.amount / 100).toFixed(2)); setKind(entry.kind); setRecurring(entry.recurring); };
 return <section className="pt-workbench" aria-label={ui('Budget Tracker')}><p className="lt-notice" role="status">{ui('Subscription tracking is now part of the Budget Tracker. Your existing subscriptions are integrated here.')}</p><ToolTabs tabs={['Budget','Subscriptions'] as const} value={tab} onChange={value => { const next = new URLSearchParams(params); next.set('section',value.toLowerCase()); setParams(next); }} label="Budget sections" panelId="budget-panel" /><div id="budget-panel" role="tabpanel" aria-label={ui(tab)} tabIndex={0}>{tab === 'Subscriptions' ? <SubscriptionTracker /> : <><div className="pt-inputs"><Field label="Month"><input type="month" min="2000-01" max="2099-12" value={month} onChange={e => setMonth(e.target.value)} /></Field><CurrencyField value={currency} onChange={setCurrency} /></div><div className="life-summary"><div><small>{ui('Income')}</small><strong>{money(report.income, currency)}</strong></div><div><small>{ui('Expenses')}</small><strong>{money(report.expense, currency)}</strong></div><div><small>{ui('Income minus expenses')}</small><strong>{money(report.remaining, currency)}</strong></div></div>
 <div className="life-workspace"><div><h2>{ui(editing ? 'Edit entry' : 'Add entry')}</h2><form className="life-form" onSubmit={e => { e.preventDefault(); const cents = moneyCents(amount), entry: BudgetEntry = { id: editing ?? crypto.randomUUID(), title: title.trim(), category: category.trim(), date, amount: cents ?? NaN, currency, kind, recurring }; const success = save('entries', entry); if (success) reset(); setMessage(success ? 'Saved.' : 'Could not save. Check the inputs or storage limits.'); }}><div className="pt-inputs"><Field label="Entry name"><input required maxLength={100} value={title} onChange={e => setTitle(e.target.value)} /></Field><Field label="Category"><input required maxLength={50} value={category} onChange={e => setCategory(e.target.value)} /></Field><Field label="Date"><input type="date" required min="2000-01-01" max="2099-12-31" value={date} onChange={e => setDate(e.target.value)} /></Field><Field label="Amount"><input inputMode="decimal" required maxLength={11} value={amount} onChange={e => setAmount(e.target.value)} /></Field><Field label="Type"><select value={kind} onChange={e => setKind(e.target.value as BudgetEntry['kind'])}><option value="expense">{ui('Expense')}</option><option value="income">{ui('Income')}</option></select></Field></div><label className="life-check"><input type="checkbox" checked={recurring} onChange={e => setRecurring(e.target.checked)} />{ui('Repeat monthly from this date')}</label><div className="pt-actions"><button className="lt-button primary" disabled={loading}>{ui(editing ? 'Save changes' : 'Add entry')}</button>{editing && <button className="lt-button" type="button" onClick={reset}>{ui('Cancel')}</button>}</div></form><p role="status">{ui(message)}</p><h2>{ui('Entries for this month')}</h2>{!report.rows.length && <p>{ui('No entries for this month and currency.')}</p>}<ul className="life-list life-ledger-scroll">{report.rows.sort((a,b) => a.date.localeCompare(b.date)).map(entry => <li className="life-row" key={entry.id}><div><strong>{entry.title}</strong><p>{entry.date} · {ui(entry.category)} · {ui(entry.kind === 'income' ? 'Income' : 'Expense')}{entry.recurring && ` · ${ui('Monthly plan')}`}</p></div><strong>{money(entry.amount,currency)}</strong></li>)}</ul><button className="lt-button" type="button" onClick={() => downloadCsv(csv([[ui('Date'),ui('Name'),ui('Category'),ui('Type'),ui('Amount'),ui('Currency'),ui('Monthly plan')],...report.rows.map(e => [e.date,e.title,e.category,ui(e.kind === 'income' ? 'Income' : 'Expense'),(e.amount/100).toFixed(2),e.currency,e.recurring ? ui('Yes') : ui('No')])]),`budget-${month}-${currency}.csv`)}>{ui('Export CSV')}</button></div>
 <aside><h2>{ui('Monthly spending limit')}</h2><form className="life-form" onSubmit={e => { e.preventDefault(); const cents=moneyCents(limit); setMessage(save('limits',{id:`${month}-${currency}`,month,currency,amount:cents ?? NaN}) ? 'Saved.' : 'Could not save. Check the inputs or storage limits.'); }}><Field label="Monthly spending limit"><input inputMode="decimal" required maxLength={11} value={limit} onChange={e => setLimit(e.target.value)} /></Field><div className="pt-actions"><button className="lt-button" disabled={loading}>{ui('Save spending limit')}</button>{budget && <DeleteAction name={ui('Monthly spending limit')} onDelete={() => remove('limits',budget.id)} />}</div></form>{budget && <div className="pt-result"><p>{money(budget.amount,currency)}</p><p>{ui(report.expense > budget.amount ? 'Over budget' : 'Budget remaining')} · {money(Math.abs(budget.amount-report.expense),currency)}</p><div className="pt-percent-bar" aria-hidden="true"><span style={{width:`${budget.amount ? Math.min(100,report.expense/budget.amount*100) : report.expense ? 100 : 0}%`}} /></div></div>}<h2>{ui('Spending by category')}</h2>{Object.entries(report.categories).map(([name,amount]) => <div className="pt-result" key={name}><p>{ui(name)} · {money(amount,currency)}</p><div className="pt-percent-bar" aria-hidden="true"><span style={{width:`${report.expense ? amount/report.expense*100 : 0}%`}} /></div></div>)}<p className="lt-storage-note">{ui('Monthly plans and active subscription bills are included. Subscriptions remain in their original records and are counted once per billing cycle.')}</p></aside></div>
 <details><summary>{ui('Manage saved entries')}</summary><p>{ui('Editing or deleting a monthly plan changes every month generated from it.')}</p><ul className="life-list">{allEntries.map(entry => <li className="life-row" key={entry.id}><div><strong>{entry.title}</strong><p>{entry.date} · {entry.category} · {money(entry.amount,entry.currency)}</p></div><button className="lt-text-link" type="button" onClick={() => edit(entry)}>{ui('Edit')}</button><DeleteAction name={entry.title} onDelete={() => { remove('entries',entry.id); if (editing === entry.id) reset(); }} /></li>)}</ul></details><StorageNote sessionOnly={sessionOnly} /></>}</div></section>;
}
export default function BudgetTracker() { const { account } = useLifeTools(); return <Tracker key={account} />; }
