import { useState } from 'react';
import { useLifeTools } from '@/hooks/useLifeTools';
import { localToday, downloadCsv } from '@/data/lifeToolsBrowser';
import { csv } from '@/data/lifeTools';
import { mealNames, portionNumber, foodCalories, totalCalories, calorieHistory, type FoodEntry, type FoodPortion } from '@/data/calorieTools';
import { ui } from '@/i18n/ui';
import { Field, StorageNote, DeleteAction } from './LifeToolParts';
function Tracker() {
  const { state, save, remove, update, loading, sessionOnly } = useLifeTools();
  const [date, setDate] = useState(localToday), [meal, setMeal] = useState<FoodEntry['meal']>('Breakfast'), [name, setName] = useState(''), [quantity, setQuantity] = useState('100'), [energy, setEnergy] = useState(''), [unit, setUnit] = useState<FoodPortion['unit']>('g'), [editing, setEditing] = useState<string | null>(null), [message, setMessage] = useState(''), [templateName, setTemplateName] = useState(''), [multiplier, setMultiplier] = useState('1');
  const foods = state.foodEntries.filter(f => f.date === date), history = calorieHistory(state.foodEntries);
  const reset = () => { setEditing(null); setName(''); setEnergy(''); };
  const report = (success: boolean) => setMessage(success ? 'Saved.' : 'Could not save. Check the inputs or storage limits.');
  return <section className="pt-workbench" aria-label={ui('Calorie Tracker')}><p className="lt-notice">{ui('Enter energy from a food label or your own source. Totals are estimates based on your entries; no calorie target is prescribed.')}</p><Field label="Date"><input type="date" min="2000-01-01" max="2099-12-31" required value={date} onChange={e => { setDate(e.target.value); reset(); }} /></Field><div className="life-summary"><div><small>{ui('Daily energy')}</small><strong>{totalCalories(foods)} kcal</strong></div><div><small>{ui('Food entries')}</small><strong>{foods.length}</strong></div><div><small>{ui('Days logged')}</small><strong>{history.length}</strong></div></div>
  <form className="life-form" onSubmit={e => { e.preventDefault(); const success = save('foodEntries', { id: editing ?? crypto.randomUUID(), name: name.trim(), date, meal, quantity: portionNumber(quantity) ?? NaN, energy: portionNumber(energy) ?? NaN, unit }); report(success); if (success) reset(); }}><div className="pt-inputs"><Field label="Food name"><input required maxLength={100} value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Meal"><select value={meal} onChange={e => setMeal(e.target.value as FoodEntry['meal'])}>{mealNames.map(m => <option key={m} value={m}>{ui(m)}</option>)}</select></Field><Field label="Portion unit"><select value={unit} onChange={e => setUnit(e.target.value as FoodPortion['unit'])}><option value="g">{ui('Grams')}</option><option value="serving">{ui('Servings')}</option></select></Field><Field label="Portion quantity"><input required inputMode="decimal" maxLength={9} value={quantity} onChange={e => setQuantity(e.target.value)} /></Field><Field label={unit === 'g' ? 'kcal per 100 g' : 'kcal per serving'}><input required inputMode="decimal" maxLength={9} value={energy} onChange={e => setEnergy(e.target.value)} /></Field></div><div className="pt-actions"><button type="submit" disabled={loading} className="lt-button primary">{ui(editing ? 'Save changes' : 'Add food')}</button>{editing && <button type="button" className="lt-button" onClick={reset}>{ui('Cancel')}</button>}</div></form><p role="status">{ui(message)}</p>
  {mealNames.map(m => <div key={m}><h2>{ui(m)} · {totalCalories(foods.filter(f => f.meal === m))} kcal</h2><ul className="life-list">{foods.filter(f => f.meal === m).map(f => <li key={f.id} className="life-row"><div><strong>{f.name}</strong><p>{f.quantity} {ui(f.unit === 'g' ? 'Grams' : 'Servings')} · {foodCalories(f)} kcal</p><small>{f.energy} {ui(f.unit === 'g' ? 'kcal per 100 g' : 'kcal per serving')}</small></div><div className="pt-actions"><button type="button" className="lt-text-link" onClick={() => { setEditing(f.id); setName(f.name); setMeal(f.meal); setQuantity(String(f.quantity)); setEnergy(String(f.energy)); setUnit(f.unit); }}>{ui('Edit')}</button><DeleteAction name={f.name} onDelete={() => { remove('foodEntries', f.id); if (editing === f.id) reset(); }} /></div></li>)}</ul></div>)}
  {!foods.length && <p>{ui('No foods logged for this date.')}</p>}
  <h2>{ui('Reusable meals')}</h2><p>{ui('Save the foods in the selected meal as a template. Logging a template copies its portions, so later edits do not change history.')}</p><form className="life-form" onSubmit={e => { e.preventDefault(); report(save('savedMeals', { id: crypto.randomUUID(), name: templateName.trim(), foods: foods.filter(f => f.meal === meal).map(({ name, quantity, energy, unit }) => ({ name, quantity, energy, unit })) })); }}><div className="pt-inputs"><Field label="Meal template name"><input required maxLength={100} value={templateName} onChange={e => setTemplateName(e.target.value)} /></Field></div><button className="lt-button" disabled={loading || !foods.some(f => f.meal === meal)}>{ui('Save selected meal')}</button></form>
  <Field label="Portion multiplier"><input required inputMode="decimal" maxLength={6} value={multiplier} onChange={e => setMultiplier(e.target.value)} /></Field><ul className="life-list">{state.savedMeals.map(t => <li className="life-row" key={t.id}><div><strong>{t.name}</strong><p>{totalCalories(t.foods)} kcal · {t.foods.map(f => f.name).join(', ')}</p></div><div className="pt-actions"><button type="button" className="lt-button" disabled={loading} onClick={() => { const factor = portionNumber(multiplier); if (!factor || factor > 100) { report(false); return; } report(update(s => ({ ...s, foodEntries: [...s.foodEntries, ...t.foods.map(f => ({ ...f, quantity: Math.round(f.quantity * factor * 100) / 100, id: crypto.randomUUID(), date, meal }))] }))); }}>{ui('Log meal')}</button><DeleteAction name={t.name} onDelete={() => remove('savedMeals', t.id)} /></div></li>)}</ul>
  <h2>{ui('Daily history')}</h2><ul className="life-list">{history.slice(0, 90).map(h => <li key={h.date} className="life-row"><button type="button" className="lt-text-link" onClick={() => { setDate(h.date); reset(); }}>{h.date}</button><span>{h.calories} kcal · {h.count} {ui('Food entries')}</span></li>)}</ul><button className="lt-button" type="button" onClick={() => downloadCsv(csv([[ui('Date'), ui('Meal'), ui('Food name'), ui('Portion quantity'), ui('Portion unit'), ui('Label energy'), 'kcal'], ...state.foodEntries.map(f => [f.date, ui(f.meal), f.name, f.quantity, ui(f.unit === 'g' ? 'Grams' : 'Servings'), f.energy, foodCalories(f)])]), 'calorie-history.csv')}>{ui('Export CSV')}</button><StorageNote sessionOnly={sessionOnly} /></section>;
}
export default function CalorieTracker() { const { account } = useLifeTools(); return <Tracker key={account} />; }
