import RecipeShoppingAction from './RecipeShoppingAction';
import { useSearchParams } from 'react-router-dom';
import { useMemo, useRef, useState } from 'react';
import { Camera, Check, ChevronLeft, ChevronRight, Clipboard, Download, Plus, Share2, Sparkles, Trash2, Utensils } from 'lucide-react';
import { useLifeTools } from '@/hooks/useLifeTools';
import { localToday, downloadCsv } from '@/data/lifeToolsBrowser';
import { csv } from '@/data/lifeTools';
import { foodCalories, mealNames, portionNumber, totalCalories, type FoodEntry, type FoodPortion, type NutritionFood, type NutritionRecipe } from '@/data/calorieTools';
import { supabase } from '@/lib/supabase';
import { ui } from '@/i18n/ui';
import { Field, StorageNote } from './LifeToolParts';
import './calorieTracker.css';

type Tab = 'today' | 'foods' | 'insights' | 'recipes';
type RemoteRecipe = { id: string; name: string; servings: number; foods: FoodPortion[]; owner_id: string };
type Draft = { name: string; meal: FoodEntry['meal']; quantity: string; energy: string; unit: FoodPortion['unit']; protein: string; carbs: string; fat: string; fiber: string };
const blankDraft = (): Draft => ({ name: '', meal: 'Breakfast', quantity: '100', energy: '', unit: 'g', protein: '', carbs: '', fat: '', fiber: '' });
const standardFoods: NutritionFood[] = [
  { id: 'standard-oats', name: 'Haferflocken', quantity: 100, energy: 372, unit: 'g', nutrients: { protein: 13, carbs: 59, fat: 7, fiber: 10 } },
  { id: 'standard-chicken', name: 'Hähnchenbrust', quantity: 100, energy: 110, unit: 'g', nutrients: { protein: 23, carbs: 0, fat: 1.5 } },
  { id: 'standard-salmon', name: 'Lachs', quantity: 100, energy: 208, unit: 'g', nutrients: { protein: 20, carbs: 0, fat: 13 } },
  { id: 'standard-pasta', name: 'Vollkornnudeln', quantity: 100, energy: 348, unit: 'g', nutrients: { protein: 13, carbs: 62, fat: 2, fiber: 8 } },
  { id: 'standard-apple', name: 'Apfel', quantity: 100, energy: 52, unit: 'g', nutrients: { protein: .3, carbs: 14, fat: .2, fiber: 2.4 } },
  { id: 'standard-banana', name: 'Banane', quantity: 100, energy: 89, unit: 'g', nutrients: { protein: 1.1, carbs: 23, fat: .3, fiber: 2.6 } },
  { id: 'standard-avocado', name: 'Avocado', quantity: 100, energy: 160, unit: 'g', nutrients: { protein: 2, carbs: 9, fat: 15, fiber: 7 } },
  { id: 'standard-quark', name: 'Magerquark', quantity: 100, energy: 67, unit: 'g', nutrients: { protein: 12, carbs: 4, fat: .2 } },
];
const mealIcons: Record<FoodEntry['meal'], string> = { Breakfast: '☀️', Lunch: '🥗', Dinner: '🍲', Snack: '🍎' };
const nutrientsFor = (food: FoodPortion) => { const factor = food.unit === 'g' ? food.quantity / 100 : food.quantity, n = food.nutrients ?? {}; return { protein: (n.protein ?? 0) * factor, carbs: (n.carbs ?? 0) * factor, fat: (n.fat ?? 0) * factor, fiber: (n.fiber ?? 0) * factor }; };
const intake = (foods: FoodPortion[]) => foods.reduce((total, food) => { const n = nutrientsFor(food); return { kcal: total.kcal + foodCalories(food), protein: total.protein + n.protein, carbs: total.carbs + n.carbs, fat: total.fat + n.fat, fiber: total.fiber + n.fiber }; }, { kcal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 });
const grams = (value: number) => `${Math.round(value)} g`;
const text = (value: string) => value.trim().slice(0, 100);

function Tracker() {
  const [params] = useSearchParams();
  const { state, save, remove, update, loading, sessionOnly, account } = useLifeTools();
  const [tab, setTab] = useState<Tab>(params.get('section') === 'recipes' ? 'recipes' : 'today'), [date, setDate] = useState(localToday), [draft, setDraft] = useState<Draft>(blankDraft), [editing, setEditing] = useState<string | null>(null), [message, setMessage] = useState(''), [foodSearch, setFoodSearch] = useState(''), [recipeName, setRecipeName] = useState(''), [recipeServings, setRecipeServings] = useState('1'), [shareTo, setShareTo] = useState<Record<string, string>>({}), [remoteRecipes, setRemoteRecipes] = useState<RemoteRecipe[]>([]), [scanStatus, setScanStatus] = useState('');
  const photoInput = useRef<HTMLInputElement>(null), foods = state.foodEntries.filter(item => item.date === date), day = useMemo(() => intake(foods), [foods]), goal = state.nutritionSettings.calorieGoal, remaining = goal === null ? null : Math.max(0, goal - day.kcal);
  const allFoods = useMemo(() => [...standardFoods, ...state.nutritionFoods].filter(item => item.name.toLowerCase().includes(foodSearch.trim().toLowerCase())), [foodSearch, state.nutritionFoods]);
  const recipeCards = useMemo(() => [...state.nutritionRecipes.map(recipe => ({ ...recipe, source: 'local' as const })), ...state.savedMeals.filter(meal => !state.nutritionRecipes.some(recipe => recipe.id === meal.id)).map(meal => ({ ...meal, servings: 1, source: 'local' as const })), ...remoteRecipes.map(recipe => ({ ...recipe, source: 'shared' as const }))], [state.nutritionRecipes, state.savedMeals, remoteRecipes]);
  const set = <K extends keyof Draft>(key: K, value: Draft[K]) => setDraft(current => ({ ...current, [key]: value }));
  const moveDay = (amount: number) => { const value = new Date(`${date}T12:00:00`); value.setDate(value.getDate() + amount); setDate(value.toISOString().slice(0, 10)); };
  const addEntry = (event: React.FormEvent) => { event.preventDefault(); const quantity = portionNumber(draft.quantity), energy = portionNumber(draft.energy), macros = [draft.protein, draft.carbs, draft.fat, draft.fiber].map(value => value ? portionNumber(value) : 0); if (!text(draft.name) || !quantity || energy === null || macros.some(value => value === null)) { setMessage('Bitte Lebensmittel, Menge und Nährwerte prüfen.'); return; } const entry: FoodEntry = { id: editing ?? crypto.randomUUID(), name: text(draft.name), date, meal: draft.meal, quantity, energy, unit: draft.unit, nutrients: { protein: macros[0] ?? 0, carbs: macros[1] ?? 0, fat: macros[2] ?? 0, fiber: macros[3] ?? 0 } }; if (save('foodEntries', entry)) { setMessage(editing ? 'Eintrag aktualisiert.' : 'Zum Tagebuch hinzugefügt.'); setDraft(blankDraft()); setEditing(null); } else setMessage('Der Eintrag konnte nicht gespeichert werden.'); };
  const editEntry = (entry: FoodEntry) => { setDraft({ name: entry.name, meal: entry.meal, quantity: String(entry.quantity), energy: String(entry.energy), unit: entry.unit, protein: String(entry.nutrients?.protein ?? ''), carbs: String(entry.nutrients?.carbs ?? ''), fat: String(entry.nutrients?.fat ?? ''), fiber: String(entry.nutrients?.fiber ?? '') }); setEditing(entry.id); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const chooseFood = (food: NutritionFood) => { setDraft({ name: food.name, meal: draft.meal, quantity: String(food.quantity), energy: String(food.energy), unit: food.unit, protein: String(food.nutrients?.protein ?? ''), carbs: String(food.nutrients?.carbs ?? ''), fat: String(food.nutrients?.fat ?? ''), fiber: String(food.nutrients?.fiber ?? '') }); setTab('today'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const rememberFood = () => { const quantity = portionNumber(draft.quantity), energy = portionNumber(draft.energy); if (!text(draft.name) || !quantity || energy === null) { setMessage('Erst einen vollständigen Eintrag ausfüllen.'); return; } const food: NutritionFood = { id: crypto.randomUUID(), name: text(draft.name), quantity, energy, unit: draft.unit, nutrients: { protein: portionNumber(draft.protein) ?? 0, carbs: portionNumber(draft.carbs) ?? 0, fat: portionNumber(draft.fat) ?? 0, fiber: portionNumber(draft.fiber) ?? 0 } }; setMessage(save('nutritionFoods', food) ? 'In deiner Lebensmitteldatenbank gespeichert.' : 'Lebensmittel konnte nicht gespeichert werden.'); };
  const saveRecipe = () => { const servings = portionNumber(recipeServings); if (!text(recipeName) || !servings || !foods.length) { setMessage('Rezeptname, Portionen und mindestens ein heutiger Eintrag sind nötig.'); return; } const recipe: NutritionRecipe = { id: crypto.randomUUID(), name: text(recipeName), servings, foods: foods.map(({ name, quantity, energy, unit, nutrients }) => ({ name, quantity, energy, unit, nutrients })) }; if (save('nutritionRecipes', recipe) && save('savedMeals', { id: recipe.id, name: recipe.name, foods: recipe.foods })) { setRecipeName(''); setRecipeServings('1'); setMessage('Rezept im Rezeptbuch gespeichert.'); } else setMessage('Rezept konnte nicht gespeichert werden.'); };
  const logRecipe = (recipe: NutritionRecipe) => { const portions = Math.max(1, recipe.servings), ok = update(current => ({ ...current, foodEntries: [...current.foodEntries, ...recipe.foods.map(food => ({ ...food, id: crypto.randomUUID(), date, meal: draft.meal, quantity: Math.round(food.quantity / portions * 100) / 100 }))] })); setMessage(ok ? `${recipe.name} wurde eingetragen.` : 'Rezept konnte nicht eingetragen werden.'); setTab('today'); };
  const loadSharedRecipes = async () => { if (account === 'guest') return; const { data, error } = await supabase.from('nutrition_recipes').select('id,name,servings,foods,owner_id,created_at').order('created_at', { ascending: false }).limit(100); if (!error) setRemoteRecipes((data ?? []).filter(recipe => recipe.owner_id !== account) as RemoteRecipe[]); };
  const shareRecipe = async (recipe: NutritionRecipe) => { const username = text(shareTo[recipe.id] ?? ''); if (account === 'guest') { setMessage('Melde dich an, um Rezepte mit Freundinnen und Freunden zu teilen.'); return; } if (!username) { setMessage('Gib den Pluto-Nutzernamen deiner Freundschaft ein.'); return; } const { error: saveError } = await supabase.from('nutrition_recipes').upsert({ id: recipe.id, owner_id: account, name: recipe.name, servings: recipe.servings, foods: recipe.foods }, { onConflict: 'id' }); if (saveError) { setMessage('Online-Rezeptbuch ist noch nicht eingerichtet. Bitte die Datenbankmigration anwenden.'); return; } const { error } = await supabase.rpc('nutrition_share_recipe', { p_recipe: recipe.id, p_username: username }); setMessage(error ? 'Freigabe nicht möglich: Bitte Freundschaft und Nutzername prüfen.' : `Rezept für ${username} freigegeben.`); if (!error) setShareTo(current => ({ ...current, [recipe.id]: '' })); };
  const scanPhoto = async (file: File) => { if (!file.type.startsWith('image/') || file.size > 3_000_000) { setScanStatus('Bitte ein Bild bis 3 MB auswählen.'); return; } setScanStatus('Etikett wird gelesen …'); try { const image = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); const { data, error } = await supabase.functions.invoke('nutrition-scan', { body: { image } }); if (error || !data?.food) throw Error('Unavailable'); const found = data.food; setDraft(current => ({ ...current, name: typeof found.name === 'string' ? found.name : current.name, energy: typeof found.energy === 'number' ? String(found.energy) : current.energy, protein: typeof found.protein === 'number' ? String(found.protein) : current.protein, carbs: typeof found.carbs === 'number' ? String(found.carbs) : current.carbs, fat: typeof found.fat === 'number' ? String(found.fat) : current.fat, fiber: typeof found.fiber === 'number' ? String(found.fiber) : current.fiber })); setScanStatus('Werte erkannt – bitte vor dem Speichern prüfen.'); } catch { setScanStatus('Foto bereit. Die Erkennung ist nicht verfügbar – trage die Werte bitte manuell ein.'); } };
  const history = useMemo(() => Array.from({ length: 7 }, (_, index) => { const value = new Date(`${date}T12:00:00`); value.setDate(value.getDate() - (6 - index)); const label = value.toISOString().slice(0, 10); return { label, day: value.toLocaleDateString(undefined, { weekday: 'short' }), calories: totalCalories(state.foodEntries.filter(item => item.date === label)) }; }), [date, state.foodEntries]), maxHistory = Math.max(2000, ...history.map(item => item.calories));
  return <section className="pt-workbench calorie-workbench" aria-label={ui('Calorie Tracker')}>
    <header className="calorie-header"><div><p className="calorie-eyebrow">Nutrition tracker</p><h2>Dein Ernährungskompass</h2><p>Kalorien, Makros und Rezepte – klar an einem Ort.</p></div><div className="calorie-date"><button type="button" onClick={() => moveDay(-1)} aria-label="Previous day"><ChevronLeft size={18}/></button><Field label="Date"><input type="date" value={date} min="2000-01-01" max="2099-12-31" onChange={event => setDate(event.target.value)} /></Field><button type="button" onClick={() => moveDay(1)} aria-label="Next day"><ChevronRight size={18}/></button></div></header>
    <nav className="calorie-tabs" aria-label="Calorie tracker sections">{([{ id: 'today', label: 'Heute' }, { id: 'foods', label: 'Lebensmittel' }, { id: 'insights', label: 'Auswertung' }, { id: 'recipes', label: 'Rezeptbuch' }] as { id: Tab; label: string }[]).map(item => <button type="button" key={item.id} className={tab === item.id ? 'active' : ''} onClick={() => { setTab(item.id); if (item.id === 'recipes') void loadSharedRecipes(); }}>{item.label}</button>)}</nav>
    {tab === 'today' && <><div className="calorie-today-grid"><article className="calorie-card calorie-energy"><div><span className="calorie-label">Tagesenergie</span><strong>{Math.round(day.kcal).toLocaleString('de-DE')} <small>kcal</small></strong><p>{goal === null ? 'Lege optional ein Tagesziel fest.' : `${Math.round(remaining ?? 0).toLocaleString('de-DE')} kcal bis zu deinem Ziel`}</p></div><div className="calorie-ring" style={{ '--progress': `${goal ? Math.min(100, day.kcal / goal * 100) : 0}%` } as React.CSSProperties}><span>{goal ? `${Math.round(Math.min(100, day.kcal / goal * 100))}%` : '—'}</span></div><div className="calorie-goal"><label>Kalorienziel<input type="number" min="0" max="10000" value={goal ?? ''} placeholder="optional" onChange={event => update(current => ({ ...current, nutritionSettings: { calorieGoal: event.target.value ? Number(event.target.value) : null } }))} /></label></div></article><article className="calorie-card calorie-scan"><div className="calorie-scan-icon"><Camera size={24}/></div><div><h3>Etikett fotografieren</h3><p>Werte erkennen lassen und vor dem Speichern kontrollieren.</p><button type="button" className="calorie-primary" onClick={() => photoInput.current?.click()}><Sparkles size={16}/> Foto scannen</button><input ref={photoInput} type="file" accept="image/*" capture="environment" hidden onChange={event => { const file = event.target.files?.[0]; if (file) void scanPhoto(file); }} /></div></article></div>{scanStatus && <p className="calorie-status" role="status">{scanStatus}</p>}
      <div className="calorie-macro-grid">{[{ label: 'Eiweiß', value: day.protein, target: 90, tone: 'lime' }, { label: 'Kohlenhydrate', value: day.carbs, target: 250, tone: 'purple' }, { label: 'Fett', value: day.fat, target: 70, tone: 'orange' }, { label: 'Ballaststoffe', value: day.fiber, target: 30, tone: 'blue' }].map(item => <article className="calorie-card calorie-macro" key={item.label}><div><span>{item.label}</span><strong>{grams(item.value)}</strong></div><div className="calorie-meter"><i className={item.tone} style={{ width: `${Math.min(100, item.value / item.target * 100)}%` }} /></div><small>{Math.round(Math.min(100, item.value / item.target * 100))}% von {item.target} g</small></article>)}</div>
      <div className="calorie-layout"><article className="calorie-card calorie-log"><div className="calorie-section-title"><div><span className="calorie-label">Tagebuch</span><h3>Deine Mahlzeiten</h3></div><span>{foods.length} Einträge</span></div>{mealNames.map(meal => <div className="calorie-meal" key={meal}><h4><span>{mealIcons[meal]}</span>{ui(meal)} <small>{Math.round(totalCalories(foods.filter(item => item.meal === meal)))} kcal</small></h4>{foods.filter(item => item.meal === meal).map(item => <div className="calorie-entry" key={item.id}><div><b>{item.name}</b><small>{item.quantity} {item.unit === 'g' ? 'g' : 'Portionen'} · {Math.round(foodCalories(item))} kcal</small></div><div className="calorie-entry-actions"><button type="button" onClick={() => editEntry(item)}>Bearbeiten</button><button type="button" aria-label={`${item.name} löschen`} onClick={() => { remove('foodEntries', item.id); if (editing === item.id) { setEditing(null); setDraft(blankDraft()); } }}><Trash2 size={15}/></button></div></div>)}{!foods.some(item => item.meal === meal) && <p className="calorie-empty">Noch nichts eingetragen.</p>}</div>)}</article>
      <aside className="calorie-card calorie-form"><div className="calorie-section-title"><div><span className="calorie-label">Schneller Eintrag</span><h3>{editing ? 'Eintrag bearbeiten' : 'Lebensmittel hinzufügen'}</h3></div><Utensils size={20}/></div><form onSubmit={addEntry}><Field label="Food name"><input required maxLength={100} value={draft.name} onChange={event => set('name', event.target.value)} placeholder="z. B. Naturjoghurt" /></Field><div className="calorie-two"><Field label="Meal"><select value={draft.meal} onChange={event => set('meal', event.target.value as FoodEntry['meal'])}>{mealNames.map(meal => <option key={meal} value={meal}>{ui(meal)}</option>)}</select></Field><Field label="Portion unit"><select value={draft.unit} onChange={event => set('unit', event.target.value as FoodPortion['unit'])}><option value="g">Grams</option><option value="serving">Servings</option></select></Field></div><div className="calorie-two"><Field label="Portion quantity"><input required inputMode="decimal" value={draft.quantity} onChange={event => set('quantity', event.target.value)} /></Field><Field label={draft.unit === 'g' ? 'kcal per 100 g' : 'kcal per serving'}><input required inputMode="decimal" value={draft.energy} onChange={event => set('energy', event.target.value)} /></Field></div><div className="calorie-nutrient-inputs"><label>Eiweiß<input inputMode="decimal" value={draft.protein} onChange={event => set('protein', event.target.value)} /></label><label>Kohlenhydrate<input inputMode="decimal" value={draft.carbs} onChange={event => set('carbs', event.target.value)} /></label><label>Fett<input inputMode="decimal" value={draft.fat} onChange={event => set('fat', event.target.value)} /></label><label>Ballaststoffe<input inputMode="decimal" value={draft.fiber} onChange={event => set('fiber', event.target.value)} /></label></div><div className="calorie-form-actions"><button type="submit" disabled={loading} className="calorie-primary"><Plus size={16}/>{editing ? 'Save changes' : 'Add food'}</button><button type="button" className="calorie-secondary" onClick={rememberFood}><Clipboard size={15}/> Merken</button>{editing && <button type="button" className="calorie-secondary" onClick={() => { setEditing(null); setDraft(blankDraft()); }}>Cancel</button>}</div></form><p role="status" className="calorie-status">{message}</p></aside></div></>}
    {tab === 'foods' && <div className="calorie-page"><div className="calorie-page-heading"><div><p className="calorie-eyebrow">Schnell finden</p><h3>Lebensmitteldatenbank</h3><p>Standardwerte und deine eigenen Lebensmittel – immer mit prüfbaren Nährwerten.</p></div><input className="calorie-search" value={foodSearch} onChange={event => setFoodSearch(event.target.value)} placeholder="Lebensmittel suchen" /></div><div className="calorie-food-grid">{allFoods.map(food => <article className="calorie-card calorie-food" key={food.id}><span className="calorie-food-icon">{food.id.startsWith('standard') ? '✦' : '★'}</span><h4>{food.name}</h4><p>pro {food.quantity} {food.unit === 'g' ? 'g' : 'Portion'}</p><strong>{food.energy} kcal</strong><div><span>{food.nutrients?.protein ?? 0} g Eiweiß</span><button type="button" onClick={() => chooseFood(food)} aria-label={`${food.name} verwenden`}><Plus size={16}/></button></div></article>)}</div>{!allFoods.length && <p className="calorie-empty">Keine passenden Lebensmittel gefunden.</p>}</div>}
    {tab === 'insights' && <div className="calorie-page"><div className="calorie-page-heading"><div><p className="calorie-eyebrow">Dein Verlauf</p><h3>Die letzten sieben Tage</h3><p>Gespeicherte Tageswerte im Überblick.</p></div></div><article className="calorie-card calorie-chart"><div className="calorie-chart-bars">{history.map(item => <div key={item.label} className="calorie-bar-wrap"><span>{item.calories ? Math.round(item.calories) : ''}</span><i style={{ height: `${Math.max(4, item.calories / maxHistory * 100)}%` }} /><small>{item.day}</small></div>)}</div><div className="calorie-chart-summary"><div><span>Durchschnitt</span><strong>{Math.round(history.reduce((sum, item) => sum + item.calories, 0) / history.length)} kcal</strong></div><div><span>Höchster Tag</span><strong>{Math.round(Math.max(...history.map(item => item.calories)))} kcal</strong></div><button type="button" className="calorie-secondary" onClick={() => downloadCsv(csv([['Date', 'Meal', 'Food name', 'Portion quantity', 'Portion unit', 'Label energy', 'Protein g', 'Carbs g', 'Fat g', 'Fiber g', 'kcal'], ...state.foodEntries.map(item => [item.date, item.meal, item.name, item.quantity, item.unit, item.energy, item.nutrients?.protein ?? 0, item.nutrients?.carbs ?? 0, item.nutrients?.fat ?? 0, item.nutrients?.fiber ?? 0, foodCalories(item)])]), 'nutrition-history.csv')}><Download size={15}/> CSV exportieren</button></div></article></div>}
    {tab === 'recipes' && <div className="calorie-page"><div className="calorie-page-heading"><div><p className="calorie-eyebrow">Deine Sammlung</p><h3>Rezeptbuch</h3><p>Eigene Mahlzeiten wiederverwenden und mit Freundinnen und Freunden teilen.</p></div></div><section className="calorie-card calorie-recipe-create"><div><h4>Heutige Einträge als Rezept sichern</h4><p>Das Rezept verwendet die aktuell ausgewählten Einträge vom {date}.</p></div><label>Rezeptname<input value={recipeName} maxLength={100} onChange={event => setRecipeName(event.target.value)} placeholder="z. B. Power Bowl" /></label><label>Portionen<input inputMode="decimal" value={recipeServings} onChange={event => setRecipeServings(event.target.value)} /></label><button type="button" className="calorie-primary" onClick={saveRecipe}><Plus size={16}/> Rezept speichern</button></section><div className="calorie-recipe-grid">{recipeCards.map(recipe => { const values = intake(recipe.foods); return <article className="calorie-card calorie-recipe" key={`${recipe.source}-${recipe.id}`}><div className="calorie-recipe-top"><span>♨</span><small>{recipe.source === 'shared' ? 'Mit dir geteilt' : `${recipe.servings} Portion${recipe.servings === 1 ? '' : 'en'}`}</small></div><h4>{recipe.name}</h4><p>{Math.round(values.kcal / recipe.servings)} kcal pro Portion · {grams(values.protein / recipe.servings)} Eiweiß</p><div className="calorie-recipe-actions"><RecipeShoppingAction recipe={recipe}/><button type="button" className="calorie-secondary" onClick={() => logRecipe(recipe)}><Check size={15}/> Eintragen</button>{recipe.source === 'local' && <><input value={shareTo[recipe.id] ?? ''} onChange={event => setShareTo(current => ({ ...current, [recipe.id]: event.target.value }))} placeholder="Pluto-Nutzername" aria-label={`${recipe.name} teilen mit`} /><button type="button" className="calorie-share" onClick={() => void shareRecipe(recipe)}><Share2 size={15}/> Teilen</button><button type="button" className="calorie-icon-button" aria-label={`${recipe.name} löschen`} onClick={() => { remove('nutritionRecipes', recipe.id); remove('savedMeals', recipe.id); }}><Trash2 size={15}/></button></>}</div></article>; })}</div>{!recipeCards.length && <p className="calorie-empty">Noch keine Rezepte gespeichert.</p>}</div>}
    <StorageNote sessionOnly={sessionOnly} />
  </section>;
}
export default function CalorieTracker() { const { account } = useLifeTools(); return <Tracker key={account} />; }
