import useMoney from '@/hooks/useToolMoney';
import { localToday, downloadCsv } from '@/data/lifeToolsBrowser';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useLifeTools } from '@/hooks/useLifeTools';
import { moneyCents, nextRenewal, subscriptionCosts, csv, type Currency, type Subscription } from '@/data/lifeTools';
import { Field, CurrencyField, StorageNote, DeleteAction } from './LifeToolParts';
import { ui } from '@/i18n/ui';
function Tracker() {
  const { state, save, remove, sessionOnly, loading } = useLifeTools(), money = useMoney();
  const [currency, setCurrency] = useState<Currency>('EUR'), [name, setName] = useState(''), [amount, setAmount] = useState(''), [date, setDate] = useState(localToday), [cycle, setCycle] = useState<Subscription['cycle']>('monthly'), [editing, setEditing] = useState<string | null>(null), [active, setActive] = useState(true), [message, setMessage] = useState('');
  const today = localToday(), costs = subscriptionCosts(state.subscriptions, currency), subscriptions = state.subscriptions.filter(s => s.currency === currency).sort((a, b) => Number(b.active) - Number(a.active) || nextRenewal(a, today).localeCompare(nextRenewal(b, today)));
  const reset = () => { setEditing(null); setName(''); setAmount(''); setActive(true); };
  return <section className="pt-workbench" aria-label={ui('Subscription Tracker')}><CurrencyField value={currency} onChange={setCurrency} /><div className="life-summary"><div><small>{ui('Monthly equivalent')}</small><strong>≈ {money(costs.monthly, currency)}</strong></div><div><small>{ui('Annualized cost')}</small><strong>{money(costs.annual, currency)}</strong></div><div><small>{ui('Active subscriptions')}</small><strong>{subscriptions.filter(s => s.active).length}</strong></div></div><p className="lt-storage-note">{ui('Annualized costs include all active subscriptions in the selected currency, even future starts. Yearly fees are divided by 12 for the monthly equivalent; this is not the amount billed each month.')}</p>
    <form className="life-form" onSubmit={e => { e.preventDefault(); const cents = moneyCents(amount); const item: Subscription = { id: editing ?? crypto.randomUUID(), name: name.trim(), amount: cents ?? NaN, currency, date, cycle, active }; const success = save('subscriptions', item); if (success) reset(); setMessage(success ? 'Saved.' : 'Could not save. Check the inputs or storage limits.'); }}><div className="pt-inputs"><Field label="Subscription name"><input required maxLength={100} value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Price per billing cycle"><input inputMode="decimal" required maxLength={11} value={amount} onChange={e => setAmount(e.target.value)} /></Field><Field label="First renewal date"><input type="date" required min="2000-01-01" max="2099-12-31" value={date} onChange={e => setDate(e.target.value)} /></Field><Field label="Billing cycle"><select value={cycle} onChange={e => setCycle(e.target.value as Subscription['cycle'])}><option value="monthly">{ui('Monthly')}</option><option value="yearly">{ui('Yearly')}</option></select></Field></div><label className="life-check"><input type="checkbox" checked={active} onChange={e => setActive(e.target.checked)} />{ui('Active')}</label><div className="pt-actions"><button className="lt-button primary" type="submit" disabled={loading}>{ui(editing ? 'Save changes' : 'Add subscription')}</button>{editing && <button className="lt-button" type="button" onClick={reset}>{ui('Cancel')}</button>}</div></form><p role="status">{ui(message)}</p>
    <h2>{ui('Renewals and subscriptions')}</h2>{!subscriptions.length && <p>{ui('No subscriptions in this currency.')}</p>}<ul className="life-list">{subscriptions.map(item => <li className="life-row" key={item.id}><div><strong>{item.name}</strong><p>{money(item.amount, item.currency)} · {ui(item.cycle === 'monthly' ? 'Monthly' : 'Yearly')}</p><p>{ui(item.active ? 'Next renewal' : 'Inactive')} {item.active && nextRenewal(item, today)}</p></div><div className="pt-actions"><button className="lt-text-link" type="button" disabled={loading} onClick={() => save('subscriptions', { ...item, active: !item.active })}>{ui(item.active ? 'Deactivate' : 'Activate')}</button><button className="lt-text-link" type="button" onClick={() => { setEditing(item.id); setName(item.name); setAmount((item.amount / 100).toFixed(2)); setDate(item.date); setCycle(item.cycle); setActive(item.active); }}>{ui('Edit')}</button><DeleteAction name={item.name} onDelete={() => { remove('subscriptions', item.id); if (editing === item.id) reset(); }} /></div></li>)}</ul>
    <p className="lt-notice">{ui('Renewals keep the original day, clamping to the last day of shorter months. Deactivating here does not cancel a subscription with its provider. Renewal reminders can be added in Day Planner.')}</p><div className="pt-actions"><Link className="lt-button" to="/tools/day-planner">{ui('Day Planner')}</Link><button className="lt-button" type="button" onClick={() => downloadCsv(csv([[ui('Name'), ui('Amount'), ui('Currency'), ui('Billing cycle'), ui('First renewal date'), ui('Next renewal'), ui('Active')], ...subscriptions.map(s => [s.name, (s.amount / 100).toFixed(2), s.currency, ui(s.cycle === 'monthly' ? 'Monthly' : 'Yearly'), s.date, s.active ? nextRenewal(s, today) : '', s.active ? ui('Yes') : ui('No')])]), `subscriptions-${currency}.csv`)}>{ui('Export CSV')}</button></div><StorageNote sessionOnly={sessionOnly} />
  </section>;
}
export default function SubscriptionTracker() { const { account } = useLifeTools(); return <Tracker key={account} />; }
