import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useLifeTools } from '@/hooks/useLifeTools';
import { enablePush, disablePush, pushAction, pushBinding, usePushStatus, type PushOverview } from '@/hooks/useToolPush';
import { pushSupported } from '@/data/toolNotifications';
import { ui } from '@/i18n/ui';
function Settings() {
  const {state,account,loading,update}=useLifeTools(), status=usePushStatus(account);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[overview,setOverview]=useState<PushOverview|null>(null);
  const signedIn=account!=='guest',supported=pushSupported();
  const refresh=async()=>setOverview(await pushAction<PushOverview>(account,{action:'status'}));
  const run=async(action:()=>Promise<void>)=>{setBusy(true);setMessage('');try {await action();} catch {setMessage('Could not connect. Check notification permission, sign-in, and delivery setup.');}finally {setBusy(false);}};
  const bound=pushBinding()?.account===account;
  const deliveryLabels={pending:'Queued',sending:'Sending',accepted:'Accepted by push provider',shown:'Shown by device',clicked:'Opened on device',failed:'Delivery failed'};
  return <section className="lt-panel life-notification-settings" aria-label={ui('Background reminders')}><h2>{ui('Background reminders')}</h2><p>{ui('Opt in on each device to receive planner and birthday reminders when this page is closed. Reminder names and birthday month, day, and time zone are sent to the delivery service. Names may appear on the lock screen.')}</p><p>{ui('Only enabled planner and birthday reminders are shared. Birth years, food logs, budgets, and other tool records stay in this browser. Break reminders stay in-app.')}</p>
  {!supported && <p>{ui('Push notifications need a supported browser and a secure connection. On iPhone or iPad, open the installed home-screen app.')}</p>}
  {!signedIn ? <p><Link to="/login">{ui('Sign in to enable background reminders.')}</Link></p> : <><div className="pt-actions"><button type="button" className="lt-button" disabled={loading||busy||!supported} onClick={()=>void run(async()=>{await enablePush(account);update(s=>({...s,background:{...s.background,enabled:true}}));setMessage('Background reminders enabled on this device.');await refresh();})}>{ui(bound && state.background.enabled?'Reconnect this device':'Enable on this device')}</button><button type="button" className="lt-button" disabled={loading||busy||(!bound&&!state.background.enabled)} onClick={()=>void run(async()=>{update(s=>({...s,background:{...s.background,enabled:false}}));await disablePush(account);setMessage('This device is unsubscribed. Other devices keep their reminders.');await refresh();})}>{ui('Disable on this device')}</button><button type="button" className="lt-button" disabled={busy||loading} onClick={()=>void run(refresh)}>{ui('Check devices and delivery')}</button><button type="button" className="lt-button" disabled={busy||loading} onClick={()=>void run(async()=>{await pushAction(account,{action:'test'});await refresh();setMessage('Test requested. Refresh delivery status after the notification appears.');})}>{ui('Send test to all devices')}</button></div><p role="status">{ui(message)} {state.background.pending.length>0 && ui(status.error?'Reminder sync failed. Pending changes retry when online.':'Uploading reminder changes…')}</p>
  <p className="lt-storage-note">{ui('A test is allowed once per minute. Provider acceptance does not prove device delivery. “Shown” confirms the service worker displayed the notification; it does not prove you read it.')}</p>
  {overview && <><h3>{ui('Enrolled devices')}: {overview.devices.length}</h3><ul className="life-list">{overview.devices.map((d,i)=><li className="life-row" key={d.id}><span>{ui('Device')} {i+1} {d.id===pushBinding()?.device && `· ${ui('This device')}`} · {d.id.slice(0,8)}</span><button type="button" className="lt-text-link" disabled={busy} onClick={()=>void run(async()=>{if(d.id===pushBinding()?.device) {update(s=>({...s,background:{...s.background,enabled:false}}));await disablePush(account);}else await pushAction(account,{action:'unsubscribe',device:d.id});await refresh();})}>{ui('Remove device')}</button></li>)}</ul><h3>{ui('Cloud reminders')}</h3><ul className="life-list">{overview.reminders.map(r=><li className="life-row" key={r.id}><div><strong>{r.title}</strong><p>{new Date(r.at).toLocaleString()}</p></div><button type="button" className="lt-text-link" disabled={busy} onClick={()=>void run(async()=>{await pushAction(account,{action:'cancel',id:r.id});update(s=>({...s,tasks:s.tasks.map(t=>t.id===r.id?{...t,reminder:false}:t),birthdays:s.birthdays.map(p=>`birthday-${p.id}`===r.id?{...p,reminder:false}:p),background:{...s.background,pending:s.background.pending.filter(c=>c.id!==r.id)}}));await refresh();})}>{ui('Cancel reminder')}</button></li>)}</ul><h3>{ui('Recent delivery checks')}</h3><ul className="life-list">{overview.deliveries.map(d=><li className="life-row" key={d.id}><div><strong>{ui(deliveryLabels[d.status])}</strong><p>{ui('Device')} {d.device_id.slice(0,8)} · {new Date(d.updated_at).toLocaleString()}</p></div><span>{ui('Attempts')}: {d.attempts}</span></li>)}</ul></>}
  </>}</section>;
}
export default function ToolNotificationSettings() {const {account}=useLifeTools();return <Settings key={account}/>;}
