import { useToolClock } from '@/hooks/useToolClock';
import { useEffect, useState } from 'react';
import { geoEquirectangular, geoPath } from 'd3-geo';
import { feature } from 'topojson-client';
import type { GeometryCollection, Topology } from 'topojson-specification';
import { useLifeTools } from '@/hooks/useLifeTools';
import { fetchWeatherJson, forecastUrl, parseForecast, parsePlaces, validCoordinates, mapCoordinates, weatherLabel, type WeatherPlace, type WeatherForecast } from '@/data/weatherTools';
import { ui, useUiLanguage } from '@/i18n/ui';
import { Field, StorageNote, DeleteAction } from './LifeToolParts';
import './weatherTools.css';
const initial: WeatherPlace = { id: 'berlin', name: 'Berlin', latitude: 52.52, longitude: 13.41 };
const projection = geoEquirectangular().scale(900 / (2 * Math.PI)).translate([450, 225]);
function Forecast({ place, offset, refresh, startAt }: { place: WeatherPlace; offset: number; refresh: number; startAt: number }) {
  const { language } = useUiLanguage();
  const [result, setResult] = useState<{ key: string; data?: WeatherForecast; error?: boolean } | null>(null);
  const key = `${place.latitude},${place.longitude}:${refresh}`;
  useEffect(() => { const controller = new AbortController(); fetchWeatherJson(forecastUrl(place), controller.signal).then(data => { if (!controller.signal.aborted) setResult({ key, data: parseForecast(data) }); }).catch(() => { if (!controller.signal.aborted) setResult({ key, error: true }); }); return () => controller.abort(); }, [key, place]);
  const data = result?.key === key ? result.data : null;
  const format = (at: number) => new Intl.DateTimeFormat(language === 'bar' ? 'de' : language, { timeZone: data?.zone ?? 'UTC', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', timeZoneName: 'short' }).format(at);
  const hours = data?.hours.filter(h => h.at >= Math.floor(startAt / 3600000) * 3600000).slice(offset, offset + 24) ?? [];
  const selected = hours[0];
  return <article className="weather-card"><h2>{place.name}</h2><p>{place.latitude.toFixed(3)}°, {place.longitude.toFixed(3)}°</p>{result?.key !== key ? <p role="status">{ui('Loading forecast…')}</p> : result.error ? <p role="alert">{ui('Forecast unavailable. Check your connection and try Refresh.')}</p> : <><p className="lt-storage-note">{ui('Forecast time zone')}: {data?.zone} · {ui('Retrieved')}: {data && format(data.fetchedAt)}</p><div className="life-summary"><div><small>{ui('Temperature')}</small><strong>{selected?.temperature ?? '—'} °C</strong></div><div><small>{ui('Rain probability')}</small><strong>{selected?.rainChance ?? '—'} %</strong></div><div><small>{ui('Wind')}</small><strong>{selected?.wind ?? '—'} km/h</strong></div></div>
  {hours.length ? <><svg className="weather-chart" viewBox="0 0 600 160" role="img" aria-label={ui('Hourly temperature chart')}><title>{ui('Hourly temperature chart')}</title>{(() => { const values = hours.flatMap(h => h.temperature === null ? [] : [h.temperature]); if (!values.length) return null; const min = Math.min(...values) - 2, max = Math.max(...values) + 2, y = (n: number) => 130 - (n - min) / (max - min) * 100; return <><text x="5" y="18">{max.toFixed(0)} °C</text><text x="5" y="145">{min.toFixed(0)} °C</text>{hours.slice(1).map((h, i) => h.temperature !== null && hours[i].temperature !== null ? <line key={h.at} x1={55 + i * 22} x2={55 + (i + 1) * 22} y1={y(hours[i].temperature!)} y2={y(h.temperature)} /> : null)}<text x="55" y="158">{format(hours[0].at)}</text></>; })()}</svg><div className="life-table-wrap"><table className="life-table"><caption>{ui('Hourly forecast')} · {ui('Missing data appears as a dash.')}</caption><thead><tr>{['Local time', 'Conditions', 'Temperature', 'Rain probability', 'Precipitation', 'Wind'].map(k => <th key={k} scope="col">{ui(k)}</th>)}</tr></thead><tbody>{hours.map(h => <tr key={h.at}><td>{format(h.at)}</td><td>{ui(weatherLabel(h.code))}</td><td>{h.temperature ?? '—'} °C</td><td>{h.rainChance ?? '—'} %</td><td>{h.precipitation ?? '—'} mm</td><td>{h.wind ?? '—'} km/h</td></tr>)}</tbody></table></div></> : <p>{ui('No forecast hours available.')}</p>}</>}</article>;
}
function Explorer() {
  const { language } = useUiLanguage();
  const startAt = useToolClock(true);
  const { state, save, remove, loading, sessionOnly } = useLifeTools();
  const [place, setPlace] = useState<WeatherPlace>(initial), [latitude, setLatitude] = useState(String(initial.latitude)), [longitude, setLongitude] = useState(String(initial.longitude)), [query, setQuery] = useState(''), [search, setSearch] = useState<{ query: string; language: string; results: WeatherPlace[]; error: boolean } | null>(null), [submitted, setSubmitted] = useState(''), [searchAttempt, setSearchAttempt] = useState(0), [comparison, setComparison] = useState<string>(''), [offset, setOffset] = useState(0), [refresh, setRefresh] = useState(0), [land, setLand] = useState(''), [message, setMessage] = useState('');
  useEffect(() => { const controller = new AbortController(); fetch('/data/geography/world-110m.json', { signal: controller.signal }).then(r => r.json()).then((data: Topology<{ countries: GeometryCollection }>) => { if (!controller.signal.aborted) setLand(geoPath(projection)(feature(data, data.objects.countries)) ?? ''); }).catch(() => {}); return () => controller.abort(); }, []);
  useEffect(() => { if (!submitted) return; const controller = new AbortController(); const params = new URLSearchParams({ name: submitted, count: '8', language: language === 'bar' ? 'de' : language }); fetchWeatherJson(`https://geocoding-api.open-meteo.com/v1/search?${params}`, controller.signal).then(data => { if (!controller.signal.aborted) setSearch({ query: submitted, language, results: parsePlaces(data), error: false }); }).catch(() => { if (!controller.signal.aborted) setSearch({ query: submitted, language, results: [], error: true }); }); return () => controller.abort(); }, [submitted, language, searchAttempt]);
  const choose = (p: WeatherPlace) => { setPlace(p); setLatitude(String(p.latitude)); setLongitude(String(p.longitude)); setMessage(''); };
  const coordinatePlace = (lat: number, lon: number): WeatherPlace => ({ id: `point-${String(lat).replace(/[.]/g, '-')}-${String(lon).replace(/[.]/g, '-')}`, name: `${lat.toFixed(3)}°, ${lon.toFixed(3)}°`, latitude: lat, longitude: lon });
  const compared = state.weatherPlaces.find(p => p.id === comparison);
  const currentSearch = search?.query === submitted && search.language === language ? search : null;
  return <section className="pt-workbench" aria-label={ui('Weather Explorer')}><form className="life-form" onSubmit={e => { e.preventDefault(); setSubmitted(query.trim()); setSearch(null); setSearchAttempt(n => n + 1); }}><div className="pt-inputs"><Field label="Search location"><input type="search" minLength={2} maxLength={100} required value={query} onChange={e => setQuery(e.target.value)} /></Field></div><button className="lt-button" type="submit">{ui('Search')}</button></form>{submitted && (!currentSearch ? <p role="status">{ui('Searching…')}</p> : currentSearch.error ? <p role="alert">{ui('Location search failed. Try again.')}</p> : !currentSearch.results.length ? <p>{ui('No matching locations.')}</p> : <ul className="life-list">{currentSearch.results.map(p => <li key={p.id}><button className="lt-button" type="button" onClick={() => choose(p)}>{p.name}</button></li>)}</ul>)}
  <p>{ui('Choose a point on the world map, use arrow keys to move the marker, or enter coordinates below.')}</p><svg className="weather-map" viewBox="0 0 900 450" role="group" aria-label={ui('World location picker')} tabIndex={0} onClick={e => { const svg = e.currentTarget; const pt = new DOMPoint(e.clientX, e.clientY).matrixTransform(svg.getScreenCTM()!.inverse()); const p = mapCoordinates(pt.x / 900, pt.y / 450); choose(coordinatePlace(p.latitude, p.longitude)); }} onKeyDown={e => { const shifts: Record<string, [number, number]> = { ArrowLeft: [0, -1], ArrowRight: [0, 1], ArrowUp: [1, 0], ArrowDown: [-1, 0] }; const shift = shifts[e.key]; if (!shift) return; e.preventDefault(); const lat = Math.max(-90, Math.min(90, place.latitude + shift[0])), lon = Math.max(-180, Math.min(180, place.longitude + shift[1])); choose(coordinatePlace(lat, lon)); }}><title>{ui('World location picker')}</title><rect width="900" height="450" className="weather-ocean" /><path d={land} className="weather-land" />{[150, 300, 450, 600, 750].map(x => <line key={x} x1={x} x2={x} y1="0" y2="450" />)}{[75, 150, 225, 300, 375].map(y => <line key={y} x1="0" x2="900" y1={y} y2={y} />)}<circle cx={(place.longitude + 180) * 2.5} cy={(90 - place.latitude) * 2.5} r="7" className="weather-marker" /></svg>
  <form className="life-form" onSubmit={e => { e.preventDefault(); const lat = Number(latitude), lon = Number(longitude); if (!latitude.trim() || !longitude.trim() || !validCoordinates(lat, lon)) { setMessage('Enter latitude from −90 to 90 and longitude from −180 to 180.'); return; } choose(coordinatePlace(Math.round(lat * 1000) / 1000, Math.round(lon * 1000) / 1000)); }}><div className="pt-inputs"><Field label="Latitude"><input type="number" required min="-90" max="90" step="any" value={latitude} onChange={e => setLatitude(e.target.value)} /></Field><Field label="Longitude"><input type="number" required min="-180" max="180" step="any" value={longitude} onChange={e => setLongitude(e.target.value)} /></Field></div><div className="pt-actions"><button className="lt-button">{ui('Explore coordinates')}</button><button type="button" className="lt-button" disabled={loading} onClick={() => setMessage(save('weatherPlaces', place) ? 'Saved.' : 'Could not save. Check the inputs or storage limits.')}>{ui('Save place')}</button><button type="button" className="lt-button" onClick={() => { setRefresh(v => v + 1); setSubmitted(''); setSearch(null); }}>{ui('Refresh')}</button></div></form><p role="status">{ui(message)}</p>
  <h2>{ui('Favorite places')}</h2><ul className="life-list">{state.weatherPlaces.map(p => <li className="life-row" key={p.id}><button className="lt-text-link" type="button" onClick={() => choose(p)}>{p.name}</button><DeleteAction name={p.name} onDelete={() => { remove('weatherPlaces', p.id); if (comparison === p.id) setComparison(''); }} /></li>)}</ul><div className="pt-inputs"><Field label="Compare with"><select value={comparison} onChange={e => setComparison(e.target.value)}><option value="">{ui('No comparison')}</option>{state.weatherPlaces.filter(p => p.id !== place.id).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Forecast window"><select value={offset} onChange={e => setOffset(Number(e.target.value))}><option value="0">{ui('Next 24 hours')}</option><option value="24">{ui('Hours 24–48')}</option></select></Field></div><div className="weather-forecasts"><Forecast place={place} offset={offset} refresh={refresh} startAt={startAt} />{compared && compared.id !== place.id && <Forecast place={compared} offset={offset} refresh={refresh} startAt={startAt} />}</div><p className="lt-storage-note">{ui('Forecasts are model estimates. Comparisons use the same UTC hours and show each location’s local time. Data is requested when you open or refresh a location; forecasts are not saved offline.')}</p><p><a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a> · <a href="https://www.geonames.org/" target="_blank" rel="noreferrer">GeoNames</a> · <a href="https://www.naturalearthdata.com/" target="_blank" rel="noreferrer">Natural Earth</a></p><StorageNote sessionOnly={sessionOnly} /></section>;
}
export default function WeatherExplorer() { const { account } = useLifeTools(); return <Explorer key={account} />; }
