import { useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useLifeTools } from '@/hooks/useLifeTools';
import { useToolClock } from '@/hooks/useToolClock';
import { routineProgress, type Routine, type RoutineExercise } from '@/data/lifeTools';
import { Field, StorageNote, DeleteAction } from './LifeToolParts';
import { ui } from '@/i18n/ui';
const newExercise = (): RoutineExercise => ({ id: crypto.randomUUID(), name: '', sets: 3, reps: 10, duration: 30, rest: 15 });
function RoutineEditor({ initial, onSaved, onCancel }: { initial?: Routine; onSaved: (id: string) => void; onCancel: () => void }) {
  const { save, loading } = useLifeTools();
  const [name, setName] = useState(initial?.name ?? ''), [exercises, setExercises] = useState<RoutineExercise[]>(initial?.exercises ?? (initial ? [{ id: crypto.randomUUID(), name: initial.name, sets: initial.rounds, reps: 0, duration: initial.work, rest: initial.rest }] : [newExercise()])), [message, setMessage] = useState('');
  const change = (id: string, change: Partial<RoutineExercise>) => setExercises(exercises.map(e => e.id === id ? { ...e, ...change } : e));
  const move = (index: number, delta: number) => { const next = [...exercises]; [next[index], next[index + delta]] = [next[index + delta], next[index]]; setExercises(next); };
  return <form className="life-form" onSubmit={e => { e.preventDefault(); const id = initial?.id ?? crypto.randomUUID(), first = exercises[0]; if (!first) return; if (save('routines', { id, name: name.trim(), work: first.duration, rest: first.rest, rounds: first.sets, exercises: exercises.map(item => ({ ...item, name: item.name.trim() })) })) onSaved(id); else setMessage('Could not save. Check the inputs or storage limits.'); }}><Field label="Workout name"><input required maxLength={100} value={name} onChange={e => setName(e.target.value)} /></Field><div className="life-exercise-editor">{exercises.map((exercise, index) => <fieldset key={exercise.id}><legend>{ui('Exercise')} {index + 1}</legend><div className="pt-inputs"><Field label="Exercise name"><input required maxLength={100} value={exercise.name} onChange={e => change(exercise.id, { name: e.target.value })} /></Field>{([['sets', 'Sets', 1, 100], ['reps', 'Reps', 0, 1000], ['duration', 'Duration in seconds', 1, 3600], ['rest', 'Rest seconds', 0, 3600]] as const).map(([key, label, min, max]) => <Field label={label} key={key}><input required type="number" min={min} max={max} step="1" value={exercise[key]} onChange={e => change(exercise.id, { [key]: Number(e.target.value) })} /></Field>)}</div><div className="pt-actions"><button className="lt-button" type="button" disabled={index === 0} aria-label={`${ui('Move up')}: ${exercise.name}`} onClick={() => move(index, -1)}>{ui('Move up')}</button><button className="lt-button" type="button" disabled={index === exercises.length - 1} aria-label={`${ui('Move down')}: ${exercise.name}`} onClick={() => move(index, 1)}>{ui('Move down')}</button><button className="lt-text-link" type="button" disabled={exercises.length === 1} onClick={() => setExercises(exercises.filter(item => item.id !== exercise.id))}>{ui('Remove exercise')}</button></div></fieldset>)}</div><div className="pt-actions"><button className="lt-button" type="button" disabled={exercises.length >= 100} onClick={() => setExercises([...exercises, newExercise()])}>{ui('Add exercise')}</button><button className="lt-button primary" disabled={loading}>{ui('Save routine')}</button><button className="lt-button" type="button" onClick={onCancel}>{ui('Cancel')}</button></div><p role="status">{ui(message)}</p></form>;
}
function RoutinePlayer({ routine }: { routine: Routine }) {
  const [sound, setSound] = useState(false), [elapsed, setElapsed] = useState(0), [started, setStarted] = useState<number | null>(() => Date.now()), [message, setMessage] = useState('');
  const audio = useRef<AudioContext | null>(null), lastPhase = useRef('');
  const now = useToolClock(started !== null), seconds = elapsed + (started !== null ? Math.max(0, now - started) / 1000 : 0), result = routineProgress(routine, seconds), phaseKey = `${result.exercise.id}-${result.phase}-${result.set}`, running = started !== null && result.phase !== 'Finished';
  useEffect(() => {
    if (lastPhase.current !== phaseKey && started !== null && sound && audio.current?.state === 'running') {
      const context = audio.current, oscillator = context.createOscillator(), gain = context.createGain(); oscillator.frequency.value = result.phase === 'Rest' ? 440 : 880; gain.gain.setValueAtTime(.08, context.currentTime); gain.gain.exponentialRampToValueAtTime(.001, context.currentTime + .18); oscillator.connect(gain); gain.connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + .2);
    }
    lastPhase.current = phaseKey;
  }, [phaseKey, started, sound, result.phase]);
  useEffect(() => () => { void audio.current?.close(); }, []);
  const begin = () => { if (sound) { try { audio.current ??= new AudioContext(); void audio.current.resume().catch(() => setMessage('Sound is unavailable. The visual timer still works.')); } catch { setMessage('Sound is unavailable. The visual timer still works.'); } } if (result.phase === 'Finished') setElapsed(0); setStarted(Date.now()); };
  return <div><div className="life-timer"><p role="status">{ui(result.phase)} · {result.exercise.name} · {ui('Set')} {result.set}/{result.exercise.sets}</p><output aria-label={ui('Remaining time')}>{String(Math.floor(result.remaining / 60)).padStart(2, '0')}:{String(result.remaining % 60).padStart(2, '0')}</output><p>{result.exercise.reps > 0 && `${result.exercise.reps} ${ui('reps')} · `}{ui('Total duration')} · {Math.floor(result.total / 60)}:{String(result.total % 60).padStart(2, '0')}</p></div><label className="life-check"><input type="checkbox" checked={sound} disabled={running} onChange={e => setSound(e.target.checked)} />{ui('Sound cues')}</label><div className="pt-actions"><button className="lt-button primary" type="button" disabled={running} onClick={begin}>{ui(result.phase === 'Finished' ? 'Replay workout' : elapsed > 0 ? 'Resume' : 'Start')}</button><button className="lt-button" type="button" disabled={!running} onClick={() => { setElapsed(seconds); setStarted(null); }}>{ui('Pause')}</button><button className="lt-button" type="button" onClick={() => { setStarted(null); setElapsed(0); lastPhase.current = ''; }}>{ui('Reset')}</button></div>{result.phase === 'Finished' && <p role="status">{ui('Workout complete. Your routine is saved and ready to replay.')}</p>}<p role="status">{ui(message)}</p><p className="lt-storage-note">{ui('The timer follows elapsed time when a tab is suspended. Sound may be delayed or unavailable in the background. Leaving this page resets the timer; saved routines remain.')}</p></div>;
}
function BreakSettings() {
  const { state, update, loading } = useLifeTools();
  const [interval, setInterval] = useState(String(state.breaks.interval)), [message, setMessage] = useState('');
  return <details><summary>{ui('Break reminders')}</summary><form className="life-form" onSubmit={e => { e.preventDefault(); const minutes = Number(interval); setMessage(update(s => ({ ...s, breaks: { enabled: true, interval: minutes, nextAt: Date.now() + minutes * 60000 } })) ? 'Break reminders enabled.' : 'Use a whole number of minutes from 1 to 240.'); }}><Field label="Break interval in minutes"><input type="number" required min="1" max="240" step="1" value={interval} onChange={e => setInterval(e.target.value)} /></Field><div className="pt-actions"><button className="lt-button" disabled={loading}>{ui('Enable break reminders')}</button><button type="button" className="lt-button" disabled={loading || !state.breaks.enabled} onClick={() => update(s => ({ ...s, breaks: { ...s.breaks, enabled: false } }))}>{ui('Turn off')}</button></div></form><p>{ui(state.breaks.enabled ? 'Break reminders are on.' : 'Break reminders are off.')}</p><p className="lt-storage-note">{ui('Break reminders appear while Pluto is open and do not send push notifications.')}</p><p role="status">{ui(message)}</p></details>;
}
function Workouts() {
  const { state, remove, sessionOnly } = useLifeTools();
  const [params, setParams] = useSearchParams();
  const id = params.get('routine'), view = params.get('view'), routine = state.routines.find(r => r.id === id);
  const navigate = (id?: string, view?: string) => { const next = new URLSearchParams(params); if (id) next.set('routine', id); else next.delete('routine'); if (view) next.set('view', view); else next.delete('view'); setParams(next); };
  return <section className="pt-workbench" aria-label={ui('Workout routines')}><div className="life-workspace"><div>{view === 'new' || routine && view === 'edit' ? <><h2>{ui(view === 'new' ? 'Create workout' : 'Edit Routine')}</h2><RoutineEditor key={routine?.id ?? 'new'} initial={view === 'new' ? undefined : routine} onSaved={id => navigate(id)} onCancel={() => navigate(routine?.id)} /></> : routine ? <><button type="button" className="lt-text-link" onClick={() => navigate()}>{ui('Back to workouts')}</button><h2>{routine.name}</h2><div className="pt-actions"><button className="lt-button primary" type="button" disabled={view === 'start'} onClick={() => navigate(routine.id, 'start')}>{ui('Start Workout')}</button><button className="lt-button" type="button" onClick={() => navigate(routine.id, 'edit')}>{ui('Edit Routine')}</button></div>{view === 'start' ? <RoutinePlayer key={routine.id} routine={routine} /> : <ol className="life-list">{(routine.exercises ?? [{ id: 'legacy', name: routine.name, sets: routine.rounds, reps: 0, duration: routine.work, rest: routine.rest }]).map((e, i) => <li className="life-row" key={e.id}><strong>{i + 1}. {e.name}</strong><span>{e.sets} {ui('sets')} · {e.reps > 0 && `${e.reps} ${ui('reps')} · `}{e.duration}s · {ui('Rest')} {e.rest}s</span></li>)}</ol>}</> : <><div className="pt-actions"><h2>{ui('Saved workouts')}</h2><button className="lt-button primary" type="button" onClick={() => navigate(undefined, 'new')}>{ui('Create workout')}</button></div>{!state.routines.length && <p>{ui('Create a reusable routine for your next workout.')}</p>}<ul className="life-list">{state.routines.map(item => <li className="life-row" key={item.id}><button className="lt-text-link" type="button" onClick={() => navigate(item.id)}>{item.name}</button><span>{item.exercises?.length ?? 1} {ui('exercises')}</span><DeleteAction name={item.name} onDelete={() => remove('routines', item.id)} /></li>)}</ul></>}</div><aside><BreakSettings /><StorageNote sessionOnly={sessionOnly} /></aside></div></section>;
}
export default function WorkoutTimer() { const { account } = useLifeTools(); return <Workouts key={account} />; }
