import { gameUi, useGameLanguage } from "../../i18n/gameUi.ts";
import GameXpReward from "@/components/games/GameXpReward";
import { useState } from "react";
import { AtlasWorldMap } from "./AtlasWorldMap";
import { ArenaQuestionInput } from "./ArenaQuestionInput";
import { toPublicQuestion } from "../../games/atlas/publicQuestion";
import { validateAnswer } from "../../games/atlas/engine";
import { freshSeed } from "../../games/atlas/arenaStorage";
import { emptyMastery, loadMastery, masteryQuestions, MASTERY_STAGES, recordMastery, saveMastery } from "../../games/atlas/mastery";
import { entitiesInFillScope, FILL_SCOPES, focusForScope, type FillScope } from "../../games/atlas/scopes";
import type { AtlasDataset, AtlasQuestion } from "../../games/atlas/types";
export function AtlasMastery({data}:{data:AtlasDataset|null}) {
  useGameLanguage();
  const [progress,setProgress]=useState(loadMastery),[region,setRegion]=useState<FillScope>("Europe"),[run,setRun]=useState<{seed:string;stage:number;questions:AtlasQuestion[];answers:{question:AtlasQuestion;correct:boolean}[]}|null>(null),[feedback,setFeedback]=useState<{correct:boolean;answer:string}|null>(null),[result,setResult]=useState<string|null>(null);
  if(!data)return <p>{gameUi("Loading mastery regions…")}</p>;
  const current=progress[region]??emptyMastery(),count=entitiesInFillScope(data.countries,region).length;
  const answer=(value:string|string[])=>{if(!run||feedback)return;const q=run.questions[run.answers.length],correct=validateAnswer(q,value);const text=Array.isArray(q.answer)?q.answer.map(id=>data.countries.find(c=>c.id===id)?.shortName??id).join(", "):q.interaction==="single_choice"?q.choices.find(c=>c.id===q.answer)?.label??q.answer:data.countries.find(c=>c.id===q.answer)?.shortName??String(q.answer);setFeedback({correct,answer:text});setRun({...run,answers:[...run.answers,{question:q,correct}]});};
  const next=()=>{if(!run)return;if(run.answers.length===run.questions.length){const updated=recordMastery(progress,region,run.seed,run.stage,run.answers,count);setProgress(updated);saveMastery(updated);setResult(`${run.answers.filter(a=>a.correct).length} / 10 correct · ${updated[region]!.stage>current.stage?"New stage earned!":"Progress saved"}`);setRun(null);}setFeedback(null);};
  if(run){const q=run.questions[Math.min(run.answers.length-Number(Boolean(feedback)),run.questions.length-1)];return <section className={`atlas-play-layout ${q.interaction==="map_click"?"":"is-panel-only"}`}><aside className="atlas-question-panel"><button className="atlas-room-leave" onClick={()=>{setRun(null);setFeedback(null);}}>{gameUi("Back to regions")}</button><span className="atlas-eyebrow">{gameUi(region)} · {gameUi(MASTERY_STAGES[run.stage])} · {gameUi(run.answers.length+Number(!feedback))} / 10</span><h2>{gameUi(q.prompt)}</h2>{!feedback&&<ArenaQuestionInput key={q.id} question={toPublicQuestion(q,q.id)} topology={data.topology} disabled={false} onAnswer={answer}/>} {feedback&&<div className={`atlas-feedback ${feedback.correct?"is-correct":"is-wrong"}`} role="status"><div><strong>{gameUi(feedback.correct?"Correct":"Review")}</strong><p>{gameUi(feedback.answer)}</p><button className="atlas-submit" onClick={next}>{gameUi(run.answers.length===10?"Finish expedition":"Next question")}</button></div></div>}</aside>{q.interaction==="map_click"&&<AtlasWorldMap topology={data.topology} entities={data.countries} focus={focusForScope(region)} showHoverLabels={false} disabled={Boolean(feedback)} onSelect={answer} correctId={feedback?q.entityId:null}/>}</section>;}
  return <section className="atlas-mastery"><span className="atlas-eyebrow">{gameUi("Your regional journey · saved on this device")}</span><h2>{gameUi("Explore. Connect. Reason.")}</h2><p>{gameUi("Build mastery separately from your competitive rank. Each stage needs two runs with at least 8/10 correct and broad concept coverage. Review mistakes at your own pace.")}</p><div className="atlas-mastery-regions">{FILL_SCOPES.filter(s=>s!=="World").map(s=>{const p=progress[s]??emptyMastery();return <button key={gameUi(s)} className={s===region?"active":""} onClick={()=>{setRegion(s);setResult(null);}}><strong>{gameUi(s)}</strong><span>{gameUi(p.stage===3?"Mastered":MASTERY_STAGES[p.stage])} · {gameUi(p.stage)}{gameUi("/3 stages")}</span><progress value={gameUi(p.stage)} max={3}/></button>;})}</div><article className="atlas-mastery-detail"><h3>{gameUi(region)} · {gameUi(current.stage===3?"Mastered":MASTERY_STAGES[current.stage])}</h3><p>{gameUi(count)}{gameUi(" countries · ")}{gameUi(current.successes[Math.min(current.stage,2)])}{gameUi(" qualifying runs in this stage · ")}{gameUi(current.concepts[Math.min(current.stage,2)].length)}{gameUi(" concepts learned")}</p><div className="atlas-mastery-stages">{MASTERY_STAGES.map((stage,i)=><span key={gameUi(stage)} className={i<current.stage?"earned":""}>{i<current.stage?"✓ ":""}{gameUi(stage)}</span>)}</div>{result&&<><p role="status">{gameUi(result)}</p><GameXpReward /></>}{current.review.length>0&&<p>{gameUi("Review: ")}{gameUi(current.review.map(id=>data.countries.find(c=>c.id===id)?.shortName).filter(Boolean).join(", "))}</p>}<button className="atlas-start" onClick={()=>{const seed=freshSeed(),stage=Math.min(current.stage,2);setRun({seed,stage,questions:masteryQuestions(data,region,stage,seed),answers:[]});setResult(null);}}>{gameUi(current.stage===3?"Practice this region":"Start expedition")}</button></article></section>;
}
