import { Link } from "react-router-dom";
import DashboardDialog from "@/components/App/dashboard/DashboardDialog";
import { RANK_THRESHOLDS } from "@/games/atlas/ranked";
import { useAtlasRanks } from "@/games/atlas/useAtlasRanks";
import AtlasRankBadge from "./AtlasRankBadge";

export function AtlasRankGuide({ onClose }: { onClose: () => void }) {
  return <DashboardDialog title="Atlas rank information" onClose={onClose}><p className="text-sm leading-6 text-slate-300">Your rating starts at 1500. Ten series establish your level, with a tentative rank after three. Best of three uses bounded games and knowledge challenges for ties; response speed contributes at most 5% in map questions. Glicko-2 tracks uncertainty. Promotion pace responds to opponent strength: equally rated established wins typically earn at least 20 below Platinum, 16 in Platinum, 12 in Diamond and 9 in Master or higher; expected wins against weaker players earn less. Established movement is capped at 40 below Platinum, 32 in Platinum, 24 in Diamond and 18 in Master or higher. Diamond requires 14 series, Master 20 and Grandmaster 30, plus rating supported by a half-deviation confidence margin. These are evidence requirements, not win streak bonuses. Both players share the question tier at their average rating: beginner below Gold, intermediate below Diamond, expert thereafter; Master adds geographic constraints and applied ratios, Grandmaster adds compound constraints. Established players appear on the leaderboard; only the top ten show a position inside their badge.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{RANK_THRESHOLDS.map((rank, index) => <article key={index} className="rounded-xl border border-white/10 bg-white/5 p-3"><AtlasRankBadge rating={Number.isFinite(rank.rating) ? rank.rating : 100} /><p className="mt-2 text-sm text-slate-400">{index === 0 ? "Below 800" : index === RANK_THRESHOLDS.length - 1 ? "2400+" : `${rank.rating}–${RANK_THRESHOLDS[index + 1].rating - 1}`} Rating</p></article>)}</div></DashboardDialog>;
}
export function AtlasLeaderboard({ onClose }: { onClose: () => void }) {
  const { rows, loading, error } = useAtlasRanks();
  return <DashboardDialog title="Atlas ranked leaderboard" onClose={onClose}>{loading ? <p>Loading leaderboard…</p> : error ? <p role="alert">{error}</p> : !rows.length ? <p>Complete ten placement series to join the leaderboard.</p> : <ol className="space-y-2">{rows.map(row => <li key={row.user_id} className="flex flex-wrap items-center gap-3 rounded-xl border border-white/10 bg-white/5 p-3"><span className="w-8 text-slate-400">{row.leaderboard_rank}</span><Link to={`/profile/${row.user_id}`} className="min-w-20 flex-1 font-bold">{row.username || "Explorer"}</Link><AtlasRankBadge rating={row.rating} deviation={row.deviation} matchesPlayed={row.matches_played} position={row.leaderboard_rank} /><strong>{Math.round(row.rating)}</strong></li>)}</ol>}</DashboardDialog>;
}
