import type { AiDifficulty, GameView } from './schafkopf.ts';
import type { ReasonCode } from './bot.ts';
export type Lesson = { id: string; code: ReasonCode; kind: 'rule' | 'tip'; title: string; text: string };
export const SCHAFKOPF_LESSONS: Lesson[] = [
  {id:'follow',code:'ENGINE',kind:'rule',title:'Bedienen geht vor',text:'Trumpf muss mit Trumpf bedient werden, Fehlfarbe mit derselben Fehlfarbe. Ober und Unter zählen nur dann zur Farbe, wenn sie in der Spielart keine Trümpfe sind. Frei darfst du beliebig abwerfen oder stechen; die Engine erzwingt keinen Stich und kein Überstechen.'},
  {id:'winner',code:'ENGINE',kind:'rule',title:'Wer gewinnt den Stich?',text:'Der höchste Trumpf gewinnt. Ohne Trumpf gewinnt die höchste Karte der angespielten Farbe. Eine andere Fehlfarbe kann den Stich nie gewinnen.'},
  {id:'ace',code:'ENGINE',kind:'rule',title:'Die Rufsau schützen',text:'Wenn die Ruffarbe angespielt wird, muss die Rufsau zugegeben werden. In eine andere Farbe darf sie frühestens im vorletzten Stich geschmiert werden. Davonlaufen ist mit mindestens vier aktuellen Karten der Ruffarbe einschließlich Sau erlaubt. Nach erfolgreichem Davonlaufen darf beim Ausspiel und beim Bedienen jede Karte der Ruffarbe gelegt werden, auch die Sau. Die allgemeine Bedienpflicht bleibt bestehen.'},
  {id:'threshold',code:'ENGINE',kind:'rule',title:'Punkte und Stiche zählen',text:'Ohne Spritzen braucht die Spielerpartei 61, die Gegenseite 60 Punkte. Schneiderfrei sind Spieler ab 31, Gegenspieler ab 30. Nach Spritzen braucht immer die zuletzt spritzende Partei 61 Punkte zum Sieg und 31 für schneiderfrei. Schwarz heißt kein einziger Stich: Auch ein Stich mit null Punkten verhindert Schwarz.'},
  {id:'A1',code:'A1',kind:'rule',title:'Die passende Rufsau',text:'Rufe die Sau deiner kürzesten rufbaren Fehlfarbe. Bei gleicher Kartenanzahl wähle die Farbe mit deiner punktereicheren Karte. Du brauchst eine Nicht-Trumpfkarte dieser Farbe und darfst ihre Sau nicht selbst haben.'},
  {id:'R1',code:'R1',kind:'rule',title:'Wer spielt Trumpf aus?',text:'Gehörst du zur Spielerpartei und bist am Ausspiel, spielst du Trumpf. So ziehst du den Gegnern die Trümpfe raus. Bist du Gegenspieler, spielst du lieber eine Fehlfarbe aus.'},
  {id:'R1-memory',code:'R1',kind:'rule',title:'Trumpferschöpfung erkennen',text:'Ab Fortgeschritten kann die Spielerpartei auf Fehlfarbe wechseln, wenn bewiesen ist, dass nur noch das eigene Team Trumpf besitzt. Ausspiel einer Farbe, in der dein Partner frei ist oder hinten sitzt, kann dann helfen.'},
  {id:'R2',code:'R2',kind:'rule',title:'Schmieren',text:'Dein Partner hat den höchsten Trumpf gelegt, oder hinter dir sitzt kein Gegner mehr: Der Stich gehört sicher euch. Leg jetzt Punkte dazu, zum Beispiel ein Ass oder eine Zehn. Das nennt man Schmieren.'},
  {id:'R3',code:'R3',kind:'rule',title:'Suchen',text:'Du bist Gegenspieler und hast eine Karte der gerufenen Farbe? Dann spiel sie aus! So muss die gerufene Sau fallen, und ihr wisst, wer der Mitspieler ist.'},
  {id:'R4',code:'R4',kind:'rule',title:'Partner nicht überstechen',text:'Dein Partner gewinnt den Stich schon. Dann legst du keinen höheren Trumpf drauf, den brauchst du später noch. Die kontrollierten Ausnahmen sind R6 und R4a.'},
  {id:'R5',code:'R5',kind:'rule',title:'Einstechen',text:'Du bist in der angespielten Fehlfarbe frei? Dann darfst du mit Trumpf stechen und dir den Stich holen, außer dein Partner hat ihn schon sicher. Bei unter fünf Punkten kannst du einen einzelnen sehr hohen Trumpf schonen. Ab Fortgeschritten nimmst du den Stich trotzdem, wenn er den Sieg sichert, in den letzten beiden Stichen schneiderfrei macht oder Schwarz verhindert.'},
  {id:'R5-ace',code:'R5',kind:'rule',title:'Ein eigenes Ass aufheben',text:'Ein Ass einer noch nicht gespielten Fehlfarbe hebst du auf. Spielentscheidende Punkte zum Sieg haben Vorrang; Profi und Legende schmieren auch dann, wenn die Punkte den Gegner in den Schneider bringen. Mit Ass und Zehn derselben Farbe kannst du das Ass schmieren: Die Zehn übernimmt den späteren Stich. Die Rufsau bleibt geschützt.'},
  {id:'R6',code:'R6',kind:'rule',title:'Partner bewusst überstechen',text:'Dein Mitspieler direkt vor dir spielt den Schellen-Ober. Du hast Herz-Ober und Eichel-Unter, die direkten Nachbarn. Stich mit Herz-Ober drüber: Du spielst danach aus und dein Partner sitzt hinten. R6 gilt nur, wenn alle Karten an die Partnerkarte angrenzen. Der eindeutige Fall besteht aus genau den beiden Nachbarkarten; mit weiteren Karten wird R6 vorerst nicht angewendet.'},
  {id:'A4',code:'A4',kind:'rule',title:'Der Bremser',text:'Für ein Sauspiel brauchst du mit einem der drei höchsten Ober mindestens vier Trümpfe und zwei Ober/Unter. Ohne Bremser geht es mit sechs Trümpfen, oder mit fünf Trümpfen, wenn Schellen-Ober oder Eichel-Unter dabei ist. Eine Sau muss rufbar sein.'},
  {id:'A4-solo',code:'A4',kind:'rule',title:'Ein Solo ansagen',text:'Ein Farbsolo braucht mindestens sechs Trümpfe und mindestens zwei Ober. Höchstens eine gehaltene Fehlfarbe darf ohne Ass sein; freie Farben zählen nicht. Acht Trümpfe erlauben das Solo immer. Trumpf-Ass und Trumpf-Zehn stärken dein Blatt.'},
  {id:'A4-wenz',code:'A4',kind:'rule',title:'Farbwenz prüfen',text:'Farbwenz braucht mindestens fünf Trümpfe, zwei Unter und eine Trumpfschmier. Bei fünf Trümpfen soll einer der beiden höchsten Unter dabei sein, bei sechs einer der drei höchsten. Zwei Ausschlusskriterien schließen normalerweise Wenz, Geier oder Farbwenz aus. Wenz und Geier erlauben auch zwei beliebige Rangtrümpfe mit drei Fehlfarben-Assen oder zwei Fehlfarben-Assen und zwei freien Farben; höchstens zwei Farben dürfen frei sein. Beim Geier zählen Ober. Freie Farben sind keine gehaltenen Farben ohne Ass.'},
  {id:'A4-tout',code:'A4',kind:'rule',title:'Tout sicher ansagen',text:'Tout verlangt alle acht Stiche. Der Bot sagt es nur mit sicherer Trumpfkontrolle an. Eine einzelne blanke Fehlfarben-Sau ist nur an Position 1 als Ausnahme erlaubt. Ein nicht blankes Ass reicht nicht.'},
  {id:'A5',code:'A5',kind:'rule',title:'Spritzen mit starker Hand',text:'Gegen Sauspiel brauchst du mindestens fünf Trümpfe, einen Ober, insgesamt drei Ober/Unter und eine freie Fehlfarbe. Gegen Solo brauchst du mindestens fünf Trümpfe, einen der drei höchsten und insgesamt drei Ober/Unter. Im reinen Wenz/Geier spritzen Bots erst nach einem ersten Teamstich mit über 30 Augen, mit dem höchsten Trumpf oder zwei Trümpfen einschließlich eines der höchsten beiden.'},
  {id:'R4a',code:'R4a',kind:'rule',title:'Drüberstechen, um Trumpf zu ziehen',text:'Sitzt dein Partner direkt vor dir, darfst du ihn deutlich überstechen, um danach Trumpf zu ziehen und ihn hinten zu platzieren. Du brauchst viele Trümpfe und ausreichend hohe Reserven. Die konservative Bot-Einstellung verlangt standardmäßig vier verbleibende Trümpfe und mindestens einen weiteren hohen Trumpf; diese Grenzen sind einstellbar. Den einzigen hohen Trumpf hebst du auf. Ein Trumpf nur eine Stufe darüber ist allein für R6 gedacht.'},
  {id:'R6b',code:'R6b',kind:'rule',title:'Zwei sichere Trümpfe bewahren',text:'Geht der Stich sicher an den Gegner, behältst du zwei hohe Trümpfe und gibst eine Trumpfschmier nur ab, wenn beide hohen Trümpfe anschließend sicher stechen. Sonst opferst du einen unsicheren hohen Trumpf und behältst die Schmier.'},
  {id:'T1',code:'T1',kind:'tip',title:'Mim Unter gehst nie unter!',text:'Stechst du in eine Fehlfarbe ein und sitzt noch ein Gegner hinter dir, nimm lieber einen Unter als Trumpf-Ass oder Trumpf-Zehn. Wirst du überstochen, verliert dein Team weniger Punkte und der Gegner braucht einen hohen Trumpf.'},
  {id:'T1-points',code:'T1',kind:'tip',title:'Spielentscheidende Punkte holen',text:'Ab Profi hat die Punktlage Vorrang vor dem Unter-Tipp: Wenn ein sicherer höherer Trumpf dein Team zum Sieg, aus dem Schneider oder den Gegner in den Schneider bringt, nimm diesen Stich.'},
  {id:'T2',code:'T2',kind:'tip',title:'Mitspieler spielt hoch aus',text:'Als Mitspieler spielst du deinen höchsten Ober aus. Sitzt der Ansager hinten, darf auch einer der höchsten sechs Trümpfe genügen. Mit drei bis vier Trümpfen kannst du hohe und niedrige Trumpfrunden abwechseln, außer du kannst erneut den höchsten Trumpf spielen.'},
  {id:'T2-save',code:'T2',kind:'tip',title:'Trumpf zum Einstechen aufheben',text:'Hast du als Mitspieler nur noch einen niedrigen Unter und schwache Farbtrümpfe, hebe den Unter zum Einstechen auf. Spiele stattdessen zum Beispiel die Herz-7 aus.'},
  {id:'T3a',code:'T3a',kind:'tip',title:'Selbst frei in der Suchfarbe',text:'Willst du suchen, hast aber keine Karte der Ruffarbe, spiele eine andere Fehlfarbe an. So kann dein Partner an den Stich kommen und suchen. Ohne eigenen Trumpf ist die Farbwahl weniger wichtig.'},
  {id:'T3b',code:'T3b',kind:'tip',title:'Dem möglichen Partner das Suchen überlassen',text:'Bei Trumpfanspiel übernimmst du als Gegenspieler den Stich möglichst nicht, wenn ein möglicher Partner hinter dir stechen und danach suchen könnte. Dieser Tipp hat Vorrang vor dem Erzwingen weiterer Trumpfrunden.'},
  {id:'T3c',code:'T3c',kind:'tip',title:'Als Ansager wenig Punkte in die Suchfarbe',text:'Hat ein Gegenspieler früher eine andere Fehlfarbe ausgespielt, statt zu suchen, ist er vermutlich in der Ruffarbe frei. Wird jetzt gesucht und hast du mehrere Karten der Ruffarbe, lege die punktärmste. Das ist eine Vermutung, kein Beweis.'},
  {id:'T4',code:'T4',kind:'tip',title:'Mit der Suchfarbe hoch suchen',text:'Suche mit der punktereichsten Karte. Die Sau und mindestens eine weitere Rufkarte liegen bei der Spielerpartei. Hebe deine einzige volle Schmier für einen sicheren Teamstich auf; mit vier Rufkarten suche immer hoch, außer der Ansager hat bereits eine Rufkarte abgeschmissen.'},
  {id:'T4-color',code:'T4',kind:'tip',title:'Viele Karten einer Fehlfarbe',text:'Mit drei oder vier Karten einer angespielten Fehlfarbe und einem Gegner hinter dir gibst du eher wenige Punkte zu. Jemand könnte frei sein und einstechen. Ist der Gegner nachweislich trumpffrei, entfällt diese Sorge.'},
  {id:'T5',code:'T5',kind:'tip',title:'Vorsicht beim Ass-Schmieren',text:'Deine einzige volle Schmier hebst du für einen sicheren Teamstich auf. Ein Ass, das später selbst durchgehen würde, behältst du möglichst. Mehrere Asse und Zehnen erlauben mehr Risiko; Ass mit Zehn dahinter kannst du eher schmieren.'},
  {id:'T5-solo',code:'T5',kind:'tip',title:'Im Solo Asse schmieren',text:'Als Gegenspieler im Solo schmierst du ein Ass eher, wenn du viele weitere Karten dieser Farbe hältst, ein Gegner darin frei ist, die Farbe schon gelaufen ist, du die Zehn dahinter hast oder dein Team dadurch die gültige Sieggrenze erreicht.'},
  {id:'T6',code:'T6',kind:'tip',title:'Gleich starke Karten',text:'Benachbarte Karten wie Schellen-Unter und Herz-Ass haben gegenüber fremden Karten dieselbe Stichkraft. Macht der Partner den Stich, lege die punktereichere. Macht der Gegner den Stich oder übernimmst du selbst, lege die punktärmere.'},
  {id:'T7',code:'T7',kind:'tip',title:'Den sicheren Trumpf behalten',text:'Du hast Gras-Ober und einen weiteren Trumpf; Eichel-Ober ist im Stich. Kannst du den aktuellen Stich nicht holen, behalte Gras-Ober für einen späteren sicheren Stich, selbst wenn du dafür Herz-Ass abgibst.'},
  {id:'T7-sacrifice',code:'T7',kind:'tip',title:'Den unsicheren Ober opfern',text:'Du hast Herz-Ober und Herz-Zehn. Eichel-Ober liegt im Stich, Gras-Ober ist noch im Spiel. Kannst du den Stich nicht holen, lege Herz-Ober und bewahre Herz-Zehn zum Schmieren. Mit drei Trümpfen behältst du den hohen und gibst von den übrigen dem Gegner wenig, dem Partner viele Punkte.'},
  {id:'T7-pro',code:'T7',kind:'tip',title:'Jeder Punkt zählt',text:'Macht der Partner den Stich ohnehin, kann ein Punkt über Schneider entscheiden: Schellen-Ober bringt drei Punkte, Eichel-Unter zwei. Der Profi wägt diese Punkte gegen die künftige Stichkraft ab.'},
  {id:'T8',code:'T8',kind:'tip',title:'Punkte streuen',text:'Versuche insgesamt fünf bis zwölf Punkte in einen Stich zu legen. So machen sich Gegner weniger billig frei. Hast du nur zwei oder drei Karten mit mindestens vier Punkten, spare sie für sichere Stiche; spielentscheidende Punkte können ab Profi Vorrang haben.'},
  {id:'T9',code:'T9',kind:'tip',title:'Trumpffreie Gegenspieler erkennen',text:'Wenn beide Gegenspieler nachweislich trumpffrei sind, suchen Anfänger trotzdem immer. Amateur sucht in 75 %, Fortgeschritten in 50 %, Profi in 25 % und Legende in 0 % dieser Fälle. Sonst bleibt Suchen nach R3 Pflicht.'},
  {id:'T10',code:'T10',kind:'tip',title:'Viele Trumpfrunden',text:'Die Spielerpartei will möglichst viele Trumpfrunden und damit Trumpfhoheit erreichen. Als Gegenspieler kannst du einen Stich übernehmen, um zu suchen oder Fehlfarbe nachzuspielen. Einen eigenen Partner überstichst du nur gemäß R4a oder R6.'},
  {id:'T11',code:'T11',kind:'tip',title:'Vorsorglich frei machen',text:'Bei wenigen Punkten oder einem Partnerstich kannst du eine punktarme Einzelkarte einer noch nicht gespielten Fehlfarbe abwerfen. Dafür opferst du niemals Ass oder Zehn. Einen sicheren Stich mit mindestens zehn Punkten oder zum Sieg nimmst du; geht der Stich sicher an den Gegner, greift dieser Tipp nicht.'},
  {id:'T12',code:'T12',kind:'tip',title:'Die zwei höchsten Trümpfe',text:'Hast du die beiden höchsten Trümpfe, spiele bei einem Partner in der Mitte den höchsten, damit er schmieren kann. Sitzt er hinten oder spielst du allein, genügt der zweithöchste. Bei unbekanntem Partner kannst du den höchsten spielen.'},
  {id:'T12-hand',code:'T12',kind:'tip',title:'Trumpfausspiel nach Handstruktur',text:'Mit mindestens fünf Trümpfen und wenigen Obern kannst du niedrig ausspielen. Mit mindestens zwei Obern und insgesamt vier Ober/Unter spiele erst hoch, danach niedrig. Die zwei höchsten Trümpfe und die Partnerposition haben Vorrang.'},
];
export function lessonKinds(difficulty?: AiDifficulty): Lesson['kind'][] {
  return difficulty === 'beginner' ? ['rule'] : difficulty === 'amateur' ? ['rule','tip'] : difficulty === 'advanced' || difficulty === 'normal' ? ['tip'] : [];
}
export function randomSchafkopfLesson(difficulty: AiDifficulty, random: () => number = Math.random, view?: GameView): Lesson | null {
  const kinds = lessonKinds(difficulty);
  let choices = SCHAFKOPF_LESSONS.filter(lesson => kinds.includes(lesson.kind));
  if (view && !['play','trick','finished'].includes(view.phase)) {
    const declarations = choices.filter(lesson => lesson.code.startsWith('A') || lesson.code === 'ENGINE');
    if (declarations.length) choices = declarations;
  }
  if (!choices.length) return null;
  return choices[Math.min(choices.length-1,Math.floor(random()*choices.length))];
}
