import GameXpReward from "@/components/games/GameXpReward";
import { useState } from "react";
import { Anchor, BookOpen, Castle, ChevronRight, Crown, Handshake, Leaf, Route, Scale, Shield, Sparkles } from "lucide-react";
import type { Campaign, Command, District, House, Resource } from "../../../games/MedievalKingdoms/edravane/types.ts";
import type { Administration, Cargo, Covenant, ProjectKind, Reform } from "../../../games/MedievalKingdoms/edravane/agreementsTypes.ts";
import { ADMINISTRATION, COVENANTS, PROJECTS, REFORMS, SPECIALISATIONS, administrationPressure, cargoDescription, connectedHoldings, estateForecast, legacyScore, projectRemainder, projectTotals, realmDecisions } from "../../../games/MedievalKingdoms/edravane/agreements.ts";
import { campaignRound } from "../../../games/MedievalKingdoms/edravane/realm.ts";
import { RESOURCES, center, findPath } from "../../../games/MedievalKingdoms/edravane/world.ts";
import { HouseSigil } from "./HouseSigil.tsx";

type Props = { state: Campaign; house: House; active: boolean; onCommand: (c: Command) => void };
const name = (s: Campaign, id: string) => s.houses.find((h) => h.id === id)?.name ?? "Unknown house";
const empty = (): Cargo => ({ coins: 0, resources: {} });
const values = (c: Cargo) => c.coins + Object.values(c.resources).reduce((n, x) => n + x, 0);
function CargoEditor({ value, onChange, label }: { value: Cargo; onChange: (c: Cargo) => void; label: string }) {
  return <fieldset className="ed-cargo-editor"><legend>{label}</legend><label>Coins<input type="number" min="0" max="500" step="1" value={value.coins} onChange={(e) => onChange({ ...value, coins: Number(e.target.value) })} /></label>
    <details><summary>Goods · {cargoDescription({ ...value, coins: 0 })}</summary><div className="ed-cargo-goods">{RESOURCES.map((r) => <label key={r}>{r}<input type="number" min="0" max="200" step="1" value={value.resources[r] ?? 0} onChange={(e) => onChange({ ...value, resources: { ...value.resources, [r]: Number(e.target.value) } })} /></label>)}</div></details></fieldset>;
}
export function RealmAgenda({ state, house, onVisit }: { state: Campaign; house: House; onVisit: (tab: string, hex?: string) => void }) {
  const decisions = realmDecisions(state, house);
  return <section className="ed-agenda" aria-label="Decisions for this reign"><div className="ed-section-kicker"><Sparkles size={13} /><span>BEFORE YOU END YOUR TURN</span></div>{decisions.map((d) => <button key={d.id} className={`ed-decision ed-decision-${d.urgency}`} onClick={() => onVisit(d.tab, d.hex)}><span><strong>{d.title}</strong><small>{d.detail}</small></span><ChevronRight size={16} /></button>)}</section>;
}
export function AgreementsPanel({ state, house, active, onCommand }: Props) {
  const [partnerId, setPartner] = useState(""), [give, setGive] = useState<Cargo>({ coins: 0, resources: { grain: 20 } }), [take, setTake] = useState<Cargo>({ coins: 10, resources: {} });
  const [covenant, setCovenant] = useState<Covenant>("none"), [duration, setDuration] = useState(3);
  const partners = state.titles.map((t) => state.houses.find((h) => h.id === t.holder)!).filter((h) => h.id !== house.id && !state.wars.includes([h.nation, house.nation].sort().join("|")));
  const partner = partners.find((h) => h.id === partnerId) ?? partners[0];
  const compacts = state.agreements?.compacts.filter((c) => [c.from, c.to].includes(house.id)) ?? [];
  const unavailable = !active ? "Negotiate on your own turn." : !partner ? "Make peace to find a trading partner." : house.treasury < give.coins || RESOURCES.some((r) => house.stock[r] < (give.resources[r] ?? 0)) ? "Your first delivery exceeds your stores." : compacts.filter((c) => ["offered", "active"].includes(c.status)).length >= 6 ? "Resolve or finish an existing compact first." : "";
  return <section className="ed-agreements" aria-label="Realm agreements"><div className="ed-panel-title"><span className="ed-eyebrow">RESOURCES, RIGHTS & PROMISES</span><h2><Handshake size={23} /> Seal a compact</h2><p>Trade what your neighbours need. Every agreement requires their consent.</p></div>
    <div className="ed-specialisation"><Leaf size={18} /><div><strong>{SPECIALISATIONS[house.nation]?.resource} specialisation</strong><small>{SPECIALISATIONS[house.nation]?.detail} +15% output for your specialist resource.</small></div></div>
    <form onSubmit={(e) => { e.preventDefault(); if (partner && !unavailable) onCommand({ type: "offerCompact", house: partner.id, give, take, covenant, duration }); }}>
      <label>Other crown<select value={partner?.id ?? ""} onChange={(e) => setPartner(e.target.value)}>{partners.map((h) => <option key={h.id} value={h.id}>House {h.name}</option>)}</select></label>
      <div className="ed-cargo-pair"><CargoEditor label="You deliver each round" value={give} onChange={setGive} /><CargoEditor label="They deliver each round" value={take} onChange={setTake} /></div>
      <label>Political commitment<select value={covenant} onChange={(e) => setCovenant(e.target.value as Covenant)}>{Object.entries(COVENANTS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>
      <label>Delivery rounds<select value={duration} onChange={(e) => setDuration(Number(e.target.value))}>{[2, 3, 4, 5, 6, 7, 8].map((n) => <option key={n} value={n}>{n} deliveries</option>)}</select></label>
      <p className="ed-consequence">First exchange on acceptance; later exchanges on your turns. A shortage or war breaks the compact: −15 relations. Honouring all deliveries earns +8 relations. Political rights last through the final delivery round.</p>
      <button className="ed-primary" disabled={!!unavailable || (!values(give) && !values(take) && covenant === "none")}><Handshake size={15} />Send offer to {partner?.name ?? "a crown"}</button>{unavailable && <p className="ed-reason">{unavailable}</p>}
    </form>
    <h3>Your compact ledger</h3>{!compacts.length && <p className="ed-empty-note">No compacts yet. An exchange of grain, timber or iron can turn a neighbour into a partner.</p>}
    {[...compacts].reverse().map((c) => <article className={`ed-compact ed-compact-${c.status}`} key={c.id}><div className="ed-card-heading"><strong>{name(state, c.from)} ↔ {name(state, c.to)}</strong><span className="ed-status-seal">{c.status}</span></div><p>{cargoDescription(c.give)} <span aria-hidden="true">⇄</span> {cargoDescription(c.take)}</p><small>{COVENANTS[c.covenant]} · {c.delivered}/{c.duration} deliveries</small><p className="ed-reason">{c.reason}</p>
      {c.status === "offered" && c.to === house.id && <div className="ed-card-actions"><button disabled={!active} onClick={() => onCommand({ type: "answerCompact", compact: c.id, accept: true })}>Accept and exchange</button><button disabled={!active} onClick={() => onCommand({ type: "answerCompact", compact: c.id, accept: false })}>Decline</button><button disabled={!active} onClick={() => { setPartner(c.from); setGive(structuredClone(c.take)); setTake(structuredClone(c.give)); setCovenant(c.covenant); setDuration(c.duration); onCommand({ type: "answerCompact", compact: c.id, accept: false }); }}>Prepare counteroffer</button></div>}
      {(c.status === "active" || c.status === "offered" && c.from === house.id) && <button disabled={!active} onClick={() => onCommand({ type: "breakCompact", compact: c.id })}>{c.status === "active" ? "Withdraw · −15 relations" : "Withdraw unaccepted offer"}</button>}
    </article>)}
  </section>;
}
function FundProject({ state, house, projectId, active, onCommand }: Props & { projectId: string }) {
  const p = state.agreements!.projects.find((p) => p.id === projectId)!, left = projectRemainder(p);
  const [cargo, setCargo] = useState<Cargo>(empty);
  const smallShare = (): Cargo => ({ coins: Math.min(left.coins, 30, Math.floor(house.treasury)), resources: Object.fromEntries(RESOURCES.map((r) => [r, Math.min(left.resources[r] ?? 0, 20, Math.floor(house.stock[r]))])) });
  const remainingAffordable = left.coins <= house.treasury && RESOURCES.every((r) => (left.resources[r] ?? 0) <= house.stock[r]);
  return <div className="ed-project-funding"><p>Still needed: <strong>{cargoDescription(left)}</strong></p><div className="ed-card-actions"><button disabled={!active} onClick={() => setCargo(smallShare())}>Prepare a share</button><button disabled={!active || !remainingAffordable} onClick={() => setCargo(left)}>Prepare remaining cost</button></div><CargoEditor label="Your contribution" value={cargo} onChange={setCargo} /><button disabled={!active || !values(cargo)} onClick={() => onCommand({ type: "fundProject", project: p.id, cargo })}>Contribute {cargoDescription(cargo)}</button></div>;
}
export function ProjectsPanel({ state, house, active, onCommand, selected, onHex }: Props & { selected?: District; onHex: (d: District) => void }) {
  const [kind, setKind] = useState<ProjectKind>("granary"), [destination, setDestination] = useState("");
  const ports = state.districts.filter((d) => d.port && d.owner && d.id !== selected?.id);
  const dest = ports.find((d) => d.id === destination) ?? ports[0];
  const validEstate = selected?.owner === house.id && !selected.occupation;
  const reason = !active ? "Found projects on your own turn." : !validEstate ? "Select one of your unoccupied estates on the map." : kind === "bridge" && selected.biome !== "river" ? "Select a river estate for a bridge." : kind === "sea-lane" && (!selected.port || !dest) ? "Select your port and a destination port." : "";
  return <section aria-label="Shared projects"><div className="ed-panel-title"><span className="ed-eyebrow">BUILD ACROSS BORDERS</span><h2><Castle size={23} /> Common works</h2><p>Pool resources. Share the benefits. The founder funds upkeep and controls access.</p></div><label>Project<select value={kind} onChange={(e) => setKind(e.target.value as ProjectKind)}>{Object.entries(PROJECTS).map(([key, p]) => <option key={key} value={key}>{p.title}</option>)}</select></label>
    <p className="ed-selected-location">{selected?.name ?? "Select an estate on the map"}</p>{kind === "sea-lane" && <label>Destination port<select value={dest?.id ?? ""} onChange={(e) => setDestination(e.target.value)}>{ports.map((d) => <option key={d.id} value={d.id}>{d.name} · {name(state, d.owner!)}</option>)}</select></label>}
    <p>{PROJECTS[kind].detail}</p><p className="ed-consequence">Construction: {cargoDescription(PROJECTS[kind].cost)}. Upkeep: {PROJECTS[kind].upkeep} coins on the founder's turns. Closing access costs 12 relations with every other contributor. Funding is refunded if an unfinished project is cancelled.</p>
    <button className="ed-primary" disabled={!!reason} onClick={() => selected && onCommand({ type: "foundProject", kind, hex: selected.id, destination: kind === "sea-lane" ? dest?.id : undefined })}>Invite contributions</button>{reason && <p className="ed-reason">{reason}</p>}
    <h3>Works of the eight crowns</h3>{!state.agreements?.projects.length && <p className="ed-empty-note">The first shared project could become the foundation of a lasting alliance.</p>}
    {state.agreements?.projects.filter((p) => p.status !== "cancelled").map((p) => { const total = projectTotals(p), cost = PROJECTS[p.kind].cost, progress = Math.round(values(total) / values(cost) * 100); return <article className="ed-project-card" key={p.id}><div className="ed-card-heading"><strong>{PROJECTS[p.kind].title}</strong><span className="ed-status-seal">{p.status === "complete" ? p.open && p.maintained ? "open" : "suspended" : `${progress}% funded`}</span></div><button className="ed-house-link" onClick={() => onHex(state.districts.find((d) => d.id === p.hex)!)}>{state.districts.find((d) => d.id === p.hex)?.name}</button><small>Founded by {name(state, p.owner)} · {PROJECTS[p.kind].upkeep} coins upkeep</small><progress value={progress} max="100" aria-label={`${PROJECTS[p.kind].title} funding`} /><p>{PROJECTS[p.kind].detail}</p>
      <div className="ed-contributors">{Object.entries(p.contributions).map(([id, cargo]) => <small key={id}>{name(state, id)}: {cargoDescription(cargo)}</small>)}</div>
      {p.status === "funding" && <FundProject state={state} house={house} projectId={p.id} active={active} onCommand={onCommand} />}
      {p.owner === house.id && <button disabled={!active} onClick={() => onCommand(p.status === "complete" ? { type: "projectAccess", project: p.id, open: !p.open } : { type: "cancelProject", project: p.id })}>{p.status === "complete" ? p.open ? "Close access · diplomatic cost" : "Reopen access" : "Cancel and refund contributions"}</button>}
    </article>; })}
  </section>;
}
export function InterestsPanel({ state, house, active, onCommand }: Props) {
  const d = state.agreements?.domestic[house.id], pressure = administrationPressure(state, house);
  if (!d) return null;
  const interests = [{ key: "rural" as const, title: "Rural communities", icon: Leaf, detail: "Need food and workers in the fields. Mobilisation lowers approval and harvest output." }, { key: "merchants" as const, title: "Merchant guilds", icon: Scale, detail: "Need affordable routes and market privileges. Royal tolls reduce approval." }, { key: "scholars" as const, title: "Schools and healers", icon: BookOpen, detail: "Need sustained patronage. Learning increases legitimacy but needs ongoing funding." }];
  return <section aria-label="Domestic interests"><div className="ed-panel-title"><span className="ed-eyebrow">THE PEOPLE BEHIND THE CROWN</span><h2>Consent to govern</h2><p>A prosperous kingdom needs more than obedient nobles.</p></div>{interests.map((i) => <article className="ed-interest-card" key={i.key}><div><i.icon size={19} /><strong>{i.title}</strong><b className={d.approval[i.key] < 40 ? "ed-danger" : ""}>{d.approval[i.key]}%</b></div><progress value={d.approval[i.key]} max="100" aria-label={`${i.title} approval`} /><small>{i.detail}</small></article>)}
    <p className="ed-consequence">Levy burden: {d.levyBurden} soldiers; recovers by 100 each own turn. Farm output falls by up to 35%. Approval below 35: rural communities increase unrest, merchants add 20% route costs, and scholars reduce legitimacy by 1 each own turn. Food shortages cost 4 rural approval each own turn.</p>
    <div className={`ed-administration-meter ${pressure.excess ? "ed-danger" : ""}`}><Shield size={18} /><span>Administration <strong>{pressure.used} / {pressure.capacity}</strong><small>{pressure.excess ? `Overstretch: +${pressure.excess} unrest per estate each own turn` : "Your administration can support its current holdings"}</small></span></div>
    <h3>Choose a governing charter</h3>{Object.entries(REFORMS).map(([key, reform]) => <article className="ed-reform-card" key={key}><strong>{reform.title}</strong><p>{reform.detail}</p><button disabled={!active || d.reform === key || d.lastReform === campaignRound(state) || house.treasury < reform.cost} onClick={() => onCommand({ type: "reform", reform: key as Reform })}>{d.reform === key ? "Current charter" : `Enact · ${reform.cost} coins`}</button></article>)}
  </section>;
}
export function IntegrationPanel({ state, house, active, onCommand, district }: Props & { district: District }) {
  const [policy, setPolicy] = useState<Administration>("local-rule"), [governor, setGovernor] = useState("");
  const governors = state.houses.filter((h) => h.liege === house.id && !h.rebellion && h.loyalty >= 55), chosen = governors.find((h) => h.id === governor) ?? governors[0];
  const recharter = district.owner === house.id && !!district.integration && !district.occupation;
  if (!recharter && (district.occupation !== house.id || district.owner === house.id)) return null;
  const held = recharter ? 3 : state.tick - (district.occupiedAt ?? state.tick);
  return <section className="ed-integration"><span className="ed-eyebrow">AFTER THE CONQUEST</span><h3>How will you govern?</h3><label>Administration<select value={policy} onChange={(e) => setPolicy(e.target.value as Administration)}>{Object.entries(ADMINISTRATION).map(([key, p]) => <option key={key} value={key}>{p.title}</option>)}</select></label>{policy === "governor" && <label>Appoint a loyal vassal<select value={chosen?.id ?? ""} onChange={(e) => setGovernor(e.target.value)}>{governors.map((h) => <option key={h.id} value={h.id}>{h.name} · {h.loyalty}% loyalty</option>)}</select></label>}
    {recharter && <p>Current charter: {ADMINISTRATION[district.integration!.policy].title}. Administered by House {name(state, district.integration!.administrator)}.</p>}<p className="ed-consequence">{ADMINISTRATION[policy].detail} Costs 50 coins. {recharter ? "Autonomy also removes 15 existing unrest and frees administration capacity." : "Your host must remain here."}</p><button disabled={!active || held < 3 || house.treasury < 50 || policy === "governor" && !chosen || recharter && district.integration?.policy === policy} onClick={() => onCommand({ type: "integrate", hex: district.id, policy, administrator: chosen?.id })}>{recharter ? "Revise estate charter" : "Grant estate charter"}{held < 3 ? ` · hold ${3 - held} more ticks` : ""}</button></section>;
}
export function EstateDevelopment({ state, house, active, onCommand, district }: Props & { district: District }) {
  if (district.owner !== house.id || district.occupation) return null;
  return <section className="ed-development"><span className="ed-eyebrow">A LIVING ESTATE</span><h3>Invest in {district.name}</h3><p>Development {district.development ?? 0}/3 · forecast {estateForecast(state, house, district)} {district.resource} per economy tick.</p><div className="ed-card-actions">{district.farm && <button disabled={!active || (district.development ?? 0) >= 3 || house.treasury < 60 || house.stock.timber < 20} onClick={() => onCommand({ type: "develop", hex: district.id, building: "farm" })}>Improve farms · 60 coins, 20 timber</button>}{!district.city && <button disabled={!active || (district.development ?? 0) >= 3 || house.treasury < 60 || house.stock.timber < 20} onClick={() => onCommand({ type: "develop", hex: district.id, building: "market" })}>Build market · 60 coins, 20 timber</button>}{district.city === "town" && <button disabled={!active || (district.development ?? 0) >= 3 || house.treasury < 150 || house.stock.timber < 40 || house.stock.iron < 20} onClick={() => onCommand({ type: "develop", hex: district.id, building: "town" })}>Grow city · 150 coins, 40 timber, 20 iron</button>}</div><small>Each development level adds 10% resource output and +5 rural or merchant approval.</small></section>;
}
type Tie = { house: House; kinds: string[]; details: string[] };
export function relationshipTies(s: Campaign, focus: House): Tie[] {
  return s.houses.filter((h) => h.id !== focus.id).flatMap((other) => {
    const kinds: string[] = [], details: string[] = [];
    if (other.liege === focus.id || focus.liege === other.id) { kinds.push("obligation"); details.push(`${other.obligation} pledged soldiers; ${other.loyalty}% loyalty`); }
    const marriages = focus.family.filter((p) => p.alive && other.family.some((q) => q.alive && q.id === p.spouse));
    if (marriages.length) { kinds.push("marriage"); details.push(`${marriages.length} living marriage tie${marriages.length === 1 ? "" : "s"}`); }
    const compacts = s.agreements?.compacts.filter((c) => c.status === "active" && [c.from, c.to].includes(focus.id) && [c.from, c.to].includes(other.id)) ?? [];
    if (compacts.length) { kinds.push("compact"); details.push(...compacts.map((c) => `${COVENANTS[c.covenant]}: ${cargoDescription(c.give)} ⇄ ${cargoDescription(c.take)}`)); }
    const trade = s.routes.filter((r) => r.house === focus.id && s.districts.find((d) => d.id === r.to)?.owner === other.id || r.house === other.id && s.districts.find((d) => d.id === r.to)?.owner === focus.id);
    if (trade.length) { kinds.push("trade"); details.push(`${trade.length} route${trade.length === 1 ? "" : "s"}: ${[...new Set(trade.map((r) => r.resource))].join(", ")}`); }
    if (s.wars.includes([focus.nation, other.nation].sort().join("|")) && s.titles.some((t) => t.holder === other.id)) { kinds.push("rivalry"); details.push("At war; access and compacts are suspended"); }
    if (!kinds.length && (focus.relations[other.id] ?? 0) < -10) { kinds.push("rivalry"); details.push(`Relations ${focus.relations[other.id]}`); }
    return kinds.length ? [{ house: other, kinds, details }] : [];
  });
}
export function RelationsPanel({ state, house, focus, onHouse, onAgreements }: { state: Campaign; house: House; focus: House; onHouse: (h: House) => void; onAgreements: () => void }) {
  const ties = relationshipTies(state, focus), memories = state.agreements?.memories.filter((m) => m.house === focus.id || m.other === focus.id) ?? [];
  return <section className="ed-relations" aria-label="House relationships"><div className="ed-panel-title"><span className="ed-eyebrow">THE THREADS OF POWER</span><h2>House {focus.name}</h2><p>Marriage, commerce and obligations shape this house's position. Select a connection to inspect its terms.</p></div><button onClick={onAgreements}><Handshake size={15} />Open your agreements</button><div className="ed-relationship-list">{ties.map((t) => <details key={t.house.id} className={`ed-relationship-tie ed-tie-${t.kinds[0]}`}><summary><HouseSigil house={t.house} size={24} /><span>{t.house.name}<small>{t.kinds.join(" · ")}</small></span><b>{focus.relations[t.house.id] ?? 0}</b></summary>{t.details.map((d) => <p key={d}>{d}</p>)}<button onClick={() => onHouse(t.house)}>Inspect House {t.house.name}</button></details>)}</div>{!ties.length && <p className="ed-empty-note">No observed connections. Your own private agreements appear here; other crowns' private contracts remain hidden.</p>}
    <h3>Promises remembered</h3>{memories.slice(0, 12).map((m) => <article className="ed-memory" key={m.id}><span className={`ed-memory-seal ed-memory-${m.kind}`}>{m.kind === "broken" ? "!" : "✓"}</span><div><strong>{m.detail}</strong><small>Round {m.round} · remembered by {name(state, m.house)} · {m.effect > 0 ? "+" : ""}{m.effect} relations</small></div></article>)}{!memories.length && <p className="ed-empty-note">Honoured deliveries, shared works and broken promises leave a lasting record.</p>}
    {focus.id !== house.id && <small>Private memories are visible only to the houses involved.</small>}
  </section>;
}
export function CampaignLegacy({ state, house, active, onCommand }: Props) {
  const c = state.agreements?.campaign, score = c?.result ? c.scores[house.id] ?? legacyScore(state, house) : legacyScore(state, house);
  const connected = connectedHoldings(state, house), landmarks = state.agreements?.landmarks.filter((l) => connected.connected.has(l.hex)) ?? [];
  const goals = [{ key: "dynasty" as const, title: "A lasting dynasty", detail: "Recognised heir (6), a succession (8), loyal vassals (6), legitimacy at least 70 (5).", icon: Crown }, { key: "prosperity" as const, title: "A prosperous realm", detail: "Working routes (8), open shared projects (8), estate development (5), food and cash reserves (4).", icon: Leaf }, { key: "diplomacy" as const, title: "A respected voice", detail: "Distinct compact partners (12), fulfilled compacts (8), a joint project (5); broken promises lose 3 each.", icon: Handshake }, { key: "defence" as const, title: "A secure frontier", detail: "Connected strategic landmarks (9), low unrest (6), secure home capital (6), connected holdings (4).", icon: Shield }];
  return <section className="ed-legacy" aria-label="Campaign objectives"><div className="ed-panel-title"><span className="ed-eyebrow">BUILD A REALM YOUR HEIRS CAN KEEP</span><h2>{c?.result ? "The council's verdict" : "Your legacy"}</h2><p>{c?.kind === "council" ? `A ${c.length}-round chronicle. ${Math.max(0, c.startRound + c.length - campaignRound(state))} rounds remain. A succession council convenes midway.` : "An open chronicle: build, trade and govern across generations."}</p></div><div className="ed-legacy-total"><strong>{score.total}</strong><span>/ 100 legacy</span></div>{goals.map((g) => <article className="ed-goal" key={g.key}><div><g.icon size={18} /><strong>{g.title}</strong><b>{score[g.key]} / 25</b></div><progress max="25" value={score[g.key]} aria-label={g.title} /><small>{g.detail}</small></article>)}
    <p className="ed-consequence">{connected.connected.size}/{connected.total} holdings connected by land · {landmarks.length} connected landmarks. Pass castles gain 10% defence. Shared bridges improve local output; protected ports support trade.</p>
    {c?.result && <><GameXpReward /><h3>{c.result.winners.map((id) => name(state, id)).join(" & ")} {c.result.winners.length > 1 ? "share the victory" : "wins the chronicle"}</h3><table className="ed-legacy-ranking"><thead><tr><th>House</th><th>Dynasty</th><th>Wealth</th><th>Diplomacy</th><th>Defence</th><th>Total</th></tr></thead><tbody>{Object.entries(c.scores).sort(([, x], [, y]) => y.total - x.total).map(([id, s]) => <tr key={id}><th>{name(state, id)}</th><td>{s.dynasty}</td><td>{s.prosperity}</td><td>{s.diplomacy}</td><td>{s.defence}</td><td>{s.total}</td></tr>)}</tbody></table>{state.mode === "single" && <button disabled={!active} onClick={() => onCommand({ type: "continueSandbox" })}>Continue this realm as a sandbox</button>}</>}
  </section>;
}
export function RelationshipLayer({ state, focus, onHouse }: { state: Campaign; focus: House; onHouse: (h: House) => void }) {
  const seat = (h: House) => state.districts.find((d) => d.owner === h.id && d.seat === "capital") ?? state.districts.find((d) => d.owner === h.id);
  const origin = seat(focus); if (!origin) return null;
  const [x, y] = center(origin);
  return <g className="ed-relationship-layer">{relationshipTies(state, focus).map((t) => { const dest = seat(t.house); if (!dest) return null; const [dx, dy] = center(dest), colour = t.kinds.includes("rivalry") ? "#ee9985" : t.kinds.includes("marriage") ? "#d3aff1" : t.kinds.includes("compact") ? "#85d9c4" : "#e5c684";
    return <g key={t.house.id} onClick={(e) => { e.stopPropagation(); onHouse(t.house); }}><title>{focus.name} ↔ {t.house.name}: {t.details.join("; ")}</title><path d={`M${x} ${y} Q${(x + dx) / 2} ${(y + dy) / 2 - 35} ${dx} ${dy}`} fill="none" stroke="transparent" strokeWidth="14" /><path d={`M${x} ${y} Q${(x + dx) / 2} ${(y + dy) / 2 - 35} ${dx} ${dy}`} fill="none" stroke={colour} strokeWidth="2" strokeDasharray={t.kinds.includes("rivalry") ? "4 3" : undefined} pointerEvents="none" /><circle cx={dx} cy={dy} r="5" fill={colour} stroke="#18352c" /><g role="button" tabIndex={0} aria-label={`Inspect ${t.house.name}: ${t.kinds.join(", ")}`} onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); e.stopPropagation(); onHouse(t.house); } }}><rect x={(x + dx) / 2 - 30} y={(y + dy) / 2 - 29} width="60" height="17" rx="3" fill="#18352c" fillOpacity=".85" stroke={colour} strokeWidth=".4" /><text x={(x + dx) / 2} y={(y + dy) / 2 - 18} textAnchor="middle" fontSize="8" fill={colour} pointerEvents="none">{t.kinds[0]}</text></g></g>;
  })}</g>;
}
export function LandmarkLayer({ state, onHex, detailed }: { state: Campaign; onHex: (d: District) => void; detailed: boolean }) {
  return <g className="ed-landmarks">{state.agreements?.landmarks.map((l) => { const d = state.districts.find((d) => d.id === l.hex)!; const [x, y] = center(d); return <g key={l.hex} transform={`translate(${x + 13} ${y - 13})`} role="button" tabIndex={0} aria-label={`Strategic ${l.kind} at ${d.name}`} onClick={() => onHex(d)} onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); onHex(d); } }}><title>{l.kind}: {d.name}. Connect this landmark to your capital for defence objectives.</title><circle r="5" fill="#183b33" stroke="#f2d38c" strokeWidth="1" /><path d={l.kind === "pass" ? "M-3 2L0-3 3 2Z" : l.kind === "harbour" ? "M0-3V3M-3 0Q0 5 3 0M-2-2H2" : "M-3 2V-1Q0-4 3-1V2M-3 0H3"} stroke="#f2d38c" fill="none" strokeWidth=".7" />{detailed && <text x="0" y="10" textAnchor="middle" fontSize="6" fill="#fff0ca" stroke="#183b33" strokeWidth="2" paintOrder="stroke">{l.kind}</text>}</g>; })}
    {state.agreements?.projects.filter((p) => p.status !== "cancelled").map((p) => { const d = state.districts.find((d) => d.id === p.hex)!; const [x, y] = center(d); const destination = state.districts.find((d) => d.id === p.destination); const path = destination ? findPath(state.districts, d.id, destination.id, true) : [];
      return <g key={p.id} className="ed-project-map-marker" onClick={() => onHex(d)}>{p.kind === "sea-lane" && p.status === "complete" && <polyline points={[p.hex, ...path].map((id) => center(state.districts.find((d) => d.id === id)!).join(",")).join(" ")} stroke={p.open && p.maintained ? "#85d9c4" : "#ee9985"} fill="none" strokeWidth="1.6" strokeDasharray="3 4" pointerEvents="none" />}<rect x={x - 17} y={y + 10} width="10" height="10" rx="2" fill={p.status === "funding" ? "#795c2f" : p.open && p.maintained ? "#29684f" : "#733d34"} stroke="#e8cb85" /><text x={x - 12} y={y + 18} fontSize="8" textAnchor="middle" fill="#fff0ca">{p.status === "funding" ? "+" : "✓"}</text><title>{PROJECTS[p.kind].title}: {p.status}; {Object.keys(p.contributions).length} contributors</title></g>;
    })}</g>;
}
export function MapScaleLegend({ zoom }: { zoom: number }) {
  return <span className="ed-map-scale-legend"><Route size={13} />{zoom < 1.6 ? "World · crowns, connections & crossings" : zoom < 2.6 ? "Region · houses, production & hosts" : "Estate · buildings, charters & development"}</span>;
}
export function ResourceDependency({ state, house }: { state: Campaign; house: House }) {
  const needs = RESOURCES.filter((r) => house.stock[r] < (r === "grain" ? 100 : 25));
  return <div className="ed-dependencies"><strong>{needs.length ? "Imports worth negotiating" : "Your reserves are healthy"}</strong><small>{needs.length ? needs.join(" · ") : "Invest surplus goods in agreements or shared infrastructure."}</small><div>{needs.map((r: Resource) => <span key={r}>{r}: {Math.floor(house.stock[r])} · {state.prices[r]} coins</span>)}</div><small>{SPECIALISATIONS[house.nation]?.detail}</small></div>;
}
export const PROJECT_ICONS = { bridge: Route, granary: Castle, "sea-lane": Anchor };
