import { useArcadeControls } from './useArcadeControls.ts';
import { COLORS } from '../../../../games/party/config.ts';
import { MAZE_SIZE, type MazeView } from '../../../../games/party/minigames/arcadeAdditions/maze.ts';
import { CharacterFace } from '../CharacterFace.tsx';
import { DirectionPad, HoldButton } from './ArcadeControls.tsx';
import type { MinigameViewProps } from './views.ts';
function MazeFloor({ cells }: { cells: number[] }) { return <><rect width={MAZE_SIZE} height={MAZE_SIZE} fill="#1c1832"/>{cells.map((wall, n) => wall ? <g key={n}><rect x={n % MAZE_SIZE} y={Math.floor(n / MAZE_SIZE)} width="1" height="1" fill={(n % 11) < 3 ? '#484260' : '#3e3955'}/><path d={`M${n % MAZE_SIZE} ${Math.floor(n / MAZE_SIZE) + .05}h1`} stroke="#746985" strokeWidth=".05"/></g> : <rect key={n} x={n % MAZE_SIZE + .05} y={Math.floor(n / MAZE_SIZE) + .05} width=".9" height=".9" rx=".05" fill={n % 17 === 0 ? '#4b3848' : '#29233d'}/>)}{[[1.5, 1.5], [33.5, 1.5], [33.5, 33.5], [17.5, 17.5]].map(([x, y], i) => <g key={i}><circle cx={x} cy={y} r=".32" fill={['#76d8cd', '#d7be83', '#bda4eb', '#ed998b'][i]} opacity=".4"/><text x={x} y={y + .1} textAnchor="middle" fontSize=".36" fill="#fff4c5">{['✦', '◆', '●', '♉'][i]}</text></g>)}</>; }
export default function MinotaurMazeScreen(props: MinigameViewProps) {
  const { minigame, match, playerId, now, online } = props, s = minigame.state as MazeView, me = s.players[playerId], roster = s.roster[playerId], hunter = s.minotaurId === playerId;
  const active = online && !!me && me.hp > 0 && now >= s.startedAt && now < s.endsAt && !s.winners;
  const { change } = useArcadeControls(active, props.sendInput, me);
  const reveal = now < s.revealUntil, left = Math.max(0, Math.ceil((s.endsAt - now) / 1000)), x = Math.max(0, Math.min(MAZE_SIZE - 13, (me?.x ?? 17.5) - 6.5)), y = Math.max(0, Math.min(MAZE_SIZE - 13, (me?.y ?? 17.5) - 6.5));
  return <div className="pp-new-game pp-maze-game"><header className="pp-new-header"><div><span className="pp-eyebrow">{hunter ? 'YOU ARE THE MINOTAUR' : roster?.hp === 0 ? 'ELIMINATED · CHEER FOR YOUR TEAM' : 'RUNNER · SURVIVE THE LABYRINTH'}</span><h2>Minotaur’s Labyrinth</h2></div><strong className="pp-new-timer">{Math.floor(left / 60)}:{String(left % 60).padStart(2, '0')}<small>REMAINING</small></strong></header>
    <div className="pp-new-standings">{match.players.filter((p) => s.roster[p.id]).map((p) => <span key={p.id} className={p.id === playerId ? 'me' : ''} style={{ borderColor: p.id === s.minotaurId ? '#f79d80' : COLORS[p.avatarId] }}><b>{p.name}</b><strong>{p.id === s.minotaurId ? '♉ Hunter' : s.roster[p.id].hp ? '♥'.repeat(s.roster[p.id].hp) : 'Out'}</strong></span>)}</div>
    <div className="pp-maze-stage"><svg className="pp-new-arena" viewBox={`${x} ${y} 13 13`} role="img" aria-label="Your nearby maze corridors"><MazeFloor cells={s.cells}/>
      {Object.entries(s.players).filter(([, p]) => p.hp > 0).map(([id, p]) => { const player = match.players.find((q) => q.id === id)!; const monster = id === s.minotaurId; return <g key={id} transform={`translate(${p.x} ${p.y})`}>
        <circle r={monster ? '.42' : '.3'} fill={monster ? '#cd6f54' : COLORS[player.avatarId]} stroke={id === playerId ? '#fff0c2' : '#18132a'} strokeWidth=".06"/>
        {monster ? <><path d="M-.25 -.12q-.35 -.25 -.2 -.45q.1 .25 .32 .23M.25 -.12q.35 -.25 .2 -.45q-.1 .25 -.32 .23" fill="#f9e4b9"/><ellipse cy=".08" rx=".25" ry=".17" fill="#713d36"/><circle cx="-.13" cy="-.1" r=".045" fill="#ffe295"/><circle cx=".13" cy="-.1" r=".045" fill="#ffe295"/></> : <svg x="-.22" y="-.31" width=".44" height=".5" viewBox="0 0 64 72"><CharacterFace avatarId={player.avatarId}/></svg>}
        {p.boostUntil > now && <circle r=".45" fill="none" stroke="#8ffff0" strokeWidth=".07" strokeDasharray=".1 .1"/>}
        {monster && s.attackEndsAt > now && <path d={`M0 0L${p.facingX * 1.3 - p.facingY * .7} ${p.facingY * 1.3 + p.facingX * .7}Q${p.facingX * 1.6} ${p.facingY * 1.6} ${p.facingX * 1.3 + p.facingY * .7} ${p.facingY * 1.3 - p.facingX * .7}Z`} fill="#ffad7355" stroke="#ffd4a3" strokeWidth=".04"/>}
        <text y="-.58" textAnchor="middle" fontSize=".23" fill="#fff2de" stroke="#191229" strokeWidth=".05" paintOrder="stroke">{player.name}</text>
      </g>; })}</svg>
      <aside className={'pp-maze-map' + (reveal ? ' revealing' : '')}><span>{reveal ? 'LOCATIONS REVEALED' : 'LABYRINTH MAP'}</span><svg viewBox={`0 0 ${MAZE_SIZE} ${MAZE_SIZE}`} role="img" aria-label="Maze map showing your position and currently visible players"><rect width={MAZE_SIZE} height={MAZE_SIZE} fill="#100f23"/>{s.cells.flatMap((wall, n) => wall ? [] : [<rect key={n} x={n % MAZE_SIZE} y={Math.floor(n / MAZE_SIZE)} width="1" height="1" fill="#5b5069"/>])}{Object.entries(s.players).filter(([, p]) => p.hp > 0).map(([id, p]) => <circle key={id} cx={p.x} cy={p.y} r={id === playerId ? '.85' : '.65'} fill={id === s.minotaurId ? '#ff9e7f' : COLORS[match.players.find((q) => q.id === id)!.avatarId]} stroke={id === playerId ? 'white' : 'none'} strokeWidth=".3"/>)}</svg><small>{reveal ? `${Math.ceil((s.revealUntil - now) / 1000)} seconds` : `${Math.max(0, Math.ceil((s.nextRevealAt - now) / 1000))}s to next pulse`}</small></aside>
    </div>
    <p className="pp-new-status" role="status">{s.winners ? `${s.winners} win!` : roster?.hp === 0 ? 'Your teammates can still survive. Locations appear during pulses.' : me?.boostUntil && me.boostUntil > now ? 'ESCAPE BOOST +50% · PROTECTED · EVERYONE REVEALED' : hunter ? 'Follow sightings. Face a runner, then Attack.' : 'Walls hide you. Find a loop and keep an escape route.'}</p>
    <div className="pp-new-controls"><DirectionPad active={active} change={change}/>{hunter && <HoldButton active={active} controlKey="Space" label={me && me.nextActionAt > now ? `Attack · ${((me.nextActionAt - now) / 1000).toFixed(1)}s` : 'Attack'} name="Minotaur attack" change={change}/>}</div><small className="pp-new-help">WASD / arrows to move · Minotaur: Space to attack · two hits eliminate a runner{!online ? ' · Reconnecting…' : ''}</small>
  </div>;
}
