import { useArcadeControls } from './useArcadeControls.ts';
import { COLORS } from '../../../../games/party/config.ts';
import { minigameRegistry } from '../../../../games/party/minigames/index.ts';
import { DISC_WALLS, FUSE_WALLS, GRAVITY_WALLS, type FuseState, type GravityState, type RicochetState } from '../../../../games/party/minigames/arcadeAdditions/duels.ts';
import { paintWalls, PAINT_SIZE, type ColorState } from '../../../../games/party/minigames/arcadeAdditions/colorClash.ts';
import type { ArcadeState, Wall } from '../../../../games/party/minigames/arcadeAdditions/common.ts';
import { CharacterFace } from '../CharacterFace.tsx';
import { DirectionPad, HoldButton } from './ArcadeControls.tsx';
import type { MinigameViewProps } from './views.ts';

function Obstacles({ walls }: { walls: Wall[] }) { return <>{walls.map((w, i) => <g key={i}><rect x={w.x + .8} y={w.y + 1} width={w.w} height={w.h} rx="1.6" fill="#060e1a"/><rect x={w.x} y={w.y} width={w.w} height={w.h} rx="1.6" fill="#344363" stroke="#8397bc" strokeWidth=".6"/><path d={`M${w.x + 1} ${w.y + 2}h${w.w - 2}`} stroke="#b1c5e5" strokeWidth=".7"/></g>)}</>; }
function Pawns({ state, props }: { state: ArcadeState; props: MinigameViewProps }) {
  return <>{props.match.players.map((p) => { const pawn = state.players[p.id]; if (!pawn) return null; return <g key={p.id} transform={`translate(${pawn.x} ${pawn.y})`}><ellipse cy="2.5" rx="3.5" ry="1.5" fill="#030717" opacity=".6"/><circle r="3.3" fill={`${COLORS[p.avatarId]}33`} stroke={COLORS[p.avatarId]} strokeWidth={p.id === props.playerId ? '.9' : '.5'}/><svg x="-2.6" y="-3.5" width="5.2" height="5.8" viewBox="0 0 64 72"><CharacterFace avatarId={p.avatarId}/></svg><text x={Math.max(7, Math.min(93, pawn.x)) - pawn.x} y={pawn.y < 8 ? 7 : -5} textAnchor="middle" fontSize="2.6" fill="white" stroke="#101529" strokeWidth=".55" paintOrder="stroke" fontWeight="800">{p.name}{p.id === props.playerId ? ' ★' : ''}</text></g>; })}</>;
}
function DiscScene({ s, props }: { s: RicochetState; props: MinigameViewProps }) {
  return <><rect width="100" height="100" fill="#101b37"/><path d="M5 5H95V95H5Z" fill="none" stroke="#5ddbec" strokeWidth=".6"/><path d="M50 5V95M5 50H95" stroke="#314566" strokeWidth=".4" strokeDasharray="1 3"/><Obstacles walls={DISC_WALLS}/>
    {s.discs.map((d) => <g key={d.id}><path d={`M${d.x - d.vx * .05} ${d.y - d.vy * .05}L${d.x} ${d.y}`} stroke={d.bounced ? '#ffc989' : '#71ecff'} strokeWidth="1" opacity=".6"/><circle cx={d.x} cy={d.y} r="1" fill={d.bounced ? '#ffc989' : '#a6f5ff'} stroke="white" strokeWidth=".3"/></g>)}
    <Pawns state={s} props={props}/>{Object.entries(s.players).map(([id, p]) => <g key={id} transform={`translate(${p.x} ${p.y})`}><path d={`M${p.facingX * 4} ${p.facingY * 4}l${p.facingX * 3} ${p.facingY * 3}`} stroke="#c7faff" strokeWidth=".6"/>{p.protectedUntil > props.now && <circle r="4.3" fill="none" stroke="#adf4ff" strokeDasharray="1 1"/>}<text y="6" textAnchor="middle" fontSize="2.8" fill="#ffabbf">{'♥'.repeat(Math.max(0, p.hp))}</text></g>)}</>;
}
function FuseScene({ s, props }: { s: FuseState; props: MinigameViewProps }) {
  const p = s.players[s.carrier], left = Math.max(0, (s.explodesAt - props.now) / 1000);
  return <><rect width="100" height="100" fill="#25213c"/>{Array.from({ length: 10 }, (_, i) => <path key={i} d={`M0 ${i * 10}H100M${i * 10} 0V100`} stroke="#48405d" strokeWidth=".25"/>)}<circle cx="50" cy="50" r="42" fill="none" stroke="#ffbb71" strokeWidth=".5" strokeDasharray="1 2"/><Obstacles walls={FUSE_WALLS}/><Pawns state={s} props={props}/>
    {p && <g transform={`translate(${p.x} ${p.y})`}><circle r="5" fill="none" stroke={left < 3 ? '#ff777e' : '#ffc57e'} strokeWidth="1"/><circle cx="4" cy="3" r="2.8" fill="#ffb46a" stroke="#fff0b4" strokeWidth=".5"/><path d="M4 1q-1 -2 1 -3" fill="none" stroke="#fff2a9" strokeWidth=".7"/><text y="9" fill="#fff0d5" textAnchor="middle" fontSize="3.5" fontWeight="900">{left.toFixed(1)}s</text></g>}
    {props.now < s.breakUntil && <g><rect x="20" y="41" width="60" height="18" rx="5" fill="#131b35ed"/><text x="50" y="49" textAnchor="middle" fill="#ffd397" fontSize="5">BOOM!</text><text x="50" y="55" textAnchor="middle" fill="white" fontSize="3">Next round…</text></g>}</>;
}
function GravityScene({ s, props }: { s: GravityState; props: MinigameViewProps }) {
  return <><rect width="100" height="100" fill="#102b38"/>{Array.from({ length: 5 }, (_, i) => <ellipse key={i} cx="50" cy="50" rx={10 + i * 10} ry={6 + i * 10} fill="none" stroke="#487d89" strokeWidth=".25"/>)}
    {Object.entries(s.sides).map(([id, side]) => { const p = props.match.players.find((p) => p.id === id)!; return <g key={id}><rect x={side ? 92 : 0} y="37" width="8" height="26" rx="3" fill={`${COLORS[p.avatarId]}44`} stroke={COLORS[p.avatarId]} strokeWidth=".7"/><text x={side ? 96 : 4} y="52" textAnchor="middle" fill="#fff" fontSize="3">{s.players[id].score}</text></g>; })}<Obstacles walls={GRAVITY_WALLS}/>
    {Object.entries(s.players).map(([id, p]) => p.pulling ? <path key={id} d={`M${p.x} ${p.y}L${s.pluto.x} ${s.pluto.y}`} stroke={COLORS[props.match.players.find((q) => q.id === id)!.avatarId]} strokeWidth="1" strokeDasharray="1 1"/> : null)}
    <g transform={`translate(${s.pluto.x} ${s.pluto.y})`}><circle r="3.2" fill="#ffdd80" stroke="#fff9d3" strokeWidth=".5"/><ellipse rx="5" ry="1.2" transform="rotate(-25)" fill="none" stroke="#ffdc98" strokeWidth=".8"/><circle cx="-1" cy="-1" r=".8" fill="#fff4bc"/></g><Pawns state={s} props={props}/></>;
}
function ColorScene({ s, props }: { s: ColorState; props: MinigameViewProps }) {
  const colors = Object.fromEntries(props.match.players.map((p) => [p.id, COLORS[p.avatarId]]));
  return <><rect width="100" height="100" fill="#17283b"/>{s.owners.map((owner, i) => <rect key={i} x={i % PAINT_SIZE * 100 / PAINT_SIZE + .25} y={Math.floor(i / PAINT_SIZE) * 100 / PAINT_SIZE + .25} width={100 / PAINT_SIZE - .5} height={100 / PAINT_SIZE - .5} rx=".5" fill={owner ? colors[owner] : '#283d51'} opacity={owner ? .85 : 1}/>)}
    {s.washAt - props.now <= 3000 && s.washAt < s.endsAt && <rect x={s.washColumn * 100 / PAINT_SIZE} width={100 / PAINT_SIZE} height="100" fill="#e5f5ff44" stroke="#efffff" strokeWidth=".7" strokeDasharray="1 1"/>}<Obstacles walls={paintWalls}/>{s.burstEvents.map((e, i) => <circle key={i} cx={e.x} cy={e.y} r={3 + (props.now - e.at) / 55} fill="none" stroke={colors[e.id]} strokeWidth="1.5" opacity={Math.max(0, 1 - (props.now - e.at) / 700)}/>)}<Pawns state={s} props={props}/></>;
}
export default function NewArcadeScreen(props: MinigameViewProps) {
  const { minigame, match, playerId, now, online } = props, id = minigame.minigameId, s = minigame.state as RicochetState | FuseState | GravityState | ColorState;
  const definition = minigameRegistry.get(id), me = s.players[playerId], active = online && !!me && now >= s.startedAt && now < s.endsAt && !('winner' in s && s.winner);
  const { change, aimAt, aimDirection } = useArcadeControls(active, props.sendInput, me);
  const actionName = id === 'ricochet-rivals' ? 'Dash' : id === 'gravity-tug' ? 'Pull' : 'Paint Burst';
  const cooldown = me ? Math.max(0, (me.nextActionAt - now) / 1000) : 0;
  return <div className="pp-new-game"><header className="pp-new-header"><div><span className="pp-eyebrow">{definition.gameType === 'duel' ? '1 VS 1 DUEL' : 'PAINT THE PARTY'}</span><h2>{definition.name}</h2></div><strong className="pp-new-timer">{Math.max(0, Math.ceil((s.endsAt - now) / 1000))}<small>SECONDS</small></strong></header>
    <div className="pp-new-standings">{match.players.filter((p) => s.players[p.id]).map((p) => <span key={p.id} className={p.id === playerId ? 'me' : ''} style={{ borderColor: COLORS[p.avatarId] }}><b>{p.name}</b><strong>{id === 'ricochet-rivals' ? `${(s as RicochetState).players[p.id].hp} ♥` : `${s.players[p.id].score} ${id === 'color-clash' ? 'tiles' : 'wins'}`}</strong></span>)}</div>
    <svg className="pp-new-arena" viewBox="0 0 100 100" role="img" aria-label={`${definition.name} arena`} onPointerMove={(e) => { const r = e.currentTarget.getBoundingClientRect(); aimAt((e.clientX - r.left) / r.width * 100, (e.clientY - r.top) / r.height * 100); }} onPointerDown={(e) => { if (id !== 'ricochet-rivals' || !active) return; e.preventDefault(); e.currentTarget.setPointerCapture(e.pointerId); const r = e.currentTarget.getBoundingClientRect(); aimAt((e.clientX - r.left) / r.width * 100, (e.clientY - r.top) / r.height * 100); change('MouseFire', true); }} onPointerUp={() => change('MouseFire', false)} onPointerCancel={() => change('MouseFire', false)} onLostPointerCapture={() => change('MouseFire', false)}>
      {id === 'ricochet-rivals' ? <DiscScene s={s as RicochetState} props={props}/> : id === 'fuse-faceoff' ? <FuseScene s={s as FuseState} props={props}/> : id === 'gravity-tug' ? <GravityScene s={s as GravityState} props={props}/> : <ColorScene s={s as ColorState} props={props}/>}
    </svg>
    <p className="pp-new-status" role="status">{'winner' in s && s.winner ? `${match.players.find((p) => p.id === s.winner)?.name} wins!` : !me ? 'Watching the duel' : id === 'fuse-faceoff' ? `Round ${(s as FuseState).round} / 5 · ${(s as FuseState).carrier === playerId ? 'YOU HAVE THE COMET — TAG YOUR RIVAL!' : 'KEEP YOUR DISTANCE!'}` : id === 'color-clash' ? 'Run to paint. Burst to steal territory.' : id === 'gravity-tug' ? 'Hold Pull to draw the Pluto into your glowing goal.' : 'Aim around cover. Orange discs are dangerous rebounds.'}</p>
    <div className="pp-new-controls"><DirectionPad active={active} change={change}/>{id !== 'fuse-faceoff' && <HoldButton active={active} controlKey="Space" label={actionName + (cooldown > 0 ? ` · ${cooldown.toFixed(1)}s` : '')} name={actionName} change={change}/>} {id === 'ricochet-rivals' && <><div className="pp-new-aim" aria-label="Aim direction">{[[0, -1, '↑'], [-1, 0, '←'], [0, 1, '↓'], [1, 0, '→']].map(([x, y, label]) => <button key={String(label)} type="button" disabled={!active} onPointerDown={(e) => { e.preventDefault(); aimDirection(Number(x), Number(y)); }} onClick={() => aimDirection(Number(x), Number(y))} aria-label={`Aim ${label}`}>{label}</button>)}</div><HoldButton active={active} controlKey="KeyF" label="Fire" name="Fire disc" change={change}/></>}</div><small className="pp-new-help">{definition.controls}{!online ? ' · Reconnecting…' : ''}</small>
  </div>;
}
