import type { Scenario, Question } from './naturaData';
const q = (text: string, answers: [string, string, string], correct: number, explanation: string): Question => ({ text, answers, correct, explanation });
export const EXPEDITION_SCENARIOS: Scenario[] = [
  { id: 'jumpingspider', icon: '🕷️', title: 'Silk & Summit', setting: 'Garden canopy · jumping spider',
    behaviour: 'Jumping spiders hunt using keen vision and leaps. They attach a silk dragline before jumping; the silk can act as a safety line.',
    source: { label: 'Natural History Museum: spider silk', url: 'https://www.nhm.ac.uk/discover/what-are-spider-webs-made-of.html' },
    rules: ['Explore eight large 3D courses with 24 platforms each. Reach the glowing summit by jumping across leaves, branches and stones. Cavern gates, slippery waterfall ledges, ridge wind and moving/wilting flowers introduce distinct challenges.', 'WASD moves across the ground; Space jumps. Shift spends a silk rescue to return to your checkpoint. Gold uses arrows, Enter and Right Shift.', 'Glowing checkpoint platforms save progress and refill two silk rescues. Falling uses a rescue, or costs a heart when silk is empty. Three lost hearts end the run.', 'Choose a course before starting. First to the summit wins; after 180 seconds compare checkpoints, then hearts. Local two-player and an AI rival are supported.'],
    abstraction: 'Courses, saved checkpoints, silk charges, hearts and a racing rival are arcade rules. The leaps and silk safety line are based on real jumping-spider behaviour.',
    questions: [q('What helps jumping spiders judge a leap?', ['Keen vision', 'Feathers', 'Antlers'], 0, 'Jumping spiders are visual hunters.'), q('What can a silk dragline do?', ['Act as a safety line', 'Make rain', 'Supply wings'], 0, 'Silk can support a spider after a leap.'), q('Which is a game invention?', ['Silk', 'Glowing saved checkpoints', 'Legs'], 1, 'The checkpoint system is an arcade aid.'), q('Are jumping spiders insects?', ['Yes', 'No, they are arachnids', 'Only young ones'], 1, 'Spiders are arachnids.'), q('How many legs does a spider normally have?', ['Six', 'Eight', 'Ten'], 1, 'Spiders have eight legs.'), q('Do jumping spiders need a large capture web to hunt?', ['Always', 'No, they can stalk and leap', 'Only underwater'], 1, 'They can hunt prey actively.')],
  },
  { id: 'spermwhale', icon: '🐋', title: 'Into the Abyss', setting: 'Southern Ocean · sperm whale & colossal squid',
    behaviour: 'Sperm whales (Physeter macrocephalus) hunt deep-water prey, including squid. Colossal squid (Mesonychoteuthis hamiltoni) live in the Southern Ocean; their remains have been found in sperm-whale stomachs.',
    source: { label: 'Te Papa: colossal squid', url: 'https://collections.tepapa.govt.nz/topic/588' },
    rules: ['Play a sperm whale. Find three colossal squid, approach and bite, then return to the surface. Watch your breath and avoid the red tentacle warning.', 'WASD swims horizontally. Q rises and E dives. Space bites; Left Shift sends an echolocation pulse that returns a fading direction, depth band and range band for four seconds.', 'Gold uses arrows, Page Up to rise, Page Down to dive, Enter to bite and Right Shift for sonar. On-screen controls offer all actions.', 'Surface above 3 metres to refill breath. Sonar gives a snapshot, not live tracking. Squid become visible when you approach them. Red rings warn of a defensive strike; swim clear before it lands.', 'First to complete three hunts and surface wins. At 180 seconds compare catches, then health. In solo play the deep ocean is your opponent; local play lets two whales race.'],
    abstraction: 'This is a stylized hunting game. Squid health, telegraphed attacks, repeated encounters and sonar graphics are inventions; detailed battles in the wild are poorly observed. Colossal squid and giant squid (Architeuthis dux) are different species.',
    questions: [q('Which whale hunts squid in this mode?', ['Sperm whale', 'Blue whale', 'Bowhead whale'], 0, 'Sperm whales are toothed predators that eat squid.'), q('Where do colossal squid live?', ['Southern Ocean', 'Desert pools', 'Freshwater rivers'], 0, 'They inhabit Antarctic and sub-Antarctic waters.'), q('Are giant and colossal squid the same species?', ['Yes', 'No', 'Only as juveniles'], 1, 'Architeuthis dux and Mesonychoteuthis hamiltoni are different species.'), q('Why must a sperm whale surface?', ['To breathe air', 'To change its skin', 'To grow fins'], 0, 'Whales are air-breathing mammals.'), q('What can help a sperm whale locate prey?', ['Echolocation clicks', 'A glowing map', 'Leaves'], 0, 'Sperm whales produce clicks for echolocation.'), q('Which is an arcade invention?', ['Deep dives', 'Squid prey', 'A red tentacle-warning ring'], 2, 'The ring helps players respond to a simplified attack.')],
  },
];
